### ISSUE TITLE
Problem with UID caching: metricX, already mapped to metricY

### ISSUE THREAD

**Issue by OreljL** [OpenTSDB/opentsdb#1002]
There is a problem with creation or persisting data with multiple metrics while trying to put data with /api/put

I am getting following exception:
`java.lang.IllegalStateException: id=[0, 0, -127] => name=sampleMetric129, already mapped to sampleMetric128
        at net.opentsdb.uid.UniqueId.addNameToCache(UniqueId.java:328) ~[tsdb-2.3.0.jar:38c6f67]
        at net.opentsdb.uid.UniqueId.cacheMapping(UniqueId.java:651) ~[tsdb-2.3.0.jar:38c6f67]
        at net.opentsdb.uid.UniqueId.access$1700(UniqueId.java:57) ~[tsdb-2.3.0.jar:38c6f67]
        at net.opentsdb.uid.UniqueId$UniqueIdAllocator.done(UniqueId.java:628) ~[tsdb-2.3.0.jar:38c6f67]
        at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:491) ~[tsdb-2.3.0.jar:38c6f67]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1533) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.2.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223) ~[asynchbase-1.7.2.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121) ~[asynchbase-1.7.2.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
`

So I dug a bit deeper and i think that commit 38c6f6708cf94d07ca491da8f02fb8776e11b069 breaks it.

I made a test case.

I build and installed opentsdb at commit 38c6f6708cf94d07ca491da8f02fb8776e11b069 and tried /api/put with 400 metrics ([test.txt](https://github.com/OpenTSDB/opentsdb/files/1094648/test.txt)t)

Result: mentioned exception

I build and installed opentsdb at commit 797c10191ef700720471a8e6cbf89181c6886caf (one commit before) and tried /api/put with 400 metrics ([test.txt](https://github.com/OpenTSDB/opentsdb/files/1094648/test.txt))

Result: it works normally

I used hbase 1.2.4 and default opentsdb config with auto create metrics set to true.

@manolama can you take a look?

**Comment by JoshKeegan** [comment]
I'm having what appears to be the same issue, having built from the latest src today.  
Is https://github.com/OpenTSDB/opentsdb/commit/797c10191ef700720471a8e6cbf89181c6886caf (as mentioned above not having this issue) the best commit to build from if I wanted a stable build?

**Comment by OreljL** [comment]
If you want stable build it is best to download released version 2.3.0 from https://github.com/OpenTSDB/opentsdb/releases

**Comment by manolama** [comment]
Ah good catch, thank you. I'll likely roll that back then.

**Comment by hailin0** [comment]
@manolama 

I also found this problem
This is my modification is right?

modify UniqueId.java
-------------------------------------------

  private void addNameToCache(final byte[] id, final String name) {
    final String key = Arrays.toString(id);
  }

  private String getNameFromCache(final byte[] id) {
    return id_cache.get(Arrays.toString(id));
  }

**Comment by Harshvardhan28** [comment]
@OreljL  did you got the solution for this problem? I'm also running with the same issue. I'm using Big Table.

OpenTSDB(On Kubernetes) version - 2.3.0
