### ISSUE TITLE
UniqueId: Failed pending assignment for: container_1497975008857_0067_01_000008

### ISSUE THREAD

**Issue by EddiePi** [OpenTSDB/opentsdb#1009]
This error happens once in a while. Every time I have to drop all the table and create them again to correct this. When this error happens, a tag will be assigned to an incorrect value which already existed in opentsdb but assigned to other data points.
Here is the full log:
`2017-06-28 16:05:45,679 INFO  [OpenTSDB I/O Boss #1] ConnectionManager: [id: 0x3abb8b78, /127.0.0.1:37966 => /127.0.0.1:4242] OPEN
2017-06-28 16:05:45,679 INFO  [OpenTSDB I/O Worker #8] ConnectionManager: [id: 0x3abb8b78, /127.0.0.1:37966 => /127.0.0.1:4242] BOUND: /127.0.0.1:4242
2017-06-28 16:05:45,679 INFO  [OpenTSDB I/O Worker #8] ConnectionManager: [id: 0x3abb8b78, /127.0.0.1:37966 => /127.0.0.1:4242] CONNECTED: /127.0.0.1:37966
2017-06-28 16:05:45,681 INFO  [OpenTSDB I/O Worker #8] UniqueId: Creating an ID for kind='tagv' name='container_1497975008857_0067_01_000008'
2017-06-28 16:05:45,686 INFO  [AsyncHBase I/O Worker #2] UniqueId: Got ID=166 for kind='tagv' name='container_1497975008857_0067_01_000008'
2017-06-28 16:05:45,698 WARN  [AsyncHBase I/O Worker #2] UniqueId: Failed pending assignment for: container_1497975008857_0067_01_000008
java.lang.IllegalStateException: id=[0, 0, -90] => name=container_1497975008857_0067_01_000008, already mapped to application_1497975008857_0067
	at net.opentsdb.uid.UniqueId.addNameToCache(UniqueId.java:328) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId.cacheMapping(UniqueId.java:651) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId.access$1700(UniqueId.java:57) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId$UniqueIdAllocator.done(UniqueId.java:628) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:491) ~[tsdb-2.3.0.jar:7e88284]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) [asynchbase-1.8.0.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1536) [asynchbase-1.8.0.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.8.0.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1226) [asynchbase-1.8.0.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3678) [asynchbase-1.8.0.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2017-06-28 16:05:45,698 INFO  [OpenTSDB I/O Worker #8] UniqueId: Completed pending assignment for: container_1497975008857_0067_01_000008
2017-06-28 16:05:45,699 ERROR [OpenTSDB I/O Worker #8] HttpQuery: [id: 0x3abb8b78, /127.0.0.1:37966 => /127.0.0.1:4242] Internal Server Error on /api/put
java.lang.IllegalStateException: id=[0, 0, -90] => name=container_1497975008857_0067_01_000008, already mapped to application_1497975008857_0067
	at net.opentsdb.uid.UniqueId.addNameToCache(UniqueId.java:328) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId.cacheMapping(UniqueId.java:651) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId.access$1700(UniqueId.java:57) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId$UniqueIdAllocator.done(UniqueId.java:628) ~[tsdb-2.3.0.jar:7e88284]
	at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:491) ~[tsdb-2.3.0.jar:7e88284]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na]
	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) ~[asynchbase-1.8.0.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1536) ~[asynchbase-1.8.0.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.8.0.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1226) ~[asynchbase-1.8.0.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3678) ~[asynchbase-1.8.0.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2017-06-28 16:05:45,700 INFO  [OpenTSDB I/O Worker #8] HttpQuery: [id: 0x3abb8b78, /127.0.0.1:37966 => /127.0.0.1:4242] HTTP /api/put done in 20ms`

Anyone know about the issure? Thank you!

**Comment by manolama** [comment]
Hi, which version of TSD are you running? We just rolled back a bug that could potentially affect this.

If it's an older version then try running the UID fsck utility instead of deleting and see if that resolves the issues. It could be that the writes are coming through so fast that the assignments are overstepping each other or just timing out looking for a new UID.

**Comment by EddiePi** [comment]
@manolama Hi, I am user TSD-2.3.0 built from 7e88284. Indeed, The data is coming really fast. I will try UID fsck if I encounter the problem again. Thank you!

**Comment by EddiePi** [comment]
@manolama Hi. I have encountered this issue again and used fsck command. But the result showed that there is no error in TSD.
Here is the command I used:
`tsdb fsck --full-scan --threads=8 --fix`

And here is the results:
`2017-07-13 11:31:02,806 INFO  [main] Fsck: Key Values Processed: 285695
2017-07-13 11:31:02,806 INFO  [main] Fsck: Rows Processed: 37900
2017-07-13 11:31:02,806 INFO  [main] Fsck: Valid Datapoints: 12401170
2017-07-13 11:31:02,806 INFO  [main] Fsck: Annotations: 0
2017-07-13 11:31:02,806 INFO  [main] Fsck: Invalid Row Keys Found: 0
2017-07-13 11:31:02,806 INFO  [main] Fsck: Invalid Rows Deleted: 0
2017-07-13 11:31:02,806 INFO  [main] Fsck: Duplicate Datapoints: 0
2017-07-13 11:31:02,806 INFO  [main] Fsck: Duplicate Datapoints Resolved: 0
2017-07-13 11:31:02,806 INFO  [main] Fsck: Orphaned UID Rows: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Orphaned UID Rows Deleted: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Possible Future Objects: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Unknown Objects: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Unknown Objects Deleted: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Unparseable Datapoint Values: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Unparseable Datapoint Values Deleted: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Improperly Encoded Floating Point Values: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Improperly Encoded Floating Point Values Fixed: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Unparseable Compacted Columns: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Unparseable Compacted Columns Deleted: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Datapoints Qualified for VLE : 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Datapoints Compressed with VLE: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Bytes Saved with VLE: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Total Errors: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Total Correctable Errors: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Total Errors Fixed: 0
2017-07-13 11:31:02,807 INFO  [main] Fsck: Completed fsck in [2] seconds
2017-07-13 11:31:02,807 INFO  [main] TSDB: Flushing compaction queue
2017-07-13 11:31:02,809 INFO  [main] HBaseClient: Channel [id: 0x729e7b59, /192.168.32.111:60088 => /192.168.32.112:16020] is disconnecting: [id: 0x729e7b59, /192.168.32.111:60088 => /192.168.32.112:16020] DISCONNECT
2017-07-13 11:31:02,810 INFO  [main] HBaseClient: Channel [id: 0x66a8ba65, /192.168.32.111:52044 => /192.168.32.111:16020] is disconnecting: [id: 0x66a8ba65, /192.168.32.111:52044 => /192.168.32.111:16020] DISCONNECT
2017-07-13 11:31:02,810 INFO  [main] HBaseClient: Lost connection with the .META. region
2017-07-13 11:31:02,810 INFO  [main] HBaseClient: Channel [id: 0xc638183a, /192.168.32.111:33732 => /192.168.32.119:16020] is disconnecting: [id: 0xc638183a, /192.168.32.111:33732 => /192.168.32.119:16020] DISCONNECT
2017-07-13 11:31:02,812 INFO  [main] TSDB: Completed shutting down the TSDB`

**Comment by jasonw580** [comment]
@EddiePi @manolama Hi,I encounted such problem.Did you resolve the trouble？How? Thanks!
