### ISSUE TITLE
net.opentsdb.uid.NoSuchUniqueName: No such name for 'metrics'  issue while inserting metric data.

### ISSUE THREAD

**Issue by sjmittal** [OpenTSDB/opentsdb#1039]
I am using a plugin https://github.com/OpenTSDB/opentsdb-rpc-kafka to insert record into opentsdb.

However when it tries to insert into hbase it gets this error. I am not sure what it means.

Stacktrace below.

```

2017-08-04 18:11:49,795 ERROR [TsdbConsumer_2_Sachin-PC] Metric: Unexpected exception adding data point metric=fname.metric ts=1501104188693 value=2081.0 key1=A4key2=B2
net.opentsdb.uid.NoSuchUniqueName: No such name for 'metrics': 'fname.metric'
        at net.opentsdb.uid.UniqueId$1GetIdCB.call(UniqueId.java:356) ~[opentsdb-2.4.0-SNAPSHOT.jar:na]
        at net.opentsdb.uid.UniqueId$1GetIdCB.call(UniqueId.java:1) ~[opentsdb-2.4.0-SNAPSHOT.jar:na]
```

Is there something like a metric name I need to register in opentsdb first.

**Comment by sjmittal** [comment]
I figured out the issue setting tsd.core.auto_create_metrics = true works !
