### ISSUE TITLE
security hbase problem:Sasl initialization failed with a status of [1]: org.hbase.async.SecureRpcHelpe

### ISSUE THREAD

**Issue by shitWang** [OpenTSDB/opentsdb#1062]
Hi ,opentsdb

# When i started opentsdb 2.2.0 ,Some error  throwed following: @manolama

`11:13:20.692 ERROR [SecureRpcHelper96.handleResponse] - Sasl initialization failed with a status of [1]: org.hbase.async.SecureRpcHelper96@12ae710e
11:13:20.693 ERROR [RegionClient.exceptionCaught] - Unexpected exception from downstream on [id: 0x7af68a9c, /132.121.117.201:39469 => /132.121.91.233:60020]
java.lang.IllegalArgumentException: Read byte array length that's too large: 1784772193 > 268435455 in buf=ReplayingDecoderBuffer(ridx=12, widx=64)="\x00\x00\x00\x01\x00\x00\x00!javax.security.sasl.SaslException\x00\x00\x00\x13GSS initiate failed"
	at org.hbase.async.HBaseRpc.checkArrayLength(HBaseRpc.java:1007) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.HBaseRpc.readHadoopString(HBaseRpc.java:1074) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.RegionClient.consumeTimedoutNonPBufRPC(RegionClient.java:1623) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1437) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.1.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1206) ~[asynchbase-1.7.1.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3108) [asynchbase-1.7.1.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
11:13:20.693 INFO  [HBaseClient.handleDisconnect] - Channel [id: 0x7af68a9c, /132.121.117.201:39469 => /132.121.91.233:60020] is disconnecting: [id: 0x7af68a9c, /132.121.117.201:39469 => /132.121.91.233:60020] CLOSE
11:13:20.693 INFO  [HBaseClient.removeClientFromCache] - Lost connection with the .META. region
11:13:20.694 ERROR [SecureRpcHelper96.handleResponse] - Sasl initialization failed with a status of [2016310117]: org.hbase.async.SecureRpcHelper96@12ae710e
11:13:20.695 ERROR [RegionClient.exceptionCaught] - Unexpected exception from downstream on [id: 0x7af68a9c, /132.121.117.201:39469 :> /132.121.91.233:60020]
java.lang.IllegalArgumentException: Read byte array length that's too large: 1954098803 > 268435455 in buf=ReplayingDecoderBuffer(ridx=24, widx=64)=[0, 0, 0, 1, 0, 0, 0, 33, 106, 97, 118, 97, 120, 46, 115, 101, 99, 117, 114, 105, 116, 121, 46, 115, 97, 115, 108, 46, 83, 97, 115, 108, 69, 120, 99, 101, 112, 116, 105, 111, 110, 0, 0, 0, 19, 71, 83, 83, 32, 105, 110, 105, 116, 105, 97, 116, 101, 32, 102, 97, 105, 108, 101, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	at org.hbase.async.HBaseRpc.checkArrayLength(HBaseRpc.java:1007) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.HBaseRpc.readHadoopString(HBaseRpc.java:1074) ~[asynchbase-1.7.1.jar:na]

**Comment by shitWang** [comment]
# When i started opentsdb 2.2.0 ,Some error  throwed following:

**Comment by shitWang** [comment]
My hbase enabled and some tables necessary are created

**Comment by shitWang** [comment]
I have already solved this problem,if you  have a same question. you should check your config:hbase.kerberos.regionserver.principal
