### ISSUE TITLE
NoSuchMethodError ConcurrentHashMap.keySet

### ISSUE THREAD

**Issue by a414930249** [OpenTSDB/opentsdb#1128]
I encounter an error when starting the opentsdb

the error message: 
Exception in thread "main" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at org.hbase.async.HBaseClient.flush(HBaseClient.java:811)
	at org.hbase.async.HBaseClient.shutdown(HBaseClient.java:1061)
	at net.opentsdb.core.TSDB$1HClientShutdown.call(TSDB.java:1135)
	at net.opentsdb.core.TSDB$1HClientShutdown.call(TSDB.java:1130)
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
	at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688)
	at com.stumbleupon.async.Deferred.addCallbackDeferring(Deferred.java:738)
	at net.opentsdb.core.TSDB.shutdown(TSDB.java:1209)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:233)

it seems that the compile java version is java 8,  but my jdk version is 1.7.0_80. 
Is there any solution can solve this problem without changing the version of my jdk?

**Comment by manolama** [comment]
You may need to recompile asynchbase with 1.7 or try another version of AsyncHBase which I should have fixed and compiled with 1.7
