### ISSUE TITLE
Fsck finding negative timestamps, crashes without fixing the issue

### ISSUE THREAD

**Issue by heaje** [OpenTSDB/opentsdb#1134]
I don't know how this occurred, but when I attempt to run a fsck with any of the flags enabled, I get errors like this:

<pre>2018-01-23 07:48:54,438 ERROR [Fsck #14] Fsck: Shouldn't be here
org.hbase.async.RemoteException: java.io.IOException: Timestamp cannot be negative. ts=-9223372036854775808
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2236)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:183)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:163)
Caused by: java.lang.IllegalArgumentException: Timestamp cannot be negative. ts=-9223372036854775808
        at org.apache.hadoop.hbase.client.Put.addImmutable(Put.java:306)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.toPut(ProtobufUtil.java:619)
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.mutate(RSRpcServices.java:2213)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:33646)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2191)
        ... 3 more
        at org.hbase.async.RegionClient.makeException(RegionClient.java:1758) ~[asynchbase-1.8.0.jar:na]
        at org.hbase.async.RegionClient.decodeException(RegionClient.java:1776) ~[asynchbase-1.8.0.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1488) ~[asynchbase-1.8.0.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.8.0.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1226) ~[asynchbase-1.8.0.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2236)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:183)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:163)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2236)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:183)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:163)
Caused by: java.lang.IllegalArgumentException: Timestamp cannot be negative. ts=-9223372036854775808
        at org.apache.hadoop.hbase.client.Put.addImmutable(Put.java:306)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.toPut(ProtobufUtil.java:619)
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.mutate(RSRpcServices.java:2213)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:33646)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2191)
        ... 3 more
        at org.hbase.async.RegionClient.makeException(RegionClient.java:1758) ~[asynchbase-1.8.0.jar:na]
        at org.hbase.async.RegionClient.decodeException(RegionClient.java:1776) ~[asynchbase-1.8.0.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1488) ~[asynchbase-1.8.0.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.8.0.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1226) ~[asynchbase-1.8.0.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3678) ~[asynchbase-1.8.0.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.9.4.Final.jar:na]</pre>

I am currently running OpenTSDB 2.4.0 RC2 using Oracle JDK 1.8u152.  I have run fsck like this:
`tsdb fsck --config=</path/to/config.conf> --fix-all --full-scan`

I have found that the problem only occurs if the "--fix" or "--fix-all" flags are provided.

**Comment by heaje** [comment]
Any direction on what I should be looking for debug-wise?  I have tried doing this with DEBUG logging enabled, but I didn't get any additional information.  I'd love to even be able to track down which rows in the tsdb table are causing this problem.

**Comment by manolama** [comment]
Yeah that's a bad rowkey or value so we'll need to catch and drop it.

**Comment by manolama** [comment]
Merged in d43a3d95c1d3585217e30a5869f0413a5e35aabe
