### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by jyzhangbo** [OpenTSDB/opentsdb#1211]
the version is 2.4.0RC2
when I use the GUI to query data, it has error

2018-05-18 11:26:45,989 ERROR [Gnuplot #1] HttpQuery: [id: 0x3d85704a, /10.198.166.2:54410 => /10.16.44.108:4242] Internal Server Error on /q?start=2018/05/18-00:00:00&end=2018/05/18-11:26:47&m=sum:light.colour.col&o=&yrange=%5B0:%5D&wxh=1516x594&style=linespoint&json
java.lang.NullPointerException: null
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012) ~[na:1.8.0_171]
	at net.opentsdb.tsd.GraphHandler.runGnuplot(GraphHandler.java:786) ~[tsdb-2.4.0RC2.jar:]
	at net.opentsdb.tsd.GraphHandler$RunGnuplot.execute(GraphHandler.java:353) ~[tsdb-2.4.0RC2.jar:]
	at net.opentsdb.tsd.GraphHandler$RunGnuplot.run(GraphHandler.java:340) ~[tsdb-2.4.0RC2.jar:]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by manolama** [comment]
Hi, do you have GNUplot installed on your host system and available from the environment?
