### ISSUE TITLE
ERROR ConnectionManager: Unexpected exception from downstream

### ISSUE THREAD

**Issue by qingchn** [OpenTSDB/opentsdb#1223]
I use Opentsdb version is 2.4.0 in docker, when I use multiple containers, I find more error
`2018-05-29 21:55:26,620 ERROR ConnectionManager: Unexpected exception from downstream for [id: 0x981d4f33, /10.10.100.20:53659 :> /172.30.15.16:4242]
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_102]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_102]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_102]
	at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[na:1.8.0_102]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_102]
	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromSelectorLoop(AbstractNioWorker.java:158) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:114) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]`

I do not know how caaused the error？

**Comment by HariSekhon** [comment]
I've got this same issue on OpenTSDB 2.3.

It appears to happen after an HBase cluster wide restart. Why isn't OpenTSDB just closing and re-opening connections?

Looks like a bug to me. The HBase cluster was back up and working properly but TSDs were making no use of it and just repeating this exception over and over in the logs:
```
2018-07-31T16:07:37.473+0000 ERROR [RegionClient.exceptionCaught] - Unexpected exception from downstream on [id: 0xFFFFFFFF, /x.x.x.x:47764 :> /x.x.x.x:16020]
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_121]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_121]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_121]
        at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[na:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_121]
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromSelectorLoop(AbstractNioWorker.java:158) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:114) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by HariSekhon** [comment]
This causes data loss on TSDB clusters when there is a HBase restart and is a very severe bug in OpenTSDB.

I think some code needs to be added to catch and re-open connections in these situations as this can stay broken indefinitely by the look of it until someone notices and does an OpenTSDB restart on all OpenTSDB nodes in the cluster :-/

**Comment by suishaojian** [comment]
So how to solved this problem since I met this error too with opentsdb2.4 ??
thank you so much if anyone could offer any suggestion..

**Comment by qingchn** [comment]
not solved. I use Multiple instances in k8s。

**Comment by amariniml** [comment]
Hello there, any news about this issue? I'm having the same problem using Big Table + OpenTSDB.

**Comment by laudukang** [comment]
I have same issue, and write new data to opentsdb will cause Connection reset
