### ISSUE TITLE
 The method addNameToCache of UniqueId Class throws Exception

### ISSUE THREAD

**Issue by LynnYuanInspur** [OpenTSDB/opentsdb#1231]
When put ts data to Tsdb, it throws Exception:
java.lang.IllegalStateException: id=[3, 5, -21] =&gt; name=64be0453-a368-495f-a331-2a2d1ad798ca, already mapped to c74950b7-d6b0-4653-b695-1be46cea8043
	at net.opentsdb.uid.UniqueId.addNameToCache(UniqueId.java:401) ~[tsdb-2.4.0RC2.jar:]
	at net.opentsdb.uid.UniqueId.cacheMapping(UniqueId.java:742) ~[tsdb-2.4.0RC2.jar:]
	at net.opentsdb.uid.UniqueId.access$1900(UniqueId.java:62) ~[tsdb-2.4.0RC2.jar:]
	at net.opentsdb.uid.UniqueId$UniqueIdAllocator.done(UniqueId.java:719) ~[tsdb-2.4.0RC2.jar:]
	at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:582) ~[tsdb-2.4.0RC2.jar:]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) [asynchbase-1.8.0.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1536) [asynchbase-1.8.0.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.8.0.jar:na]

source codes:
private void addNameToCache(final byte[] id, final String name) {
    final String key = fromBytes(id);
    String found = use_lru ? lru_id_cache.getIfPresent(key) : id_cache.get(key);
    if (found == null) {
      if (use_lru) {
        lru_id_cache.put(key, name);
      } else {
        found = id_cache.putIfAbsent(key, name);
      }
    }
    if (found != null && !found.equals(name)) {
      throw new IllegalStateException("id=" + Arrays.toString(id) + " => name="
          + name + ", already mapped to " + found);
    }
  }

private static String fromBytes(final byte[] b) {
    return new String(b, CHARSET);
  }

The 'tsdb-uid' table in hbase:
hbase(main):002:0> get 'tsdb-uid' , 'c74950b7-d6b0-4653-b695-1be46cea8043'
COLUMN                                       CELL                                                                                                                           
 id:tagv                                     timestamp=1528683668678, value=\x03\x05\x80                                                                                    
1 row(s) in 0.1220 seconds

hbase(main):006:0> get 'tsdb-uid', '64be0453-a368-495f-a331-2a2d1ad798ca'
COLUMN                                       CELL                                                                                                                           
 id:tagv                                     timestamp=1528684021713, value=\x03\x05\xEB                                                                                    
1 row(s) in 0.0080 seconds

The test codes as follows:
       String hex1 = "030580";
        byte[] b1 = Bytes.fromHex(hex1);
        String s1 = new String(b1, CHARSET);
        System.out.println(s1);

        String hex2 = "0305A6";
        byte[] b2 = Bytes.fromHex(hex2);
        String s2 = new String(b2, CHARSET);
        System.out.println(s2);

        Assert.assertEquals(s1, s2);

The Result:
![image](https://user-images.githubusercontent.com/11604685/41210731-009376ba-6d66-11e8-915e-b9d07a3082f4.png)

**Comment by LynnYuanInspur** [comment]
If i modify the method fromBytes as follows, can it fix the issue?
private static String fromBytes(final byte[] b) {
    Long val = org.hbase.async.Bytes.getLong(b);
    return org.hbase.async.Bytes.hex(val);
  }

**Comment by manolama** [comment]
There are a number of places to change the code for UTF-8 support and if you do, make sure to truncate your UID and data tables before trying to use the system. 3.0 now supports UTF-8 properly.
