### ISSUE TITLE
Query exception: java.lang.RuntimeException: No more elements

### ISSUE THREAD

**Issue by HariSekhon** [OpenTSDB/opentsdb#1300]
Is this a bug?

Do we know what is likely to have caused this in the code?

This happened about 45 minutes after an HBase rolling restart finished, not sure if it is related.

```
2018-08-07T10:14:14.337+0000 ERROR [QueryRpc.call] - Query exception:
java.lang.RuntimeException: No more elements
        at net.opentsdb.query.expression.TimeSyncedIterator.next(TimeSyncedIterator.java:163) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.UnionIterator.next(UnionIterator.java:450) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.ExpressionIterator.next(ExpressionIterator.java:446) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.EDPtoDPS$Iterator.next(EDPtoDPS.java:230) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.Absolute.abs(Absolute.java:70) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.Absolute.evaluate(Absolute.java:52) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.ExpressionTree.evaluate(ExpressionTree.java:182) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.ExpressionTree.evaluate(ExpressionTree.java:175) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.query.expression.ExpressionTree.evaluate(ExpressionTree.java:175) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.tsd.QueryRpc$1QueriesCB.call(QueryRpc.java:241) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.tsd.QueryRpc$1QueriesCB.call(QueryRpc.java:231) ~[tsdb-2.3.0.jar:]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:173) [async-1.4.0.jar:na]
        at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158) [async-1.4.0.jar:na]
        at com.stumbleupon.async.DeferredGroup.access$200(DeferredGroup.java:36) [async-1.4.0.jar:na]
        at com.stumbleupon.async.DeferredGroup$1NotifyOrdered.call(DeferredGroup.java:97) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at net.opentsdb.core.SaltScanner.mergeAndReturnResults(SaltScanner.java:292) [tsdb-2.3.0.jar:]
        at net.opentsdb.core.SaltScanner.validateAndTriggerCallback(SaltScanner.java:663) [tsdb-2.3.0.jar:]
        at net.opentsdb.core.SaltScanner.access$1400(SaltScanner.java:58) [tsdb-2.3.0.jar:]
        at net.opentsdb.core.SaltScanner$ScannerCB.close(SaltScanner.java:633) [tsdb-2.3.0.jar:]
        at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:372) [tsdb-2.3.0.jar:]
        at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:302) [tsdb-2.3.0.jar:]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.access$300(Deferred.java:430) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) [asynchbase-1.7.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1533) [asynchbase-1.7.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.7.2.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223) [asynchbase-1.7.2.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121) [asynchbase-1.7.2.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by manolama** [comment]
That's one I've never run into. It looks like a bug in the expression code and not necessarily anything related to HBase. V3 has improved expression code.
