### ISSUE TITLE
RpcHandler Error: "Unexpected exception caught while serving [null...", java.lang.RuntimeException: Should never be here

### ISSUE THREAD

**Issue by HariSekhon** [OpenTSDB/opentsdb#1305]
I've found the following error in one of my TSD logs today (OpenTSDB 2.3).

This looks like a bug / unexpected code path based on the exception message `Should never be here`?

May also be related to #1286 but it looks like a different handler and different part of the code based on different stack trace - the exception message is also slightly different but also indicating the author did not expect to get to this code path.

This followed about 20 minutes after completing an HBase rolling restart across all RegionServer for tuning should have finished, and the log immediately following it was `[HBaseClient.handleNSRE] - There are now 1000 RPCs pending due to NSRE on "tsdb-meta...`. I assume NSRE means the old HBase NotServingRegionException?

Based on the stack trace at first I thought it may have been a random UID collision (as low probability as that is) but now suspect more a delay in getting a new UID, but maybe treated as a 10x collision as I see 11 retries in the error stack trace?

Still, should this error be handled differently? This is a heavily loaded TSDB cluster with 330,000 metrics and several dozen TB of metric data on a not very big cluster (only 8 heavy nodes) so it's not surprising to see any little blip build up a big queue of requests. I've noticed TSDB doesn't seem to handle RegionServer restarts very well in terms of following regions around as they get migrated to other RegionServers during the rolling restart? 

```
2018-08-08T13:00:01.237+0000 ERROR [RpcHandler.logError] - [id: 0xffffffff, /x.x.x.x:51016 => /y.y.y.y:4242] Unexpected exception caught while serving [null, <my.metric.name>, 1533733193, <NN>, host=<hostname>, application=<myApp>, identifier=<blah>, name=<myName>]
java.lang.RuntimeException: Should never be here
        at net.opentsdb.uid.UniqueId.getOrCreateId(UniqueId.java:737) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.core.Tags.resolveAllInternal(Tags.java:617) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.core.Tags.resolveOrCreateAll(Tags.java:604) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.core.IncomingDataPoints.rowKeyTemplate(IncomingDataPoints.java:145) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.core.TSDB.addPointInternal(TSDB.java:963) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.core.TSDB.addPoint(TSDB.java:873) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.tsd.PutDataPointRpc.importDataPoint(PutDataPointRpc.java:460) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.tsd.PutDataPointRpc.execute(PutDataPointRpc.java:78) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.tsd.RpcHandler.handleTelnetRpc(RpcHandler.java:162) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:132) ~[tsdb-2.3.0.jar:]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
        at net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:128) [tsdb-2.3.0.jar:]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: org.hbase.async.NonRecoverableException: Too many attempts: GetRequest(table="tsdb-uid", key="<blah>", family="id", qualifiers=["tagv"], attempt=11, region=null)
        at org.hbase.async.HBaseClient.tooManyAttempts(HBaseClient.java:2056) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1920) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) ~[asynchbase-1.7.2.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addBothDeferring(Deferred.java:786) ~[async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1968) ~[asynchbase-1.7.2.jar:na]
        at org.hbase.async.HBaseClient.get(HBaseClient.java:1202) ~[asynchbase-1.7.2.jar:na]
        at net.opentsdb.uid.UniqueId.hbaseGet(UniqueId.java:1220) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.uid.UniqueId.getIdFromHBase(UniqueId.java:377) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.uid.UniqueId.getIdAsync(UniqueId.java:368) ~[tsdb-2.3.0.jar:]
        at net.opentsdb.uid.UniqueId.getOrCreateId(UniqueId.java:673) ~[tsdb-2.3.0.jar:]
        ... 45 common frames omitted
2018-08-08T13:00:01.294+0000 INFO  [HBaseClient.handleNSRE] - There are now 1000 RPCs pending due to NSRE on "tsdb-meta,\x......."
```

**Comment by manolama** [comment]
Yes, this means the region is down and hasn't been brought up on another server yet. Depending on the NSRE queue size it will start throwing this exception upstream and that's what the storage exception handler plugin interface is for. We simply requeue the data back into Kafka until the region is back online.
