### ISSUE TITLE
Call queue is full and HTTP Error 424

### ISSUE THREAD

**Issue by mancubus77** [OpenTSDB/opentsdb#1327]
Hi Crew

 I'm facing weird error message when query OpenTSDB (2.3) via Grafana.  Weird thing, that sometimes queries works fine, but sometimes they fail with HTTP ERROR 424. I would be appreciated for any ideas what could cause this 

```
2018-09-05 14:09:55,052 ERROR [SaltScanner.call] - Scanner Scanner(table="tsdb", start_key=[11, 0, 2, -53, 91, -113, 42, -112, 0, 0, 33, 2, 26, 47, 0, 0, 34, 1, -25, -83], stop_key=[11, 0, 2, -53, 91, -113, 98, -48], columns={"t"}, populate_blockcache=true, max_num_rows=128, max_num_kvs=4096, region=null, filter=KeyRegexpFilter("(?s)^.{8}(?:.{6})*\Q!\E.{3}(?:.{6})*\Q"\E(?:\Qç­\E)(?:.{6})*$", ISO-8859-1), scanner_id=0x0000000000009B1A) threw an exception
org.hbase.async.CallQueueTooBigException: Call queue is full on /0.0.0.0:16020, too many items queued ?
Caused by RPC: GetNextRowsRequest(scanner_id=0x0000000000009B1A, max_num_rows=128, region=null, attempt=0)
...skip...
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-09-05 14:09:55,053 ERROR [SaltScanner.mergeAndReturnResults] - After all of the scanners finished, at least one threw an exception
org.hbase.async.CallQueueTooBigException: Call queue is full on /0.0.0.0:16020, too many items queued ?
Caused by RPC: GetNextRowsRequest(scanner_id=0x0000000000009B1A, max_num_rows=128, region=null, attempt=0)
...skip...
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-09-05 14:09:55,343 ERROR [QueryRpc.call] - Query exception: 
com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
	at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169) [async-1.4.0.jar:na]
	at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158) [async-	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
...skip...
Caused by: org.hbase.async.CallQueueTooBigException: Call queue is full on /0.0.0.0:16020, too many items queued ?
Caused by RPC: GetNextRowsRequest(scanner_id=0x0000000000009B1A, max_num_rows=128, region=null, attempt=0)
	at org.hbase.async.CallQueueTooBigException.make(CallQueueTooBigException.java:62) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.CallQueueTooBigException.make(CallQueueTooBigException.java:34) ~
```

**Comment by HariSekhon** [comment]
This is an HBase performance tuning issue, I've recently solved this for a client of mine.
