### ISSUE TITLE
why Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException

### ISSUE THREAD

**Issue by meluo** [OpenTSDB/opentsdb#1332]
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at org.hbase.async.HBaseClient.<clinit>(HBaseClient.java:238)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:175)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:252)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:186)

**Comment by manolama** [comment]
Could you let us know how you built or installed OpenTSDB? Thanks.
