### ISSUE TITLE
Out of order timestamps in bulk file import

### ISSUE THREAD

**Issue by Jonathan34** [OpenTSDB/opentsdb#1350]
From: https://github.com/OpenTSDB/opentsdb.net/issues/99
Property tsd.core.bulk.allow_out_of_order_timestamps does not work in 2.3.1 version. Documentation says it s supported in 2.3...: http://opentsdb.net/docs/build/html/user_guide/configuration.html

:(

```
New timestamp=1537857720387 is less than or equal to previous=1537859699781 when trying to add value=[91, -87, -108, 49] to IncomingDataPoints([0, 0, 87, 91, -87, -36, -16, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 18, 0, 0, 3, 0, 0, 18, 0, 0, 4, 0, 0, 15] (metric=AcqTime), base_time=1537858800 (Tue Sep 25 07:00:00 UTC 2018), []) at net.opentsdb.core.IncomingDataPoints.addPointInternal(IncomingDataPoints.java:289) ~[tsdb-2.3.1.jar:eca1ef41] at net.opentsdb.core.IncomingDataPoints.addPoint(IncomingDataPoints.java:395) ~[tsdb-2.3.1.jar:eca1ef41] at net.opentsdb.tools.TextImporter.importFile(TextImporter.java:194) [tsdb-2.3.1.jar:eca1ef41] at net.opentsdb.tools.TextImporter.main(TextImporter.java:76) [tsdb-2.3.1.jar:eca1ef41]
```

```
{"short_revision":"eca1ef41","repo":"/opentsdb/build","host":"67024e5790cf","version":"2.3.1","full_revision":"eca1ef413bfde7cde5450e093d544118e0877ef0","repo_status":"MINT","user":"root","branch":"master","timestamp":"1537367591"}
```

Writing to Google Big Table...

Any workaround for this rather that sorting out the order (which is very hard in my case)?

**Comment by twegener-embertec** [comment]
OpenTSDB devs: Would it be possible to get the tsd.core.bulk.allow_out_of_order_timestamps option into a 2.3.x release? Without this, it means that 'tsdb scan' / 'tsdb import' does not round-trip when occasionally out-of-order data points are present (and they can be legitimately present). It seems like it is a bug if 'tsdb scan' / 'tsdb import' doesn't round-trip in all cases.

(I've manually brought in the patch for that into 2.3.0/2.3.1, and it seems to work fine:
https://github.com/OpenTSDB/opentsdb/commit/71f35ca4a4cc4763110ac10d8e9ff265e7d6a750
It would be nice to have that in the release proper.)
