### ISSUE TITLE
`tsdb fsck` never produces output

### ISSUE THREAD

**Issue by johnseekins** [OpenTSDB/opentsdb#1351]
According to docs, running `tsdb fsck` should produce output every 5 seconds "so that you know the utility is still working". Whenever I run the command, I never see output, regardless of the length of time I let it run (overnight, for example).
```
root@use1-hadoop-5:~# time /usr/share/opentsdb/bin/tsdb fsck --full-scan --fix-all --threads=64 --resolve-duplicates --compact                                                                                       
^C
real    2m15.291s
user    1m8.460s
sys     0m14.156s
```
It also appears that `fsck` isn't actually repairing any problems (as my database has a few duplicates I was trying to fix).

```
root@use1-hadoop-5:~# /usr/share/opentsdb/bin/tsdb version
net.opentsdb.tools 2.3.1 built at revision 1478380 (MINT)
Built on 2018/05/22 00:28:29 +0000 by hobbes@clhbase:/home/hobbes/OFFICIAL/build
```
```
root@use1-hadoop-5:~# hbase version
HBase 2.0.0.3.0.0.0-1634
Source code repository git://ctr-e138-1518143905142-361612-01-000007.hwx.site/grid/0/jenkins/workspace/HDP-parallel-ubuntu16/SOURCES/hbase revision=e2b26de927bc689e49a2dbaaca8e7c83197fe127
Compiled by jenkins on Thu Jul 12 20:57:02 UTC 2018
From source with checksum 0fa23f637c2895528e5c2ce76549ad44
```

**Comment by johnseekins** [comment]
I really think something is getting messed up with the `fsck` tool. Even using an example query from the docs (with a real metric from my cluster) fails hard:
```
root@use1-hadoop-4:~# /usr/share/opentsdb/bin/tsdb fsck --fix 1h-ago now sum zookeeper.avg_latency type=put
Exception in thread "main" java.util.NoSuchElementException: No such aggregator: now
        at net.opentsdb.core.Aggregators.get(Aggregators.java:200)
        at net.opentsdb.tools.CliQuery.parseCommandLineQuery(CliQuery.java:200)
        at net.opentsdb.tools.Fsck.main(Fsck.java:1206)
```

**Comment by johnseekins** [comment]
Alright, so the docs are wrong:
```
root@use1-hadoop-5:~# /usr/share/opentsdb/bin/tsdb fsck 1h-ago sum zookeeper.avg_latency type=scan
root@use1-hadoop-5:~# 
```
Removing `now` from the query let's it not fail. But it also doesn't report anything. This is similar behavior to the UID fsck command in our install:
```
root@use1-hadoop-5:~# /usr/share/opentsdb/bin/tsdb uid fsck 
root@use1-hadoop-5:~# 
```
The command seems to _run_, but produces no output.

**Comment by johnseekins** [comment]
Looking at an `strace` of a running `tsdb fsck --fix-all --full-scan --last-write-wins --resolve-duplicates --compact`, it _seems_ like the code is looping. But that might actually be intentional:
```
[pid  8439] futex(0x7f5dcc002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8439] futex(0x7f5dcc002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 287627283}, ffffffff <unfinished ...>
[pid  8432] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8432] futex(0x7f5cb8023b28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8432] write(52, "\1", 1)          = 1
[pid  8432] futex(0x7f5cb8023b54, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 300354389}, ffffffff <unfinished ...>
[pid  8142] <... epoll_wait resumed> [{EPOLLIN, {u32=51, u64=9530512707334176819}}], 8192, 500) = 1
[pid  8142] read(51, "\1", 128)         = 1
[pid  8142] write(52, "\1", 1)          = 1
[pid  8142] write(239, "\0\0\0\37\f\10\371\325\2\32\4Scan \1\21\30\265\202\200\200\220\376\344\257u \200\0018"..., 35) = 35
[pid  8142] epoll_wait(53, [{EPOLLIN, {u32=51, u64=9530512707334176819}}], 8192, 500) = 1
[pid  8142] read(51, "\1", 128)         = 1
[pid  8142] epoll_wait(53, [{EPOLLIN, {u32=239, u64=9858590759266025711}}], 8192, 500) = 1
[pid  8142] read(239, "\0\0\4c\341\10\10\371\325\2\22\332\10\n/org.apache.hadoop"..., 4096) = 1127
[pid  8142] read(239, 0x7f5db4011c37, 2969) = -1 EAGAIN (Resource temporarily unavailable)
[pid  8142] epoll_wait(53,  <unfinished ...>
[pid  8439] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8439] futex(0x7f5dcc002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8439] futex(0x7f5dcc002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 307813926}, ffffffff <unfinished ...>
[pid  8432] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8432] futex(0x7f5cb8023b28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8432] write(52, "\1", 1)          = 1
[pid  8142] <... epoll_wait resumed> [{EPOLLIN, {u32=51, u64=9530512707334176819}}], 8192, 500) = 1
[pid  8432] futex(0x7f5cb8023b54, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 320708809}, ffffffff <unfinished ...>
[pid  8142] read(51, "\1", 128)         = 1
[pid  8142] write(52, "\1", 1)          = 1
[pid  8142] write(239, "\0\0\0\37\f\10\372\325\2\32\4Scan \1\21\30\255\202\200\200\220\376\344\257u \200\0018"..., 35) = 35
[pid  8142] write(239, "\0\0\0\37\f\10\373\325\2\32\4Scan \1\21\30\253\202\200\200\220\376\344\257u \200\0018"..., 35) = 35
[pid  8142] write(239, "\0\0\0\37\f\10\374\325\2\32\4Scan \1\21\30\245\202\200\200\220\376\344\257u \200\0018"..., 35) = 35
[pid  8142] epoll_wait(53, [{EPOLLIN, {u32=51, u64=9530512707334176819}}], 8192, 500) = 1
[pid  8142] read(51, "\1", 128)         = 1
[pid  8142] epoll_wait(53, [{EPOLLIN, {u32=239, u64=9858590759266025711}}], 8192, 500) = 1
[pid  8142] read(239, "\0\0\4c\341\10\10\372\325\2\22\332\10\n/org.apache.hadoop"..., 4096) = 2254
[pid  8142] read(239, 0x7f5db401209e, 1842) = -1 EAGAIN (Resource temporarily unavailable)
[pid  8142] epoll_wait(53, [{EPOLLIN, {u32=239, u64=9858590759266025711}}], 8192, 500) = 1
[pid  8142] read(239, "\0\0\4c\341\10\10\374\325\2\22\332\10\n/org.apache.hadoop"..., 4096) = 1127
[pid  8142] read(239, 0x7f5db4011c37, 2969) = -1 EAGAIN (Resource temporarily unavailable)
[pid  8142] epoll_wait(53,  <unfinished ...>
[pid  7761] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  7761] futex(0x7f5ee0108a28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  7761] futex(0x7f5ee0108a54, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 355526306}, ffffffff <unfinished ...>
[pid  8439] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8439] futex(0x7f5dcc002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8439] futex(0x7f5dcc002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 327974503}, ffffffff <unfinished ...>
[pid  8601] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8601] futex(0x7f5ee0fbf128, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8601] futex(0x7f5ee0fbf154, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228887, 317365291}, ffffffff <unfinished ...>
[pid  8432] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8432] futex(0x7f5cb8023b28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8432] futex(0x7f5cb8023b54, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 340912138}, ffffffff <unfinished ...>
[pid  8439] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8439] futex(0x7f5dcc002228, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8439] futex(0x7f5dcc002254, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 347200202}, ffffffff <unfinished ...>
[pid  8138] <... epoll_wait resumed> [], 8192, 500) = 0
[pid  8138] epoll_wait(44,  <unfinished ...>
[pid  8432] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid  8432] futex(0x7f5cb8023b28, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  8432] write(52, "\1", 1)          = 1
[pid  8432] futex(0x7f5cb8023b54, FUTEX_WAIT_BITSET_PRIVATE, 1, {2228886, 360332909}, ffffffff <unfinished ...>
[pid  8142] <... epoll_wait resumed> [{EPOLLIN, {u32=51, u64=9530512707334176819}}], 8192, 500) = 1
[pid  8142] read(51, "\1", 128)         = 1
[pid  8142] write(52, "\1", 1)

**Comment by johnseekins** [comment]
Ah. I understand. `fsck` writes to the log file by default. It'd be nice if the docs indicated this a little more clearly, but it _does_ mention relying on the `logback.xml` file, so I supposed I should have intuited that.
