### ISSUE TITLE
fsck doesn't honor threads setting

### ISSUE THREAD

**Issue by johnseekins** [OpenTSDB/opentsdb#1389]
```
root@use1-hadoop-4:~# sudo^Cu opentsdb /usr/share/opentsdb/bin/tsdb fsck --fix-all --full-scan --compact 
root@use1-hadoop-4:~# sudo -u opentsdb /usr/share/opentsdb/bin/tsdb fsck --threads=24 --fix-all --full-scan --compact --threads=24                                                                   
2018-10-22 22:41:24,941 INFO  [main] Fsck: Starting full table scan
2018-10-22 22:41:24,951 INFO  [main] Fsck: Spooling up [7] worker threads
```
This appears to indicate that the FSCK object ignores the `threads` setting. I asked for 24 threads and instead got 7. This machine has 64 cores.

```
root@use1-hadoop-4:~# sudo -u opentsdb /usr/share/opentsdb/bin/tsdb version
net.opentsdb.tools 2.3.1 built at revision 1478380 (MINT)
Built on 2018/05/22 00:28:29 +0000 by hobbes@clhbase:/home/hobbes/OFFICIAL/build
```

**Comment by johnseekins** [comment]
Digging in a bit more:
```
"Fsck #7" #100 prio=5 os_prio=0 tid=0x00007fad18ebb000 nid=0x3dab in Object.wait() [0x00007facaabee000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.stumbleupon.async.Deferred.doJoin(Deferred.java:1138)
        - locked <0x00000005995f69a0> (a com.stumbleupon.async.Deferred$Signal)
        at com.stumbleupon.async.Deferred.joinUninterruptibly(Deferred.java:1064)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:770)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:299)

"Fsck #6" #99 prio=5 os_prio=0 tid=0x00007fad18eb0800 nid=0x3daa in Object.wait() [0x00007facaacef000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.stumbleupon.async.Deferred.doJoin(Deferred.java:1138)
        - locked <0x0000000598bdb9c0> (a com.stumbleupon.async.Deferred$Signal)
        at com.stumbleupon.async.Deferred.joinUninterruptibly(Deferred.java:1064)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:770)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:299)

"Fsck #5" #98 prio=5 os_prio=0 tid=0x00007fad18eaf000 nid=0x3da9 in Object.wait() [0x00007facaadf0000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.stumbleupon.async.Deferred.doJoin(Deferred.java:1138)
        - locked <0x000000059b1b4f28> (a com.stumbleupon.async.Deferred$Signal)
        at com.stumbleupon.async.Deferred.joinUninterruptibly(Deferred.java:1064)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:751)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:299)

"Fsck #4" #97 prio=5 os_prio=0 tid=0x00007fad18ead800 nid=0x3da8 in Object.wait() [0x00007facaaef1000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.stumbleupon.async.Deferred.doJoin(Deferred.java:1138)
        - locked <0x000000059a9377c8> (a com.stumbleupon.async.Deferred$Signal)
        at com.stumbleupon.async.Deferred.joinUninterruptibly(Deferred.java:1064)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:751)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:299)

"Fsck #3" #96 prio=5 os_prio=0 tid=0x00007fad18eb6000 nid=0x3da7 in Object.wait() [0x00007facaaff2000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.stumbleupon.async.Deferred.doJoin(Deferred.java:1138)
        - locked <0x000000059a5b47b0> (a com.stumbleupon.async.Deferred$Signal)
        at com.stumbleupon.async.Deferred.joinUninterruptibly(Deferred.java:1064)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:770)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:299)

"Fsck #2" #95 prio=5 os_prio=0 tid=0x00007fad18eb5000 nid=0x3da6 in Object.wait() [0x00007facab0f3000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.stumbleupon.async.Deferred.doJoin(Deferred.java:1138)
        - locked <0x000000059a794fb0> (a com.stumbleupon.async.Deferred$Signal)
        at com.stumbleupon.async.Deferred.joinUninterruptibly(Deferred.java:1064)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:770)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:299)

"Fsck #1" #94 prio=5 os_prio=0 tid=0x00007fad18eb2800 nid=0x3da5 in Object.wait() [0x00007facab7f6000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.stumbleupon.async.Deferred.doJoin(Deferred.java:1138)
        - locked <0x00000005996d9ce0> (a com.stumbleupon.async.Deferred$Signal)
        at com.stumbleupon.async.Deferred.joinUninterruptibly(Deferred.java:1064)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:770)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:299)
```
There are definitely only 7 threads for running the fsck. What does the `--threads` setting actually _do_?

**Comment by johnseekins** [comment]
Ah. According to http://opentsdb.net/docs/build/html/user_guide/writing/index.html#salting, we set the number of threads with `tsd.storage.salt.buckets` in the config file.
