### ISSUE TITLE
resovle tags ids async might cause fsck fail

### ISSUE THREAD

**Issue by qudongfang** [OpenTSDB/opentsdb#1409]
[`Fsck.fsckKey`](https://github.com/OpenTSDB/opentsdb/blob/e4da2c04846b752961d79ab520bbe027e0fdaea1/src/tools/Fsck.java#L503) will call [`Tags.resolveIds`](https://github.com/OpenTSDB/opentsdb/blob/e4da2c04846b752961d79ab520bbe027e0fdaea1/src/core/Tags.java#L730), while it cannot handle `DeferredGroupException` properly.

`Tags.resolveIds` might throw `DeferredGroupException` when one of the tag ids is not found, in which case, `NoSuchUniqueId` should be throwed.

I noticed that some of the codes [simmilar to this situation](https://github.com/OpenTSDB/opentsdb/blob/e4da2c04846b752961d79ab520bbe027e0fdaea1/src/search/TimeSeriesLookup.java#L144) had taken care of it.

Opentsdb version that I am using is 2.3.0, git commit: cac608ad7bfaf6315fd2319a8af37da307abdeb9
Current master branch has the same issue, git commit: e4da2c04846b752961d79ab520bbe027e0fdaea1

Issue background: For some unknown reason, some 'tagk' or 'tagk' cannot be found by uuid. I have not figured it out yet.

Error log:
```
2018-11-09 15:13:05,254 ERROR [Fsck #13] Fsck: Shouldn't be here
java.lang.RuntimeException: Shouldn't be here
	at net.opentsdb.core.Tags.resolveIds(Tags.java:738) ~[tsdb-2.3.0.jar:]
	at net.opentsdb.tools.Fsck$FsckWorker.fsckKey(Fsck.java:538) ~[tsdb-2.3.0.jar:]
	at net.opentsdb.tools.Fsck$FsckWorker.fsckRow(Fsck.java:337) ~[tsdb-2.3.0.jar:]
	at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:305) ~[tsdb-2.3.0.jar:]
com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
	at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.DeferredGroup.access$200(DeferredGroup.java:36) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.DeferredGroup$1NotifyOrdered.call(DeferredGroup.java:97) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na]
	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1533) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.2.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223) ~[asynchbase-1.7.2.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121) ~[asynchbase-1.7.2.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_71]
Caused by: net.opentsdb.uid.NoSuchUniqueId: No such unique ID for 'tagv': [-92, 66, -29]
	at net.opentsdb.uid.UniqueId$1GetNameCB.call(UniqueId.java:301) ~[tsdb-2.3.0.jar:]
	at net.opentsdb.uid.UniqueId$1GetNameCB.call(UniqueId.java:298) ~[tsdb-2.3.0.jar:]
	... 34 common frames omitted
```

**Comment by qudongfang** [comment]
@sidhhu  @manolama  Would you please review this issue and give some suggestions?
