### ISSUE TITLE
Stack  trace in opentsdb.log during tsdb import for exception: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by twegener-embertec** [OpenTSDB/opentsdb#1435]
When doing a bulk load via 'tsdb import',  there was an error: 'ERROR [CompactionQueue.call] - Failed to write a row to re-compact' in the opentsdb.log file, along with a large stack trace.

The 'tsdb import' output did not report this as an nsre / error (and returned with exit status 0):
```
tsd.hbase.nsre 1543373388 0
tsd.hbase.nsre.rpcs_delayed 1543373388 0
tsd.compaction.errors 1543373388 0 rpc=read
tsd.compaction.errors 1543373388 0 rpc=put
tsd.compaction.errors 1543373388 0 rpc=delete
```

This happened with a dump file of size 1.2 GB (compressed), and also another one that was ~900MB (compressed). Other imports, some of larger size, did not encounter this issue.

This was with opentsdb 2.3.1 with the following patch included for [https://github.com/OpenTSDB/opentsdb/commit/71f35ca4a4cc4763110ac10d8e9ff265e7d6a750]() for 'tsd.core.bulk.allow_out_of_order_timestamps = true'.

```
tsdb import blah.gz
```

Except from /var/log/opentsdb/opentsdb.log:
```
2018-11-28 02:49:48,123 [main] INFO  [TextImporter.main] - Total: imported 203204537 data points in 908.733s (223612.9 points/s)
2018-11-28 02:49:48,132 [main] INFO  [TSDB.shutdown] - Flushing compaction queue
2018-11-28 02:49:48,132 [main] INFO  [CompactionQueue.flush] - Flushing all old outstanding rows out of 4541914 rows
2018-11-28 02:54:47,569 [AsyncHBase I/O Worker #1] ERROR [CompactionQueue.call] - Failed to write a row to re-compact
org.hbase.async.RemoteException: java.nio.channels.ClosedChannelException
	at org.apache.hadoop.hdfs.DFSOutputStream.checkClosed(DFSOutputStream.java:1546)
	at org.apache.hadoop.hdfs.DFSOutputStream.flushOrSync(DFSOutputStream.java:1967)
	at org.apache.hadoop.hdfs.DFSOutputStream.hflush(DFSOutputStream.java:1912)
	at org.apache.hadoop.fs.FSDataOutputStream.hflush(FSDataOutputStream.java:141)
	at org.apache.hadoop.hbase.regionserver.wal.ProtobufLogWriter.sync(ProtobufLogWriter.java:171)
	at org.apache.hadoop.hbase.regionserver.wal.FSHLog$SyncRunner.run(FSHLog.java:1250)
	at java.lang.Thread.run(Thread.java:745)

	at org.hbase.async.RegionClient.makeException(RegionClient.java:1797) [asynchbase-1.8.2.jar:na]
	at org.hbase.async.RegionClient.decodeExceptionPair(RegionClient.java:1831) [asynchbase-1.8.2.jar:na]
	at org.hbase.async.MultiAction.deserialize(MultiAction.java:643) ~[asynchbase-1.8.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1504) [asynchbase-1.8.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.8.2.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230) [asynchbase-1.8.2.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3857) [asynchbase-1.8.2.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
2018-11-28 02:54:47,570 [AsyncHBase I/O Worker #1] ERROR [CompactionQueue.call] - Failed to write a row to re-compact
org.hbase.async.RemoteException: java.nio.channels.ClosedChannelException
	at org.apache.hadoop.hdfs.DFSOutputStream.checkClosed(DFSOutputStream.java:1546)
	at org.apache.hadoop.hdfs.DFSOutputStream.flushOrSync(DFSOutputStream.java:1967)
	at org.apache.hadoop.hdfs.DFSOutputStream.hflush(DFSOutputStream.java:1912)
	at org.apache.hadoop.fs.FSDataOutputStream.hflush(FSDataOutputStream.java:141)
	at org.apache.hadoop.hbase.regionserver.wal.ProtobufLogWriter.sync(ProtobufLogWriter.java:171)
	at org.apache.hadoop.hbase.regionserver.wal.FSHLog$SyncRunner.run(FSHLog.java:1250)
	at java.lang.Thread.run(Thread.java:745)

	at org.hbase.async.RegionClient.makeException(RegionClient.java:1797) [asynchbase-1.8.2.jar:na]
	at org.hbase.async.RegionClient.decodeExceptionPair(RegionClient.java:1831) [asynchbase-1.8.2.jar:na]
	at org.hbase.async.MultiAction.deserialize(MultiAction.java:643) ~[asynchbase-1.8.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1504) [asynchbase-1.8.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.8.2.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230) [asynchbase-1.8.2.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3857) [asynchbase-1.8.2.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
2018-11-28 02:57:37,766 [AsyncHBase I/O Worker #1] INFO  [HBaseClient.handleDisconnect] - Channel [id: 0x1537b5b0, /192.168.16.8:37606 => /192.168.17.223:16020] is disconnecting: [id: 0x1537b5b0, /192.168.16.8:37606 => /192.168.17.223:16020] DISCONNECT
2018-11-28 02:57:37,766 [AsyncHBase I/O Worker #1] INFO  [HBaseClient.removeClientFromCache] - Lost connection with the .META. region
2018-11-28 02:57:38,911 [AsyncHBase I/O Worker #2] INFO  [HBaseClient.handleDisconnect] - Channel [id: 0xc535912f, /192.168.16.8:46692 => /192.168.19.180:16020] is disconnecting: [id: 0xc535912f, /192.168.16.8:46692 => /192.168.19.180:16020] DISCONNECT
2018-11-28 02:57:38,915 [AsyncHBase I/O Worker #2] INFO  [TSDB.call] - Completed shutting down the TSDB
```

Excerpt from one of the HBase region servers:

```
2018-11-28 02:54:43,208 INFO  [MemStoreFlusher.0] regionserver.HRegion: Finished memstore flush of ~128.07 MB/134286952, currentsize=18.12 MB/
19000472 for region tsdb,\x02\x00\x00\x14,1543277826248.dad3ca25bf8830abc1e8b044b13cb0c7. in 3406ms, sequenceid=791605, compaction requested=t
rue
2018-11-28 02:54:44,356 INFO  [MemStoreFlusher.0] regionserver.HRegion: Flushing 1/1 column families, memstore=130.29 MB
2018-11-28 02:54:47,247 INFO  [MemStoreFlusher.1] regionserver.HRegion: Flushing 1/1 column families, memstore=128.30 MB
2018-11-28 02:54:47,520 ERROR [sync.1] wal.FSHLog: Error syncing, request close of WAL
java.nio.channels.ClosedChannelException
        at org.apache.hadoop.hdfs.DFSOutputStream.checkClosed(DFSOutputStream.java:1546)
        at org.apache.hadoop.hdfs.DFSOutputStream.flushOrSync(DFSOutputStream.java:1967)
        at org.apache.hadoop.hdfs.DFSOutputStream.hflush(DFSOutputStream.java:1912)
        at org.apache.hadoop.fs.FSDataOutputStream.hflush(FSDataOutputStream.java:141)
        at org.apache.hadoop.hbase.regionserver.wal.ProtobufLogWriter.sync(ProtobufLogWriter.java:171)
        at org.apache.hadoop.hbase.regionserver.wal.FSHLog$SyncRunner.run(FSHLog.java:1250)
        at java.lang.Thread.run(Thread.java:745)
2018-11-28 02:54:47,527 INFO  [regionserver/ip-192-168-17-223.us-west-1.compute.internal/192.168.17.223:16020.logRoller] wal.FSHLog: Rolled WAL /user/hbase/WALs/ip-192-168-17-223.us-west-1.compute.internal,16020,1542861336615/ip-192-168-17-223.us-west-1.compute.internal%2C16020%2C1542861336615.default.1543373677394 with entries=997, filesize=122.70 MB; new WAL /user/hbase/WALs/ip-192-168-17-223.us-west-1.compute.internal,16020,1542861336615/ip-192-168-17-223.us-west-1.compute.internal%2C16020%2C1542861336615.default.1543373687429
2018-11-28 02:54:47,551 INFO  [MemStoreFlusher.0] regionserver.DefaultStoreFlusher: Flushed, sequenceid=826827, memsize=130.3 M, hasBloomFilter=true, into tmp file hdfs://ip-192-168-18-77.us-west-1.compute.internal:8020/user/hbase/data/default/tsdb/b682471c89915bfdaa04e57a3f338d41/.tmp/88fe922fb5dd4312b5d2d7477095fc1a
```

There didn't appear to be anything interesting in the HBase master log around this time.

It wasn't obvious whether this is cause for concern, or whether there was any data loss.
However, a comment in the following thread suggests that the presence of the large stack trace indicates something unexpected:
https://groups.google.com/forum/#!topic/opentsdb/BkEH6bRoC5E

**Comment by manolama** [comment]
Yes this looks like it overloaded the DFS node on the region server, being unable to keep up. Thus the region server killed the TSD connection. The region server likely requires more tuning.

**Comment by twegener-embertec** [comment]
Ah, found the following open ticket re the need for adding rate limiting for bulk import:
#173 

Out of curiosity, do you have any ideas on why I hit a ClosedChannelException (org.hbase.async.RemoteException: java.nio.channels.ClosedChannelException) rather than org.hbase.async.PleaseThrottleException in my case?

**Comment by twegener-embertec** [comment]
Re:

> Out of curiosity, do you have any ideas on why I hit a ClosedChannelException (org.hbase.async.RemoteException: java.nio.channels.ClosedChannelException) rather than org.hbase.async.PleaseThrottleException in my case?

Could this be something to do with this happening in the part *after* the following:
```
2018-11-28 02:49:48,123 [main] INFO  [TextImporter.main] - Total: imported 203204537 data points in 908.733s (223612.9 points/s)
```

...where despite that message, there is some bulk import processing that still continues for some minutes afterwards, with the following coming up when it has finished that stage:

```
2018-12-16 04:49:57,467 [AsyncHBase I/O Worker #1] INFO  [HBaseClient.removeClientFromCache] - Lost connection with the .META. region
2018-12-16 04:49:57,472 [AsyncHBase I/O Worker #1] INFO  [TSDB.call] - Completed shutting down the TSDB
```

Is that aspect related to tsd.core.bulk.allow_out_of_order_timestamps being enabled?
