### ISSUE TITLE
Can't fsck with 2.4.0

### ISSUE THREAD

**Issue by johnseekins** [OpenTSDB/opentsdb#1463]
```
root@use1-hadoop-5:~# /usr/share/opentsdb/bin/tsdb fsck
Exception in thread "main" java.lang.IllegalArgumentException: Unknown option --sync
        at net.opentsdb.tools.ArgP.has(ArgP.java:213)
        at net.opentsdb.tools.FsckOptions.<init>(FsckOptions.java:57)
        at net.opentsdb.tools.Fsck.main(Fsck.java:1282)
```

This was an upgrade from 2.3.2 to 2.4.0.

**Comment by Raboo** [comment]
@manolama It's been over a year. Could you perhaps release a v2.4.1 with these type of minor bugfixes?

**Comment by hijklmno** [comment]
Likewise; @manolama can we cut a release soon?

**Comment by thanosz** [comment]
Same here! Is there at least a workaround?

**Comment by NikolaBorisov** [comment]
@manolama v2.4.1?

**Comment by nimitnagpal** [comment]
@manolama  @qudongfang Facing the same issue with 2.4.0. It would be great if we could release 2.4.1 with these fixes. 
Currently blocked on fixing data.
Is there a workaround?
