### ISSUE TITLE
Get BadRequestException When query rolluped data.

### ISSUE THREAD

**Issue by wch661** [OpenTSDB/opentsdb#1483]
version：2.4.0

When I use the feature of rollup, I came up with an exception.
Below is my query details and the exception information. Would you please review the problem and see if this is really an issue? Thanks.

Rollup config:
```json
{
      "aggregationIds": {
              "sum": 0,
              "count": 1,
              "min": 2,
              "max": 3,
              "median": 4,
              "zimsum": 5
      },
      "intervals": [{
              "table": "tsdb",
              "preAggregationTable": "tsdb-preagg",
              "interval": "1m",
              "rowSpan": "1h",
              "defaultInterval": true
      }, {
              "table": "tsdb-rollup-1h",
              "preAggregationTable": "tsdb-rollup-preagg-1h",
              "interval": "1h",
              "rowSpan": "1d"
      }]
}
```

Insert data:
```json
{
  "timestamp":"1546531200",
  "metric":"test",
  "tags":{
    "test":"20190104"
  },
  "value":1.0,
  "interval": "1m",
  "aggregator": "ZIMSUM"
}
```

Query Param:
```json
{
  "start":1546531200,
  "end": 1546531201,
  "queries":[
    {
      "aggregator":"zimsum",
      "metric":"test",
      "tags":{
        "test":"20190104"
      },
      "downsample": "1m-zimsum",
      "rollupUsage":"ROLLUP_NOFALLBACK"
    }
  ]
}
```

And return an error:
```json
{
"error":{
"code": 400,
"message": "Corrupted value: couldn't break down into individual values (consumed 8 bytes, but was expecting to consume 8): KeyValue(key=[0, 0, 4, 92, 46, 49, -128, 0, 0, 3, 0, 0, 7], family=\"t\", qualifier=[5, 0, 15], value=[63, -16, 0, 0, 0, 0, 0, 0], timestamp=1547100061970), cells so far: [Cell([0, 0], [0]), Cell([63, -16], [0])]",
"details": "Corrupted value: couldn't break down into individual values (consumed 8 bytes, but was expecting to consume 8): KeyValue(key=[0, 0, 4, 92, 46, 49, -128, 0, 0, 3, 0, 0, 7], family=\"t\", qualifier=[5, 0, 15], value=[63, -16, 0, 0, 0, 0, 0, 0], timestamp=1547100061970), cells so far: [Cell([0, 0], [0]), Cell([63, -16], [0])]",
"trace": "net.opentsdb.tsd.BadRequestException: Corrupted value: couldn't break down into individual values (consumed 8 bytes, but was expecting to consume 8): KeyValue(key=[0, 0, 4, 92, 46, 49, -128, 0, 0, 3, 0, 0, 7], family=\"t\", qualifier=[5, 0, 15], value=[63, -16, 0, 0, 0, 0, 0, 0], timestamp=1547100061970), cells so far: [Cell([0, 0], [0]), Cell([63, -16], [0])]\n\tat net.opentsdb.tsd.QueryRpc$1ErrorCB.call(QueryRpc.java:220) [tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.tsd.QueryRpc$1ErrorCB.call(QueryRpc.java:180) [tsdb-2.4.0.jar:14ab3ef]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.access$300(Deferred.java:430) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.DeferredGroup.access$200(DeferredGroup.java:36) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.DeferredGroup$1NotifyOrdered.call(DeferredGroup.java:97) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]\n\tat net.opentsdb.core.SaltScanner.mergeAndReturnResults(SaltScanner.java:300) [tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.SaltScanner.handleException(SaltScanner.java:970) [tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.SaltScanner.access$400(SaltScanner.java:68) [tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.SaltScanner$ScannerCB.processRow(SaltScanner.java:856) [tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:701) [tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:461) [tsdb-2.4.0.jar:14ab3ef]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1313) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1284) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]\n\tat org.hbase.async.HBaseRpc.callback(HBaseRpc.java:720) [asynchbase-1.8.2.jar:na]\n\tat org.hbase.async.RegionClient.decode(RegionClient.java:1575) [asynchbase-1.8.2.jar:na]\n\tat org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.8.2.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]\n\tat org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230) [asynchbase-1.8.2.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:na]\n\tat org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3857) [asynchbase-1.8.2.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:na]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]\n\tat java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]\nCaused by: net.opentsdb.core.IllegalDataException: Corrupted value: couldn't break down into individual values (consumed 8 bytes, but was expecting to consume 8): KeyValue(key=[0, 0, 4, 92, 46, 49, -128, 0, 0, 3, 0, 0, 7], family=\"t\", qualifier=[5, 0, 15], value=[63, -16, 0, 0, 0, 0, 0, 0], timestamp=1547100061970), cells so far: [Cell([0, 0], [0]), Cell([63, -16], [0])]\n\tat net.opentsdb.core.AppendDataPoints.parseKeyValue(AppendDataPoints.java:183) ~[tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.CompactionQueue$Compaction.buildHeapProcessAnnotations(CompactionQueue.java:456) ~[tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.CompactionQueue$Compaction.compact(CompactionQueue.java:349) ~[tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.CompactionQueue.compact(CompactionQueue.java:685) ~[tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.CompactionQueue.compact(CompactionQueue.java:256) ~[tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.TSDB.compact(TSDB.java:2153) ~[tsdb-2.4.0.jar:14ab3ef]\n\tat net.opentsdb.core.SaltScanner$ScannerCB.processRow(SaltScanner.java:836) [tsdb-2.4.0.jar:14ab3ef]\n\t... 39 common frames omitted\nCaused by: java.lang.ArrayIndexOutOfBoundsException: null\n\tat java.lang.System.arraycopy(Native Method) ~[na:1.8.0_171]\n\tat net.opentsdb.core.AppendDataPoints.parseKeyValue(AppendDataPoints.java:153) ~[tsdb-2.4.0.jar:14ab3ef]\n\t... 45 common frames omitted\n"
}
}
```

Error Log:
```
2019-01-10 14:03:12,462 ERROR [AsyncHBase I/O Worker #5] SaltScanner: After all of the scanners finished, at least one threw an exception
net.opentsdb.core.IllegalDataException: Corrupted value: couldn't break down into individual values (consumed 8 bytes, but was expecting to consume 8): KeyValue(key=[0, 0, 4, 92, 46, 49, -128, 0, 0, 3, 0, 0, 7], family="t", qualifier=[5, 0, 15], value=[63, -16, 0, 0, 0, 0, 0, 0], timestamp=1547100061970), cells so far: [Cell([0, 0], [0]), Cell([63, -16], [0])]
        at net.opentsdb.core.AppendDataPoints.parseKeyValue(AppendDataPoints.java:183) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue$Compaction.buildHeapProcessAnnotations(CompactionQueue.java:456) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue$Compaction.compact(CompactionQueue.java:349) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue.compact(CompactionQueue.java:685) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue.compact(CompactionQueue.java:256) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.TSDB.compact(TSDB.java:2153) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner$ScannerCB.processRow(SaltScanner.java:836) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:701) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:461) [tsdb-2.4.0.jar:14ab3ef]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1313) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1284) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:720) [asynchbase-1.8.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1575) [asynchbase-1.8.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.8.2.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230) [asynchbase-1.8.2.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:na]
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3857) [asynchbase-1.8.2.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_171]
        at net.opentsdb.core.AppendDataPoints.parseKeyValue(AppendDataPoints.java:153) ~[tsdb-2.4.0.jar:14ab3ef]
        ... 45 common frames omitted
019-01-10 14:03:12,463 ERROR [AsyncHBase I/O Worker #5] QueryRpc: Query exception:
com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
        at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169) [async-1.4.0.jar:na]
        at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158) [async-1.4.0.jar:na]
        at com.stumbleupon.async.DeferredGroup.access$200(DeferredGroup.java:36) [async-1.4.0.jar:na]
        at com.stumbleupon.async.DeferredGroup$1NotifyOrdered.call(DeferredGroup.java:97) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at net.opentsdb.core.SaltScanner.mergeAndReturnResults(SaltScanner.java:300) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner.handleException(SaltScanner.java:970) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner.access$400(SaltScanner.java:68) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner$ScannerCB.processRow(SaltScanner.java:856) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:701) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:461) [tsdb-2.4.0.jar:14ab3ef]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1313) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1284) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:720) [asynchbase-1.8.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1575) [asynchbase-1.8.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:88) [asynchbase-1.8.2.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230) [asynchbase-1.8.2.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:na]
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3857) [asynchbase-1.8.2.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: net.opentsdb.core.IllegalDataException: Corrupted value: couldn't break down into individual values (consumed 8 bytes, but was expecting to consume 8): KeyValue(key=[0, 0, 4, 92, 46, 49, -128, 0, 0, 3, 0, 0, 7], family="t", qualifier=[5, 0, 15], value=[63, -16, 0, 0, 0, 0, 0, 0], timestamp=1547100061970), cells so far: [Cell([0, 0], [0]), Cell([63, -16], [0])]
        at net.opentsdb.core.AppendDataPoints.parseKeyValue(AppendDataPoints.java:183) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue$Compaction.buildHeapProcessAnnotations(CompactionQueue.java:456) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue$Compaction.compact(CompactionQueue.java:349) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue.compact(CompactionQueue.java:685) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.CompactionQueue.compact(CompactionQueue.java:256) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.TSDB.compact(TSDB.java:2153) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.core.SaltScanner$ScannerCB.processRow(SaltScanner.java:836) [tsdb-2.4.0.jar:14ab3ef]
        ... 39 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_171]
        at net.opentsdb.core.AppendDataPoints.parseKeyValue(AppendDataPoints.java:153) ~[tsdb-2.4.0.jar:14ab3ef]
        ... 45 common frames omitted
```

Data In HBase:
```ROW                                                  COLUMN+CELL                                                                                                                                             
 \x00\x00\x04\x5C.1\x80\x00\x00\x03\x00\x00\x07      column=t:\x05\x00\x0F, timestamp=1547100061970, value=?\xF0\x00\x00\x00\x00\x00\x00                                                                     
1 row(s)
```

It seems that OpenTSDB thinks this is `append` data because of the prefix of `\x05` ？

**Comment by manolama** [comment]
Yeah that's odd. Could you paste your full TSD config as well please? And HBase version? Thanks!
