### ISSUE TITLE
AssertionError happend when SALT feature enabled

### ISSUE THREAD

**Issue by chenxu14** [OpenTSDB/opentsdb#1511]
_errors as below_
2019-01-29 20:08:11,501 ERROR [AsyncHBase I/O Worker #5] RegionClient: Unexpected exception from downstream on [id: 0x17cc2c63, /172.18.162.40:60534 => /10.20.117.56:16020]
java.lang.AssertionError: This Deferred was already called!  
New result={[B@5810ff00=Span(1 rows, [RowSeq([3, 0, 0, 1, 80, -30, 39, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 3] (metric=sys.cpu.user), base_time=1356998400 (Tue Jan 01 08:00:00 CST 2013)(datapoints=1), (qualifier=[[0, 0]]), (values=[[4]])]), [B@192df53b=Span(1 rows, [RowSeq([4, 0, 0, 1, 80, -30, 39, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2] (metric=sys.cpu.user), base_time=1356998400 (Tue Jan 01 08:00:00 CST 2013)(datapoints=1), (qualifier=[[0, 0]]), (values=[[1, 1]])]), [B@774937ef=Span(1 rows, [RowSeq([6, 0, 0, 1, 80, -30, 39, 0, 0, 0, 1, 0, 0, 4, 0, 0, 2, 0, 0, 3] (metric=sys.cpu.user), base_time=1356998400 (Tue Jan 01 08:00:00 CST 2013)(datapoints=1), (qualifier=[[0, 0]]), (values=[[1]])]), [B@28fe2ef9=Span(1 rows, [RowSeq([7, 0, 0, 1, 80, -30, 39, 0, 0, 0, 1, 0, 0, 4, 0, 0, 2, 0, 0, 2] (metric=sys.cpu.user), base_time=1356998400 (Tue Jan 01 08:00:00 CST 2013)(datapoints=1), (qualifier=[[0, 0]]), (values=[[2]])])}, this=Deferred@2030176884(state=DONE, result=[Lnet.opentsdb.core.SpanGroup;@f70b28c, callback=<none>, errback=<none>)
	at com.stumbleupon.async.Deferred.callback(Deferred.java:982) ~[async-1.4.0.jar:na]
	at net.opentsdb.core.SaltScanner.mergeAndReturnResults(SaltScanner.java:324) ~[classes/:na]
	at net.opentsdb.core.SaltScanner.validateAndTriggerCallback(SaltScanner.java:947) ~[classes/:na]
	at net.opentsdb.core.SaltScanner.access$18(SaltScanner.java:922) ~[classes/:na]
	at net.opentsdb.core.SaltScanner$ScannerCB.close(SaltScanner.java:910) ~[classes/:na]
	at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:539) ~[classes/:na]
	at net.opentsdb.core.SaltScanner$ScannerCB.call(SaltScanner.java:1) ~[classes/:na]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.access$300(Deferred.java:430) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na]
	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:720) ~[classes/:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1575) ~[classes/:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1) ~[classes/:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230) ~[classes/:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3857) [classes/:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by manolama** [comment]
That can happen if the query failed and a late result came in. Which version?

**Comment by chenxu14** [comment]
> That can happen if the query failed and a late result came in. Which version?

opentsdb version is 2.4.0
asynchbase version is 1.8.2

**Comment by symsimmy** [comment]
> That can happen if the query failed and a late result came in. Which version?

I met the same problem, is there a solution?

**Comment by manymango** [comment]
> That can happen if the query failed and a late result came in. Which version?
I met the same problem too, prone to happen when there are more requests，What is the reason for this?
