### ISSUE TITLE
Why I use hbase as storage instead of  cassandra

### ISSUE THREAD

**Issue by xujiesh0510** [OpenTSDB/opentsdb#1752]
opentsdb 2.3.2

opentsdb.conf

asynccassandra.seeds = 127.0.0.1:9160,127.0.0.1:9161,127.0.0.1:9162
tsd.storage.hbase.uid_table = tsdbuid
tsd.storage.hbase.data_table = tsdb

start error . seems opentsdb  AddHost 127.0.0.1 then RemoveHost 127.0.0.1

2019-08-23 09:47:03,887 INFO  [main] ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=MyConnectionPool,ServiceType=connectionpool
2019-08-23 09:47:03,893 INFO  [main] CountingConnectionPoolMonitor: AddHost: 127.0.0.1
2019-08-23 09:47:03,927 INFO  [main] CountingConnectionPoolMonitor: AddHost: 172.18.0.2
2019-08-23 09:47:03,927 INFO  [main] CountingConnectionPoolMonitor: RemoveHost: 127.0.0.1
2019-08-23 09:47:03,936 INFO  [main] CountingConnectionPoolMonitor: AddHost: 127.0.0.1
2019-08-23 09:47:03,941 INFO  [main] CountingConnectionPoolMonitor: AddHost: 172.18.0.2
2019-08-23 09:47:03,941 INFO  [main] CountingConnectionPoolMonitor: RemoveHost: 127.0.0.1
2019-08-23 09:47:03,951 INFO  [main] TSDB: Flushing compaction queue

Exception in thread "main" java.lang.RuntimeException: Initialization failed
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:237)
Caused by: com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
        at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169)
        at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:142)
        at com.stumbleupon.async.DeferredGroup.access$000(DeferredGroup.java:36)
        at com.stumbleupon.async.DeferredGroup$1Notify.call(DeferredGroup.java:82)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688)
        at com.stumbleupon.async.Deferred.addBoth(Deferred.java:772)
        at com.stumbleupon.async.DeferredGroup.<init>(DeferredGroup.java:119)
        at com.stumbleupon.async.Deferred.group(Deferred.java:897)
        at net.opentsdb.core.TSDB.checkNecessaryTablesExist(TSDB.java:593)
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:195)
Caused by: java.util.concurrent.ExecutionException: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.hbase.async.HBaseClient$1ResponseCB.run(HBaseClient.java:170)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by xujiesh0510** [comment]
i struggled to make opentsdb work. 
you will need Java Runtime Environment 1.6 or later
GnuPlot 4.2 or later(optional  )

Opentsdb 2.3.2
Cassandra  https://hub.docker.com/_/cassandra/  latest

follow  https://github.com/OpenTSDB/opentsdb/issues/920 

Cassandra:
cassandra.yaml  config partitioner  ByteOrderedPartitioner 
sudo docker run --name cassandram          -e CASSANDRA_START_RPC=true -v /home/test1/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml  -p  192.168.100.41:9160:9160 -p 192.168.100.41:9042:9042  -d cassandra 

OpenTsdb
download opentsdb2.3.2 ,unzip file.
sh  build-cassandra.sh


here is the  missing part:

seems  asynccassandra project have  bugs when use the latest cassandra.
first Modify HBaseClient.java: 
      fix missing import error, 
      go to line somewhere aroud 126 , find the code :

 ast_config = new AstyanaxConfigurationImpl()      
      .setDiscoveryType(NodeDiscoveryType.RING_DESCRIBE);
 
 modify NodeDiscoveryType.RING_DESCRIBE to  NodeDiscoveryType.NONE

if you  use maven3.x , there will be building errors, fix that( if you are a  java developer ,it won't  be  a tough work)
by the way , i  update the  

  <dependency>
            <groupId>com.netflix.astyanax</groupId>
            <artifactId>astyanax-cassandra</artifactId>
            <version>3.10.2</version>
        </dependency>

        <dependency>
            <groupId>com.netflix.astyanax</groupId>
            <artifactId>astyanax-thrift</artifactId>
            <version>3.10.2</version>
        </dependency>

        <dependency>
            <groupId>com.netflix.astyanax</groupId>
            <artifactId>astyanax-recipes</artifactId>
            <version>3.10.2</version>
        </dependency>


part 

After  building the project , jar file size  is about 25-30MB. Rename jar  to  asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar
move  it  to  /build/third_party/asynccassandra  replace the old jar file

Now start opentsdb , it works !

**Comment by xujiesh0510** [comment]
another big problem!!  use http api  insert  fucking too slow..... most of the time  opentsdb is creating uid for metric and tag ....

**Comment by xujiesh0510** [comment]
If you use cassandra ,  some configuration items will not work.

such as 
tsd.storage.enable_appends=true // if enabled, data will not be written into cassandra.

**Comment by xujiesh0510** [comment]
After two days test,  here is the final result:

Env:
opentsdb 3.2.3  4c 8g , jvm 5.5G
cassandra Cluster  3 nodes, 2c 8g

 opentsdb  allows 5000  insert  per/second.
  hit  opentsdb   with 10000 per/second insert  ,  it use all the cpu resource. jvm gc threads is
working hard to gc.

so my guess is i need to increase cassandra writes per/second.
but  opentsdb with hive in a single docker container  can hold 10000 insert  per/second.

I have to  give up cassandra

**Comment by deamerfire** [comment]
Can use jdk1.8 to compile opentsdb 2.4 normally

**Comment by xujiesh0510** [comment]
UPDATE:  TdEngine and Apache Iotdb are definitely good alternatives  to replace opentsdb. 
https://github.com/taosdata/TDengine
https://github.com/apache/incubator-iotdb

**Comment by deamerfire** [comment]
I am also talking about these two time series databases . TDengine is really good and I am waiting for its cluster version to be open source.
