### ISSUE TITLE
Setting "tsd.rollups.enable = true" causes opentsdb to hang

### ISSUE THREAD

**Issue by eangelou** [OpenTSDB/opentsdb#1776]
Hello,

Tried to enable rollups, but whenever I try to change tsd.rollups.enable to true, opentsdb seems to hang (installed from .deb pkg, not sure if that is relevant):
```08:40:23.107 INFO  [TSDB.call] - Completed shutting down the TSDB
08:40:24.812 INFO  [TSDMain.main] - Starting.
08:40:24.816 INFO  [TSDMain.main] - net.opentsdb.tools 2.4.0 built at revision 14ab3ef (MINT)
08:40:24.816 INFO  [TSDMain.main] - Built on 2018/12/17 02:40:15 +0000 by hobbes@clhbase:/home/hobbes/OFFICIAL/build
08:40:24.823 DEBUG [Config.loadConfig] - Unable to find or load opentsdb.conf
java.io.FileNotFoundException: opentsdb.conf (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_45]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_45]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_45]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_45]
        at net.opentsdb.utils.Config.loadConfig(Config.java:668) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.utils.Config.<init>(Config.java:153) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tools.CliOptions.getConfig(CliOptions.java:101) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:114) [tsdb-2.4.0.jar:14ab3ef]
08:40:24.824 DEBUG [Config.loadConfig] - Unable to find or load /etc/opentsdb.conf
java.io.FileNotFoundException: /etc/opentsdb.conf (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_45]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_45]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_45]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_45]
        at net.opentsdb.utils.Config.loadConfig(Config.java:668) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.utils.Config.<init>(Config.java:153) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tools.CliOptions.getConfig(CliOptions.java:101) [tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:114) [tsdb-2.4.0.jar:14ab3ef]
08:40:24.824 INFO  [Config.loadConfig] - Successfully loaded configuration file: /etc/opentsdb/opentsdb.conf
08:40:24.834 DEBUG [SelectorUtil.debug] - Using select timeout of 500
08:40:24.835 DEBUG [SelectorUtil.debug] - Epoll-bug workaround enabled = false
08:40:24.860 INFO  [Config.loadConfig] - Successfully loaded configuration file: /etc/opentsdb/opentsdb.conf
```

It will then stay there forever...
Setting tsd.rollups.enable = false and restarting seems to fix it, but I would like to enable rollups... eventually :)
Thanks!

**Comment by eangelou** [comment]
Hello again,

Just to answer my own question, it seems that the rowSpan value in rollups json only accepts 'h' as time modifier. Trying with:
```
{
      "aggregationIds": {
              "sum": 0,
              "count": 1,
              "min": 2,
              "max": 3
      },
      "intervals": [{
              "table": "tsdb",
              "preAggregationTable": "tsdb-preagg",
              "interval": "1m",
              "rowSpan": "1h",
              "defaultInterval": true
      }, {
              "table": "tsdb-rollup-1h",
              "preAggregationTable": "tsdb-rollup-preagg-1h",
              "interval": "1h",
              "rowSpan": "1d"
      }, {
              "table": "tsdb-rollup-1d",
              "preAggregationTable": "tsdb-rollup-preagg-1d",
              "interval": "1d",
              "rowSpan": "30d"
      }]
}
```

will produce the exception:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `net.opentsdb.rollup.RollupInterval$Builder`, problem: Multipliers are only usable with the 'h' unit
 at [Source: (String)"{
      "aggregationIds": {
              "sum": 0,
              "count": 1,
              "min": 2,
              "max": 3
      },
      "intervals": [{
              "table": "tsdb",
              "preAggregationTable": "tsdb-preagg",
              "interval": "1m",
              "rowSpan": "1h",
              "defaultInterval": true
      }, {
              "table": "tsdb-rollup-1h",
              "preAggregationTable": "tsdb-rollup-preagg-1h",
              "interval": "1h",
              "[truncated 204 chars]; line: 24, column: 7] (through reference chain: net.opentsdb.rollup.RollupConfig$Builder["intervals"]->java.util.ArrayList[2])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1601)
        at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1072)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapInstantiationProblem(BeanDeserializerBase.java:1747)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.finishBuild(BuilderBasedDeserializer.java:178)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeSetAndReturn(FieldProperty.java:158)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
        at net.opentsdb.utils.JSON.parseToObject(JSON.java:108)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Multipliers are only usable with the 'h' unit
        at net.opentsdb.rollup.RollupInterval.validateAndCompile(RollupInterval.java:182)
        at net.opentsdb.rollup.RollupInterval.<init>(RollupInterval.java:104)
        at net.opentsdb.rollup.RollupInterval$Builder.build(RollupInterval.java:351)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.finishBuild(BuilderBasedDeserializer.java:176)
        ... 13 more
```

Not really sure of ot os a jackson parsing or opentsdb bug so closing the issue. Changing to rowSpan hours seems to work fine.

Thanks
