### ISSUE TITLE
When I use Openstdb 3.0 to connect to HBase, I encounter the following error. Can someone help me?

### ISSUE THREAD

**Issue by deamerfire** [OpenTSDB/opentsdb#1925]
14:17:51.989 ERROR [RegionClient.exceptionCaught] - Unexpected exception from downstream on [id: 0xd14f4e01, /10.142.58.8:36644 => /10.132.31.3:54800]
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
14:17:51.989 INFO  [HBaseClient.handleDisconnect] - Channel [id: 0xd14f4e01, /10.142.58.8:36644 => /10.132.31.3:54800] is disconnecting: [id: 0xd14f4e01, /10.142.58.8:36644 => /10.132.31.3:54800] CLOSE
14:17:51.989 INFO  [HBaseClient.removeClientFromCache] - Lost connection with the .META. region
14:17:51.989 INFO  [ZooKeeper.close] - Session: 0x170aeaeb8ee4790 closed
14:17:51.990 INFO  [ClientCnxn.run] - EventThread shut down
14:17:51.990 INFO  [HBaseClient.getIP] - Resolved IP address for host: c4-hadoop-tst-st96.bj is: 10.132.31.3
14:17:51.990 INFO  [HBaseClient.invalidateRegionCache] - Invalidated cache for .META. as null still seems to be splitting or closing it.
14:17:51.990 INFO  [HBaseClient.handleMetaZnode] - Connecting to .META. region @ 10.132.31.3:54800
14:17:51.990 INFO  [ClientCnxn.run] - EventThread shut down
14:17:51.993 INFO  [HBaseClient.handleDisconnect] - Channel [id: 0xc6173041, /10.142.58.8:36648 :> /10.132.31.3:54800] is disconnecting: [id: 0xc6173041, /10.142.58.8:36648 :> /10.132.31.3:54800] DISCONNECTED
14:17:51.993 INFO  [HBaseClient.removeClientFromCache] - Lost connection with the .META. region
14:17:53.883 INFO  [AccessLog.logMessage] - 10.38.11.138 - - [11/Mar/2020:14:17:53 +0800] "GET / HTTP/1.1" 404 73 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.3 skyeye-scanner"
14:17:54.014 INFO  [ZooKeeper.<init>] - Initiating client connection, connectString=c4tst.zk.hadoop.srv:11000 sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@5171236f

**Comment by deamerfire** [comment]
HBase version：2.2.0

**Comment by momo898821** [comment]
I also have this problem. It seems like Hbase is bussy with compacting or spliting with WAL file, then closed the connection by Hbase
![image](https://user-images.githubusercontent.com/14818687/85012713-024c7f80-b196-11ea-9a5b-47caf832d10b.png)

**Comment by manolama** [comment]
Does it reconnect automatically on the next query? It should. And we'll have to find out why HBase closes the connection.
