### ISSUE TITLE
java.lang.NullPointerException: null(opentsdb-2.4.0-1.noarch)

### ISSUE THREAD

**Issue by vadirajks** [OpenTSDB/opentsdb#1938]
i am unable see any graph on the UI, but able to fetch data using api call through curl command.
throws below exception when i am trying to plot graph in UI:
15:02:51.830 INFO  [HttpQuery.logInfo] - [id: 0xb3b3855d, /192.168.125.155:49368 => /10.250.14.40:4242] HTTP /suggest?type=metrics&q=proc.loadavg.5m done in 2ms
15:02:54.613 INFO  [Plot.writeGnuplotScript] - Wrote Gnuplot script to /tmp/opentsdb/864e4629.gnuplot
15:02:54.613 ERROR [HttpQuery.logError] - [id: 0xb3b3855d, /192.168.125.155:49368 => /10.250.14.40:4242] Internal Server Error on /q?start=2020/04/18-00:00:00&end=2020/04/18-20:32:05&m=sum:proc.loadavg.5m&o=&yrange=%5B0:%5D&wxh=1346x494&style=linespoint&json
java.lang.NullPointerException: null
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012) ~[na:1.8.0_112]
	at net.opentsdb.tsd.GraphHandler.runGnuplot(GraphHandler.java:785) ~[tsdb-2.4.0.jar:]
	at net.opentsdb.tsd.GraphHandler$RunGnuplot.execute(GraphHandler.java:353) ~[tsdb-2.4.0.jar:]
	at net.opentsdb.tsd.GraphHandler$RunGnuplot.run(GraphHandler.java:340) ~[tsdb-2.4.0.jar:]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
15:02:54.615 INFO  [HttpQuery.logInfo] - [id: 0xb3b3855d, /192.168.125.155:49368 => /10.250.14.40:4242] HTTP /q?start=2020/04/18-00:00:00&end=2020/04/18-20:32:05&m=sum:proc.loadavg.5m&o=&yrange=%5B0:%5D&wxh=1346x494&style=linespoint&json done in 20ms
15:07:11.592 INFO  [ConnectionManager.handleUpstream] - [id: 0x64c39b40, /192.168.125.155:49362 :> /10.250.14.40:4242] DISCONNECTED
15:07:11.592 INFO  [ConnectionManager.handleUpstream] - [id: 0x64c39b40, /192.168.125.155:49362 :> /10.250.14.40:4242] UNBOUND
15:07:11.593 INFO  [ConnectionManager.handleUpstream] - [id: 0x64c39b40, /192.168.125.155:49362 :> /10.250.14.40:4242] CLOSED
15:07:11.592 INFO  [ConnectionManager.handleUpstream] - [id: 0x2c47d622, /192.168.125.155:49358 :> /10.250.14.40:4242] DISCONNECTED
15:07:11.593 INFO  [ConnectionManager.handleUpstream] - [id: 0x800999e0, /192.168.125.155:49360 :> /10.250.14.40:4242] DISCONNECTED
15:07:11.594 INFO  [ConnectionManager.handleUpstream] - [id: 0x2c47d622, /192.168.125.155:49358 :> /10.250.14.40:4242] UNBOUND
15:07:11.594 INFO  [ConnectionManager.handleUpstream] - [id: 0x800999e0, /192.168.125.155:49360 :> /10.250.14.40:4242] UNBOUND
15:07:11.594 INFO  [ConnectionManager.handleUpstream] - [id: 0x800999e0, /192.168.125.155:49360 :> /10.250.14.40:4242] CLOSED
15:07:11.594 INFO  [ConnectionManager.handleUpstream] - [id: 0x2c47d622, /192.168.125.155:49358 :> /10.250.14.40:4242] CLOSED
15:07:51.834 INFO  [HBaseClient.channelIdle] - Closing idle connection to HBase region server: [id: 0xeb00d56d, /10.250.14.40:41008 => /10.250.14.41:16020]
15:07:51.835 INFO  [HBaseClient.handleDisconnect] - Channel [id: 0xeb00d56d, /10.250.14.40:41008 => /10.250.14.41:16020] is disconnecting: [id: 0xeb00d56d, /10.250.14.40:41008 => /10.250.14.41:16020] CLOSE
15:07:51.835 INFO  [HBaseClient.removeClientFromCache] - Lost connection with the .META. region
15:07:56.373 INFO  [HBaseClient.channelIdle] - Closing idle connection to HBase region server: [id: 0x0f6537d5, /10.250.14.40:50830 => /10.250.14.40:16020]
15:07:56.373 INFO  [HBaseClient.handleDisconnect] - Channel [id: 0x0f6537d5, /10.250.14.40:50830 => /10.250.14.40:16020] is disconnecting: [id: 0x0f6537d5, /10.250.14.40:50830 => /10.250.14.40:16020] CLOSE
15:07:59.444 INFO  [ConnectionManager.handleUpstream] - [id: 0xb3b3855d, /192.168.125.155:49368 :> /10.250.14.40:4242] DISCONNECTED
15:07:59.444 INFO  [ConnectionManager.handleUpstream] - [id: 0xb3b3855d, /192.168.125.155:49368 :> /10.250.14.40:4242] UNBOUND
15:07:59.444 INFO  [ConnectionManager.handleUpstream] - [id: 0xb3b3855d, /192.168.125.155:49368 :> /10.250.14.40:4242] CLOSED

[root@hdp40-10 ~]# rpm -qa | grep plot -i
gnuplot-common-4.6.2-3.amzn2.0.2.x86_64
gnuplot-minimal-4.6.2-3.amzn2.0.2.x86_64
texlive-pst-plot-svn28729.1.44-38.amzn2.0.4.noarch
gnuplot-latex-4.6.2-3.amzn2.0.2.noarch
gnuplot-doc-4.6.2-3.amzn2.0.2.noarch
gnuplot-4.6.2-3.amzn2.0.2.x86_64

[root@hdp40-10 ~]# rpm -qa | grep opentsdb  -i
opentsdb-2.4.0-1.noarch

i see file are getting created here and i guess there is no problem with this.
[root@hdp40-10 ~]# ls /tmp/opentsdb/ -ltrh
-rw-r--r-- 1 opentsdb opentsdb  413 Apr 18 14:40 dbd2b07b.gnuplot
-rw-r--r-- 1 opentsdb opentsdb 9.9K Apr 18 14:40 dbd2b07b_0.dat
-rw-r--r-- 1 opentsdb opentsdb  18K Apr 18 14:40 a0252a17_0.dat
-rw-r--r-- 1 opentsdb opentsdb  413 Apr 18 14:40 a0252a17.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  314 Apr 18 14:43 c22a46ab.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  314 Apr 18 14:45 72ce4b31.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:49 ac3c90b1.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  462 Apr 18 14:49 ac3c90b1_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:49 ac2e8fc3.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  462 Apr 18 14:49 ac2e8fc3_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:49 7f4cdd06.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  462 Apr 18 14:49 7f4cdd06_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:49 9e488c07.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  462 Apr 18 14:49 9e488c07_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:50 8a7efcea.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  462 Apr 18 14:50 8a7efcea_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:50 3c9514ff.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  462 Apr 18 14:50 3c9514ff_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:55 36d6808a.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  462 Apr 18 14:55 36d6808a_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 14:55 86437c36.gnuplot
-rw-r--r-- 1 opentsdb opentsdb 9.9K Apr 18 14:55 86437c36_0.dat
-rw-r--r-- 1 opentsdb opentsdb 9.9K Apr 18 15:02 864e45a5_0.dat
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 15:02 864e45a5.gnuplot
-rw-r--r-- 1 opentsdb opentsdb  410 Apr 18 15:02 864e4629.gnuplot
-rw-r--r-- 1 opentsdb opentsdb 9.9K Apr 18 15:02 864e4629_0.dat

As i am new to time series database and not good at java. Please anyone help me to fix this.
Thanks

**Comment by manolama** [comment]
Could be a gnuplot incompatibility. Check your TSD logs for something like `Using Gnuplot wrapper` and see if it found the gnuplot wrapper.
