### ISSUE TITLE
opentsdb start failed

### ISSUE THREAD

**Issue by ywww** [OpenTSDB/opentsdb#1987]
2020-07-22 14:49:50,212 INFO  [main] TSDMain: Starting.
2020-07-22 14:49:50,216 INFO  [main] TSDMain: net.opentsdb.tools 2.4.0 built at revision  (MODIFIED)
2020-07-22 14:49:50,216 INFO  [main] TSDMain: Built on 2019/05/17 09:37:38 +0000 by root@a013112:/root/opentsdb-2.4.0
2020-07-22 14:49:50,219 INFO  [main] Config: Successfully loaded configuration file: /usr/local/complat/opentsdb/etc/opentsdb/opentsdb.conf
2020-07-22 14:49:50,255 INFO  [main] Config: Successfully loaded configuration file: /usr/local/complat/opentsdb/etc/opentsdb/opentsdb.conf
2020-07-22 14:49:50,372 WARN  [main] PluginLoader: Unable to locate any plugins of the type: net.opentsdb.query.filter.TagVFilter
2020-07-22 14:49:50,392 INFO  [main] ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2020-07-22 14:49:50,392 INFO  [main] ZooKeeper: Client environment:host.name=a013112
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:java.version=1.8.0_181
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:java.vendor=Oracle Corporation
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:java.home=/usr/java/jdk1.8.0_181-amd64/jre
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:java.class.path=/usr/local/complat/opentsdb/*.jar:/usr/local/complat/opentsdb:/usr/local/complat/opentsdb/bin:/usr/local/complat/opentsdb/lib/asm-4.0.jar:/usr/local/complat/opentsdb/lib/async-1.4.0.jar:/usr/local/complat/opentsdb/lib/asynchbase-1.8.2.jar:/usr/local/complat/opentsdb/lib/commons-jexl-2.1.1.jar:/usr/local/complat/opentsdb/lib/commons-logging-1.1.1.jar:/usr/local/complat/opentsdb/lib/commons-math3-3.4.1.jar:/usr/local/complat/opentsdb/lib/guava-18.0.jar:/usr/local/complat/opentsdb/lib/jackson-annotations-2.9.5.jar:/usr/local/complat/opentsdb/lib/jackson-core-2.9.5.jar:/usr/local/complat/opentsdb/lib/jackson-databind-2.9.5.jar:/usr/local/complat/opentsdb/lib/javacc-6.1.2.jar:/usr/local/complat/opentsdb/lib/jgrapht-core-0.9.1.jar:/usr/local/complat/opentsdb/lib/kryo-2.21.1.jar:/usr/local/complat/opentsdb/lib/log4j-over-slf4j-1.7.7.jar:/usr/local/complat/opentsdb/lib/logback-classic-1.0.13.jar:/usr/local/complat/opentsdb/lib/logback-core-1.0.13.jar:/usr/local/complat/opentsdb/lib/minlog-1.2.jar:/usr/local/complat/opentsdb/lib/netty-3.10.6.Final.jar:/usr/local/complat/opentsdb/lib/protobuf-java-2.5.0.jar:/usr/local/complat/opentsdb/lib/reflectasm-1.07-shaded.jar:/usr/local/complat/opentsdb/lib/slf4j-api-1.7.7.jar:/usr/local/complat/opentsdb/lib/tsdb-2.4.0.jar:/usr/local/complat/opentsdb/lib/zookeeper-3.4.6.jar:/usr/local/complat/opentsdb/etc/opentsdb
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:java.library.path=/opt/cloudera/parcels/CDH/lib/hadoop/lib/native/::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:java.io.tmpdir=/tmp
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:java.compiler=<NA>
2020-07-22 14:49:50,393 INFO  [main] ZooKeeper: Client environment:os.name=Linux
2020-07-22 14:49:50,394 INFO  [main] ZooKeeper: Client environment:os.arch=amd64
2020-07-22 14:49:50,394 INFO  [main] ZooKeeper: Client environment:os.version=3.10.0-957.1.3.el7.x86_64
2020-07-22 14:49:50,394 INFO  [main] ZooKeeper: Client environment:user.name=root
2020-07-22 14:49:50,394 INFO  [main] ZooKeeper: Client environment:user.home=/root
2020-07-22 14:49:50,394 INFO  [main] ZooKeeper: Client environment:user.dir=/usr/local/complat/opentsdb/etc/opentsdb
2020-07-22 14:49:50,395 INFO  [main] ZooKeeper: Initiating client connection, connectString=zookeeper2.xdap.com:2181,zookeeper3.xdap.com:2181,zookeeper1.xdap.com:2181 sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@4d3167f4
2020-07-22 14:49:50,414 INFO  [main] HBaseClient: Need to find the -ROOT- region
2020-07-22 14:49:50,705 INFO  [main-SendThread(a010264:2181)] Login: successfully logged in.
2020-07-22 14:49:50,707 INFO  [Thread-1] Login: TGT refresh thread started.
2020-07-22 14:49:50,710 INFO  [main-SendThread(a010264:2181)] ZooKeeperSaslClient: Client will use GSSAPI as SASL mechanism.
2020-07-22 14:49:50,717 INFO  [Thread-1] Login: TGT valid starting at:        Wed Jul 22 14:49:50 CST 2020
2020-07-22 14:49:50,717 INFO  [Thread-1] Login: TGT expires:                  Thu Jul 23 14:49:50 CST 2020
2020-07-22 14:49:50,717 INFO  [Thread-1] Login: TGT refresh sleeping until: Thu Jul 23 10:28:42 CST 2020
2020-07-22 14:49:50,719 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Opening socket connection to server a010264/10.12.5.216:2181. Will attempt to SASL-authenticate using Login Context section 'Client'
2020-07-22 14:49:50,726 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Socket connection established to a010264/10.12.5.216:2181, initiating session
2020-07-22 14:49:50,733 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Session establishment complete on server a010264/10.12.5.216:2181, sessionid = 0x36b26946acff064, negotiated timeout = 12000
2020-07-22 14:49:50,763 INFO  [main-EventThread] ZooKeeper: Session: 0x36b26946acff064 closed
2020-07-22 14:49:50,764 WARN  [main-EventThread] HBaseClient: No longer connected to ZooKeeper, event=WatchedEvent state:SaslAuthenticated type:None path:null
2020-07-22 14:49:50,764 INFO  [main-EventThread] ZooKeeper: Initiating client connection, connectString=zookeeper2.xdap.com:2181,zookeeper3.xdap.com:2181,zookeeper1.xdap.com:2181 sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@4d3167f4
2020-07-22 14:49:50,770 INFO  [main-SendThread(a010263:2181)] ZooKeeperSaslClient: Client will use GSSAPI as SASL mechanism.
2020-07-22 14:49:50,772 INFO  [main-SendThread(a010263:2181)] ClientCnxn: Opening socket connection to server a010263/10.12.5.215:2181. Will attempt to SASL-authenticate using Login Context section 'Client'
2020-07-22 14:49:50,775 INFO  [main-SendThread(a010263:2181)] ClientCnxn: Socket connection established to a010263/10.12.5.215:2181, initiating session
2020-07-22 14:49:50,778 INFO  [main-SendThread(a010263:2181)] ClientCnxn: Session establishment complete on server a010263/10.12.5.215:2181, sessionid = 0x26b26946cbf029f, negotiated timeout = 12000
2020-07-22 14:49:50,783 INFO  [main-EventThread] HBaseClient: Resolved IP address for host: a011951 is: 10.12.8.230
2020-07-22 14:49:50,783 INFO  [main-EventThread] HBaseClient: Connecting to .META. region @ 10.12.8.230:60020
2020-07-22 14:49:50,796 INFO  [main-EventThread] ZooKeeper: Session: 0x26b26946cbf029f closed
2020-07-22 14:49:50,796 WARN  [main-EventThread] HBaseClient: No longer connected to ZooKeeper, event=WatchedEvent state:SaslAuthenticated type:None path:null
2020-07-22 14:49:50,796 INFO  [main-EventThread] ZooKeeper: Initiating client connection, connectString=zookeeper2.xdap.com:2181,zookeeper3.xdap.com:2181,zookeeper1.xdap.com:2181 sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@4d3167f4
2020-07-22 14:49:50,798 INFO  [main-EventThread] HBaseClient: Resolved IP address for host: a011951 is: 10.12.8.230
2020-07-22 14:49:50,798 INFO  [main-EventThread] HBaseClient: Connecting to .META. region @ 10.12.8.230:60020
2020-07-22 14:49:50,800 INFO  [main-SendThread(a010264:2181)] ZooKeeperSaslClient: Client will use GSSAPI as SASL mechanism.
2020-07-22 14:49:50,801 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Opening socket connection to server a010264/10.12.5.216:2181. Will attempt to SASL-authenticate using Login Context section 'Client'
2020-07-22 14:49:50,803 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Socket connection established to a010264/10.12.5.216:2181, initiating session
2020-07-22 14:49:50,806 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Session establishment complete on server a010264/10.12.5.216:2181, sessionid = 0x36b26946acff065, negotiated timeout = 12000
2020-07-22 14:49:50,816 INFO  [main-EventThread] ZooKeeper: Session: 0x36b26946acff065 closed
2020-07-22 14:49:50,816 WARN  [main-EventThread] HBaseClient: No longer connected to ZooKeeper, event=WatchedEvent state:SaslAuthenticated type:None path:null
2020-07-22 14:49:50,817 INFO  [main-EventThread] ZooKeeper: Initiating client connection, connectString=zookeeper2.xdap.com:2181,zookeeper3.xdap.com:2181,zookeeper1.xdap.com:2181 sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@4d3167f4
2020-07-22 14:49:50,818 INFO  [main-EventThread] HBaseClient: Resolved IP address for host: a011951 is: 10.12.8.230
2020-07-22 14:49:50,818 INFO  [main-EventThread] HBaseClient: Connecting to .META. region @ 10.12.8.230:60020
2020-07-22 14:49:50,820 INFO  [main-SendThread(a010264:2181)] ZooKeeperSaslClient: Client will use GSSAPI as SASL mechanism.
2020-07-22 14:49:50,821 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Opening socket connection to server a010264/10.12.5.216:2181. Will attempt to SASL-authenticate using Login Context section 'Client'
2020-07-22 14:49:50,823 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Socket connection established to a010264/10.12.5.216:2181, initiating session
2020-07-22 14:49:50,826 INFO  [main-SendThread(a010264:2181)] ClientCnxn: Session establishment complete on server a010264/10.12.5.216:2181, sessionid = 0x36b26946acff066, negotiated timeout = 12000
2020-07-22 14:49:50,835 INFO  [main-EventThread] ZooKeeper: Session: 0x36b26946acff066 closed
2020-07-22 14:49:50,835 INFO  [main-EventThread] ClientCnxn: EventThread shut down
2020-07-22 14:49:50,836 INFO  [main-EventThread] ClientCnxn: EventThread shut down
2020-07-22 14:49:50,836 INFO  [AsyncHBase I/O Worker #1] Login: Successfully logged in.
2020-07-22 14:49:50,836 INFO  [main-EventThread] ClientCnxn: EventThread shut down
2020-07-22 14:49:50,836 INFO  [main-EventThread] ClientCnxn: EventThread shut down
2020-07-22 14:49:50,838 INFO  [AsyncHBase I/O Worker #1] Login: TGT valid starting at:        Wed Jul 22 14:49:50 CST 2020
2020-07-22 14:49:50,839 INFO  [AsyncHBase I/O Worker #1] Login: TGT expires:                  Thu Jul 23 14:49:50 CST 2020
2020-07-22 14:49:50,839 INFO  [AsyncHBase I/O Worker #1] Login: Scheduled ticket renewal in 69750945 ms
2020-07-22 14:49:50,840 INFO  [AsyncHBase I/O Worker #1] Login: Initialized kerberos login context
2020-07-22 14:49:50,842 INFO  [AsyncHBase I/O Worker #1] KerberosClientAuthProvider: Connecting to hbase/a011951@xdap.com
2020-07-22 14:49:50,843 INFO  [AsyncHBase I/O Worker #1] KerberosClientAuthProvider: Client will use GSSAPI as SASL mechanism.
2020-07-22 14:49:50,863 INFO  [AsyncHBase I/O Worker #1] RegionClient: Initialized security helper: org.hbase.async.SecureRpcHelper96@2c923466 for region client: RegionClient@1024436422(chan=null, #pending_rpcs=3, #batched=0, #rpcs_inflight=0)
2020-07-22 14:49:50,869 INFO  [AsyncHBase I/O Worker #1] SecureRpcHelper96: SASL client context established. Negotiated QoP: auth on for: RegionClient@1024436422(chan=null, #pending_rpcs=3, #batched=0, #rpcs_inflight=0)
2020-07-22 14:49:50,896 INFO  [AsyncHBase I/O Worker #1] HBaseClient: Resolved IP address for host: a011953 is: 10.12.8.232
2020-07-22 14:49:50,898 INFO  [AsyncHBase I/O Worker #1] HBaseClient: Added client for region RegionInfo(table="tsdb", region_name="tsdb:tsdb,,1586835589827.e2b8c8222dcb7276757c9e4827504dbc.", stop_key="\x00\x00/]E\xCC"), which was added to the regions cache.  Now we know that RegionClient@1751490247(chan=null, #pending_rpcs=0, #batched=0, #rpcs_inflight=0) is hosting 1 region.
2020-07-22 14:49:50,899 INFO  [AsyncHBase I/O Worker #1] HBaseClient: Resolved IP address for host: a011953 is: 10.12.8.232
2020-07-22 14:49:50,899 INFO  [AsyncHBase I/O Worker #1] HBaseClient: Added client for region RegionInfo(table="tsdb-uid", region_name="tsdb:tsdb-uid,,1527499738510.893bec7438b61ceb0291de0e3b271922.", stop_key=""), which was added to the regions cache.  Now we know that RegionClient@1751490247(chan=null, #pending_rpcs=1, #batched=0, #rpcs_inflight=0) is hosting 2 regions.
2020-07-22 14:49:50,900 INFO  [AsyncHBase I/O Worker #2] KerberosClientAuthProvider: Connecting to hbase/a011953@xdap.com
2020-07-22 14:49:50,901 INFO  [AsyncHBase I/O Worker #2] KerberosClientAuthProvider: Client will use GSSAPI as SASL mechanism.
2020-07-22 14:49:50,901 INFO  [AsyncHBase I/O Worker #1] HBaseClient: Resolved IP address for host: a011587 is: 10.12.4.118
2020-07-22 14:49:50,902 INFO  [AsyncHBase I/O Worker #1] HBaseClient: Added client for region RegionInfo(table="tsdb-meta", region_name="tsdb:tsdb-meta,,1527499739871.957ed780569f6f07208a032b66aa6e17.", stop_key=""), which was added to the regions cache.  Now we know that RegionClient@347264055(chan=null, #pending_rpcs=0, #batched=0, #rpcs_inflight=0) is hosting 1 region.
2020-07-22 14:49:50,904 INFO  [AsyncHBase I/O Worker #3] KerberosClientAuthProvider: Connecting to hbase/a011587@xdap.com
2020-07-22 14:49:50,904 INFO  [AsyncHBase I/O Worker #3] KerberosClientAuthProvider: Client will use GSSAPI as SASL mechanism.
2020-07-22 14:49:50,914 INFO  [AsyncHBase I/O Worker #2] RegionClient: Initialized security helper: org.hbase.async.SecureRpcHelper96@2d5e61df for region client: RegionClient@1751490247(chan=null, #pending_rpcs=2, #batched=0, #rpcs_inflight=0)
2020-07-22 14:49:50,915 INFO  [AsyncHBase I/O Worker #3] RegionClient: Initialized security helper: org.hbase.async.SecureRpcHelper96@65f61f3 for region client: RegionClient@347264055(chan=null, #pending_rpcs=1, #batched=0, #rpcs_inflight=0)
2020-07-22 14:49:50,920 INFO  [AsyncHBase I/O Worker #3] SecureRpcHelper96: SASL client context established. Negotiated QoP: auth on for: RegionClient@347264055(chan=null, #pending_rpcs=1, #batched=0, #rpcs_inflight=0)
2020-07-22 14:49:50,920 INFO  [AsyncHBase I/O Worker #2] SecureRpcHelper96: SASL client context established. Negotiated QoP: auth on for: RegionClient@1751490247(chan=null, #pending_rpcs=2, #batched=0, #rpcs_inflight=0)
2020-07-22 14:49:50,938 INFO  [main] TSDB: Flushing compaction queue
2020-07-22 14:49:50,940 INFO  [main] HBaseClient: Channel [id: 0x0c7ea9d1, /10.12.8.38:46113 => /10.12.8.230:60020] is disconnecting: [id: 0x0c7ea9d1, /10.12.8.38:46113 => /10.12.8.230:60020] DISCONNECT
2020-07-22 14:49:50,941 INFO  [main] HBaseClient: Lost connection with the .META. region
2020-07-22 14:49:50,942 INFO  [main] HBaseClient: Channel [id: 0x84099b27, /10.12.8.38:5089 => /10.12.8.232:60020] is disconnecting: [id: 0x84099b27, /10.12.8.38:5089 => /10.12.8.232:60020] DISCONNECT
2020-07-22 14:49:50,943 INFO  [main] HBaseClient: Channel [id: 0xeeec7e59, /10.12.8.38:29695 => /10.12.4.118:60020] is disconnecting: [id: 0xeeec7e59, /10.12.8.38:29695 => /10.12.4.118:60020] DISCONNECT
2020-07-22 14:49:50,945 INFO  [main] TSDB: Completed shutting down the TSDB
Exception in thread "main" java.lang.RuntimeException: Initialization failed
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:237)
Caused by: com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
        at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169)
        at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:142)
        at com.stumbleupon.async.DeferredGroup.access$000(DeferredGroup.java:36)
        at com.stumbleupon.async.DeferredGroup$1Notify.call(DeferredGroup.java:82)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
        at com.stumbleupon.async.Deferred.access$300(Deferred.java:430)
        at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
        at com.stumbleupon.async.Deferred.access$300(Deferred.java:430)
        at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005)
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:720)
        at org.hbase.async.RegionClient.decode(RegionClient.java:1575)
        at org.hbase.async.RegionClient.decode(RegionClient.java:88)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3857)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hbase.async.RemoteException: java.io.IOException
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2242)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:183)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:163)
Caused by: java.lang.NullPointerException

        at org.hbase.async.RegionClient.makeException(RegionClient.java:1797)
        at org.hbase.async.RegionClient.decodeException(RegionClient.java:1815)
        at org.hbase.async.RegionClient.decode(RegionClient.java:1492)
        ... 29 more

**Comment by qiguoxiaosheng** [comment]
I met a similar problem when use the asynchbase.jar which build by myself, but when I change the version to 1.8.x , this problem was disappeared.

**Comment by ywww** [comment]
in hbase
list_quotas
set_quota TYPE => THROTTLE, NAMESPACE => 'tsdb namespace', LIMIT => NONE

then is ok
