### ISSUE TITLE
Failing FSCK with v 2.4.0

### ISSUE THREAD

**Issue by nimitnagpal** [OpenTSDB/opentsdb#2141]
I am using OpenTsdb with Bigtable
Wanted to clean up the orphaned data using the FSCK CLI tool : http://opentsdb.net/docs/build/html/user_guide/cli/fsck.html 

Seeing following issue : 
`root@opentsdb-read-854b77c77c-2l695:/opentsdb/build# tsdb fsck`
`Running OpenTSDB with Bigtable support`
`SLF4J: Class path contains multiple SLF4J bindings.`
`SLF4J: Found binding in [jar:file:/usr/local/share/opentsdb/lib/asyncbigtable-0.3.1-20170903.031804-2-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]`
`SLF4J: Found binding in [jar:file:/usr/local/share/opentsdb/lib/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]`
`SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.`
`SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]`
`log4j:WARN No appenders could be found for logger (net.opentsdb.utils.Config).`
`log4j:WARN Please initialize the log4j system properly.`
`log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`

`Exception in thread "main" java.lang.IllegalArgumentException: Unknown option --sync`
	`at net.opentsdb.tools.ArgP.has(ArgP.java:213)`
	`at net.opentsdb.tools.FsckOptions.<init>(FsckOptions.java:57)`
	`at net.opentsdb.tools.Fsck.main(Fsck.java:1282)`

**Comment by manolama** [comment]
@nimitnagpal Can you try with the `--full-scan` flag? It should throw an error about running with a query or passing that flag. The latest code in the main branch is working ok.

**Comment by cntpro** [comment]
FsckOptions.java  
public static void addDataOptions(final ArgP argp) {
    argp.addOption("--full-scan", "Scan the entire data table.");
    argp.addOption("--fix", "Fix errors as they're found. Use in combination with"
        + " other flags.");
    argp.addOption("--fix-all", "Set all flags and fix errors as they're found.");
    argp.addOption("--compact", "Compacts rows after parsing.");
    argp.addOption("--resolve-duplicates", 
        "Keeps the oldest (default) or newest duplicates. See --last-write-wins");
    argp.addOption("--last-write-wins", 
        "Last data point written will be kept when fixing duplicates.\n" +
        "            May be set via config file and the 'tsd.storage.fix_duplicates' option.");
    argp.addOption("--delete-orphans", 
        "Delete any time series rows where one or more UIDs fail resolution.");
    argp.addOption("--delete-unknown-columns", 
        "Delete any unrecognized column that doesn't belong to OpenTSDB.");
    argp.addOption("--delete-bad-values", 
        "Delete single column datapoints with bad values.");
    argp.addOption("--delete-bad-rows", "Delete rows with invalid keys.");
    argp.addOption("--delete-bad-compacts", 
        "Delete compacted columns that cannot be parsed.");
    argp.addOption("--threads", "NUMBER",
        "Number of threads to use when executing a full table scan.");
  }
