### ISSUE TITLE
When appends are disabled, /api/query/last gives error for certain timestamps: Offset of [0] is out of bounds for the qualifier length of [1]

### ISSUE THREAD

**Issue by twegener-embertec** [OpenTSDB/opentsdb#2186]
Since trying out a relatively recent checkout of opentsdb master (post 2.4.0), the following error sometimes occurs, depending on the timestamp of the last value for the given series:
```
http://tsdb-01:4242/api/query/last?back_scan=96&timeseries=redacted{redacted}: cannot GET /api/query/last?back_scan=96&timeseries=redacted%7Bredacted%7D (400)
```
message:
```Offset of [0] is out of bounds for the qualifier length of [1]```

Looking at the opentsdb source code, this appears to be a regression introduced by:
https://github.com/OpenTSDB/opentsdb/pull/1634/commits/967e4a03fc0f3f2e7b4ddc06d6e8612714575b25
Fix OpenTSDB#1632

I.e. a regression when run with appends disabled (`tsd.storage.enable_appends` `false`, i.e. the default case).

Consider the following code from `src/core/Interval.java`:
```
  public static ArrayList<Cell> extractDataPoints(final ArrayList<KeyValue> row,
...
      // when enable_appends set to true, should get qualifier and value from the HBase Column Value
      if (kv.qualifier()[0] == AppendDataPoints.APPEND_COLUMN_PREFIX) {
        int idx = 0;
        int q_length = 0;
        int v_length = 0;
        while (idx < kv.value().length) {
          q_length = Internal.getQualifierLength(kv.value(), idx);
          v_length = Internal.getValueLengthFromQualifier(kv.value(), idx);
...
```

From `src/core/AppendDataPoints.java`:
```
  public static final byte APPEND_COLUMN_PREFIX = 0x05;
```
The key line is:
```
      if (kv.qualifier()[0] == AppendDataPoints.APPEND_COLUMN_PREFIX) {
```

Note that it doesn't check the config to see whether appends are enabled, and so misinterprets the qualifier.

When appends are not enabled, the first 12 bits of the qualifier will be the offset (in seconds) from the row timestamp (which is on an hour boundary).

For timestamp offsets from 80 to 95 seconds, the first byte of the qualifier will be 0x05, which is the APPEND_COLUMN_PREFIX, and so they get misinterpreted as an append column prefix here.

In that case, it then interprets kv.value() as an embedded qualifier. In my case, a value that is 1 byte long was being stored, so when the following line is called:
```
          q_length = Internal.getQualifierLength(kv.value(), idx);
```
...which calls:
```
  public static short getQualifierLength(final byte[] qualifier, 
      final int offset) {
    validateQualifier(qualifier, offset);  
```
...which calls:
```
  private static void validateQualifier(final byte[] qualifier, 
      final int offset) {
    if (offset < 0 || offset >= qualifier.length - 1) {
      throw new IllegalDataException("Offset of [" + offset + 
          "] is out of bounds for the qualifier length of [" + 
          qualifier.length + "]");
    }
  }
```
...where offset will be 0 and qualifier.length will be 1 (due to the 1 byte value), it results in the error:
`Offset of [0] is out of bounds for the qualifier length of [1]`

This also affects other areas that call `extractDataPoints`, such as `tsdb scan` when dumping points with timestamps that have an offset from the hour such that it hits this problem.

Note that the unit tests in `test/tsd/TestQueryRpcLastDataPoint.java` only appear to test nice round timestamps that fall on the hour, and so they miss this issue. I have created a unit test that reproduces this problem when using a carefully chosen timestamp.

Presumably, the fix would be to add checks for append mode being enabled in the appropriate places.

**Comment by twegener-embertec** [comment]
Here's an example of where I hit this with `tsdb scan` when it was attempting to dump a point that had a timestamp that would hit this:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.opentsdb.core.Internal.extractDataPoints(Internal.java:256)
	at net.opentsdb.core.Internal.extractDataPoints(Internal.java:219)
	at net.opentsdb.tools.DumpSeries.formatKeyValue(DumpSeries.java:215)
	at net.opentsdb.tools.DumpSeries.doDump(DumpSeries.java:136)
	at net.opentsdb.tools.DumpSeries.main(DumpSeries.java:85)
```
Relevant code from `src/core/Internal.java`:
```
  public static ArrayList<Cell> extractDataPoints(final ArrayList<KeyValue> row,
      final int estimated_nvalues) {
    final ArrayList<Cell> cells = new ArrayList<Cell>(estimated_nvalues);
    for (final KeyValue kv : row) {
      final byte[] qual = kv.qualifier();
      final int len = qual.length;
      final byte[] val = kv.value();

      // when enable_appends set to true, should get qualifier and value from the HBase Column Value
      if (kv.qualifier()[0] == AppendDataPoints.APPEND_COLUMN_PREFIX) {
        int idx = 0;
        int q_length = 0;
        int v_length = 0;
        while (idx < kv.value().length) {
          q_length = Internal.getQualifierLength(kv.value(), idx);
          v_length = Internal.getValueLengthFromQualifier(kv.value(), idx);
          final byte[] q = new byte[q_length];
          final byte[] v = new byte[v_length];
          System.arraycopy(kv.value(),idx,q,0,q_length);
          System.arraycopy(kv.value(),idx + q_length,v, 0, v_length);
          idx += q_length + v_length;

          final Cell cell = new Cell(q, v);
          cells.add(cell);
        }

```
Specifically:
```
          System.arraycopy(kv.value(),idx + q_length,v, 0, v_length);
```

**Comment by twegener-embertec** [comment]
Here's an example of where I hit this with `tsdb fsck --full-scan`:

```
2021-08-13 02:45:05,296 [Fsck #1] ERROR [Fsck.run] - Shouldn't be here
	at net.opentsdb.tools.Fsck$FsckWorker.fsckRow(Fsck.java:563) ~[tsdb-2.4.1-SNAPSHOT.jar:a945263]
	at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:330) ~[tsdb-2.4.1-SNAPSHOT.jar:a945263]
```

Relevant code in `src/tools/Fsck.java`:

```
    private void fsckRow(final ArrayList<KeyValue> row,
...
            final ArrayList<Cell> cells = Internal.extractDataPoints(kv);
```

**Comment by twegener-embertec** [comment]
> Presumably, the fix would be to add checks for append mode being enabled in the appropriate places.

Perhaps an alternative fix would be to check that the qualifier is 3 bytes long, along with checking that the first byte is `APPEND_COLUMN_PREFIX`.

**Comment by twegener-embertec** [comment]
The following patch made the problems with `/api/query/last` / `tsdb scan` / `tsdb fsck --full-scan` go away for me:

```
--- a/src/core/Internal.java                                                                                                                            
+++ b/src/core/Internal.java                                                                                                                            
@@ -243,7 +243,7 @@ public final class Internal {
       final byte[] val = kv.value();                                                                                                                   
                                                                                                                                                        
       // when enable_appends set to true, should get qualifier and value from the HBase Column Value                                                   
-      if (kv.qualifier()[0] == AppendDataPoints.APPEND_COLUMN_PREFIX) {                                                                                
+      if (len == 3 && kv.qualifier()[0] == AppendDataPoints.APPEND_COLUMN_PREFIX) {                                                                    
         int idx = 0;                                                                                                                                   
         int q_length = 0;                                                                                                                              
         int v_length = 0;                                                                                                                              
```

**Comment by manolama** [comment]
Yup, excellent walkthrough and good catch. Just checking the length is all that is needed as per your patch. Would you like to submit a PR or would you like me to just apply the patch as-is? And thank you for your work!

**Comment by twegener-embertec** [comment]
> would you like me to just apply the patch as-is?

Sure, no worries.

> And thank you for your work!

You're welcome, and thank you for yours. :-)
