### ISSUE TITLE
NullPointerException occurs in error reporting mechanism when reporting certain Exceptions thrown elsewhere

### ISSUE THREAD

**Issue by twegener-embertec** [OpenTSDB/opentsdb#2189]
Since trying out a relatively recent checkout of opentsdb master (post 2.4.0), the following error sometimes occurs:

```
2021-10-12 20:27:37,727 [OpenTSDB Old I/O server worker (parentId: 908074792, [id: 0x36201f28, /0.0.0.0:4242])] INFO  [ConnectionManager.handleUpstream] - [id: 0x41e7c6f2, /redacted:47796 => /redacted:4242] CONNECTED: /redacted:47796
2021-10-12 20:27:37,729 [OpenTSDB Old I/O server worker (parentId: 908074792, [id: 0x36201f28, /0.0.0.0:4242])] WARN  [HttpQuery.logWarn] - [id: 0x3474fb86, /redacted:47792 => /redacted:4242] Bad Request on /api/query/last?back_scan=96&timeseries=redacted%7Bredacted%7D: null
2021-10-12 20:27:37,730 [OpenTSDB Old I/O server worker (parentId: 908074792, [id: 0x36201f28, /0.0.0.0:4242])] ERROR [RpcHandler.logError] - [id: 0x3474fb86, /redacted:47792 => /redacted:4242] Unexpected exception caught while serving DefaultHttpRequest(chunked: false)
GET /api/query/last?back_scan=96&timeseries=redacted%7Bredacted%7D HTTP/1.1
Host: tsdb-01:4242
Accept-Encoding: gzip, deflate
Connection: close
java.lang.NullPointerException: null
	at net.opentsdb.tsd.HttpSerializer.formatErrorV1(HttpSerializer.java:855) ~[tsdb-2.4.1-SNAPSHOT.jar:a945263]
	at net.opentsdb.tsd.HttpQuery.badRequest(HttpQuery.java:411) ~[tsdb-2.4.1-SNAPSHOT.jar:a945263]
	at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:294) ~[tsdb-2.4.1-SNAPSHOT.jar:a945263]
	at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:132) ~[tsdb-2.4.1-SNAPSHOT.jar:a945263]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]
...
```

I.e. it is hitting a `NullPointerException` while it is attempting to report another exception.

The relevant code is in the following file:

`src/tsd/HttpSerializer.java`
```
  public ChannelBuffer formatErrorV1(final BadRequestException exception) {
    StringBuilder output = 
      new StringBuilder(exception.getMessage().length() * 2);
```

`exception.getMessage()` returns `null`, and so a `NullPointerException` is hit when attempting to call the `length()` method on that.

As such, it means the nature of the other exception that this function was trying to report gets hidden.

A simple fix would be to coerce the result of `exception.getMessage()` to a string at the start of this function before calling `length()`. But arguably, this initial capacity argument to StringBuilder is pretty arbitrary anyway, so it might was well just be a fixed constant rather than being a function of `exception.getMessage().length()`.

This can occur when a plain `RuntimeException` occurs somewhere else (without message) and then is converted directly into a `BadRequestException` (and so still has no message). There are several code paths where this can occur.
(In this particular case, I strongly suspect that the other error triggering this particular case is #2186, e.g. possibly hitting an `ArrayIndexOutOfBoundsException` in `src/core/Interval.java` `extractDataPoints`.)

Note that this bug in the error handling appears to be really old (since 2013), but would only rarely get hit, since it would only get hit when a `RuntimeException` occurs elsewhere, which would only be when there is a bug of that nature elsewhere in the opentsdb code.

It would be good to fix this, so that other more significant exception error messages are not hidden from the logs.

**Comment by twegener-embertec** [comment]
I wasn't sure on the best way to address this.
My interim patch just tries to follow the pattern laid down by `formatErrorV1(final Exception exception)`:

```
diff --git a/src/tsd/HttpSerializer.java b/src/tsd/HttpSerializer.java
index f6108466..bf21d8e5 100644
--- a/src/tsd/HttpSerializer.java
+++ b/src/tsd/HttpSerializer.java
@@ -851,22 +851,28 @@ public abstract class HttpSerializer {
    * @return A standard JSON error
    */
   public ChannelBuffer formatErrorV1(final BadRequestException exception) {
+    // It is possible for mesage and details to be null.
+    String message = exception.getMessage();
+    String details = exception.getDetails();
+    if (message == null) {
+      message = "An unknown exception occurred";
+    }
     StringBuilder output = 
-      new StringBuilder(exception.getMessage().length() * 2);
+      new StringBuilder(message.length() * 2);
     final String jsonp = query.getQueryStringParam("jsonp");
     if (jsonp != null && !jsonp.isEmpty()) {
       output.append(query.getQueryStringParam("jsonp") + "(");
     }
     output.append("{\"error\":{\"code\":");
     output.append(exception.getStatus().getCode());
-    final StringBuilder msg = new StringBuilder(exception.getMessage().length());
-    HttpQuery.escapeJson(exception.getMessage(), msg);
+    final StringBuilder msg = new StringBuilder(message.length());
+    HttpQuery.escapeJson(message, msg);
     output.append(",\"message\":\"").append(msg.toString()).append("\"");
-    if (!exception.getDetails().isEmpty()) {
-      final StringBuilder details = new StringBuilder(
-          exception.getDetails().length());
-      HttpQuery.escapeJson(exception.getDetails(), details);
-      output.append(",\"details\":\"").append(details.toString()).append("\"");
+    if (details != null && !details.isEmpty()) {
+      final StringBuilder edetails = new StringBuilder(
+          details.length());
+      HttpQuery.escapeJson(details, edetails);
+      output.append(",\"details\":\"").append(edetails.toString()).append("\"");
     }
     if (query.showStackTrace()) {
       ThrowableProxy tp = new ThrowableProxy(exception);
```

I'll leave it to you to season to your taste.

But if it makes life easier for you I can post a PR.
Do I need to fill out a contributor agreement before submitting PRs for small things like that?
