### ISSUE TITLE
gwt Internal compiler error for gwt-user-2.5.0.jar

### ISSUE THREAD

**Issue by stukra** [OpenTSDB/opentsdb#227]
Hi,

I am unable to proceed with the make as I keep getting an Internal compilation error for gwt-user-2.5.0.jar while running make.

It seems to be complaining of a serialVersionUID mismatch in one of the classes. I did check the SHA1 of gwt-user-2.5.0.jar just to make sure it matches with the one provided by Google, and it looks fine.
Here are the logs scraped:-

cmp -s ".gwtc-stamp" ".gwtc-stamp-t" && exit 0; \
        /usr/java/jdk1.6.0_26/bin/java  -cp `jar=third_party/gwt/gwt-dev-2.5.0.jar; test -f "$jar" && echo "$jar" || echo "./$jar"`:`jar=third_party/gwt/gwt-user-2.5.0.jar; test -f "$jar" && echo "$jar" || echo "./$jar"`:./src com.google.gwt.dev.Compiler \
            -ea   -war gwt tsd.QueryUi
Compiling module tsd.QueryUi
   [ERROR] Unexpected internal compiler error
java.lang.RuntimeException: Unexpected IOException on in-memory stream
        at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:324)
        at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateUnit(UnifyAst.java:672)
        at com.google.gwt.dev.jjs.impl.UnifyAst.searchForTypeBySource(UnifyAst.java:985)
        at com.google.gwt.dev.jjs.impl.UnifyAst.addRootTypes(UnifyAst.java:530)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:621)
        at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:33)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:278)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:141)
        at com.google.gwt.dev.Compiler.run(Compiler.java:232)
        at com.google.gwt.dev.Compiler.run(Compiler.java:198)
        at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
        at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
        at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
        at com.google.gwt.dev.Compiler.main(Compiler.java:177)
Caused by: java.io.InvalidClassException: com.google.gwt.dev.jjs.SourceOrigin$1; local class incompatible: stream classdesc serialVersionUID = 4713379764594032837, local class serialVersionUID = -2407201776821563037
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:562)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1582)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1495)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1731)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
        at java.util.ArrayList.readObject(ArrayList.java:593)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:974)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
        at com.google.gwt.dev.jjs.ast.JDeclaredType.readMembers(JDeclaredType.java:294)
        at com.google.gwt.dev.jjs.ast.JProgram.deserializeTypes(JProgram.java:205)
        at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:322)
        ... 14 more
make[1]: **\* [.gwtc-stamp] Error 1

**Comment by techsubodh** [comment]
you can also get it passed by including -Dgwt.usearchives=false in its VM argument.

Subodh 
+1 404 906 3042
