### ISSUE TITLE
chunking: max_chunk does not work

### ISSUE THREAD

**Issue by tkrajca** [OpenTSDB/opentsdb#324]
Hi,
I ran into an issue with TSDB's chunking. While chunking itself works, the max_chunk setting doesn't work.

I set max_chunk to 4096 (default), if I send a (chunked) request that is larger than 4096 bytes (I tried to send 20KB), TSDB throws an error. If I send a chunked request that is smaller than 4096 bytes (I tried to send 3KB), it works. I chunk at 1024 bytes.

This happens for both 2.0.0rc2 and 2.0.0rc3, I didn't test this on 2.0.0.

Am I missing something or is this a bug? Please let me know if you need any more details. This is quite a critical feature for us so let me also know if I can help in any way to get this fixed.

Thanks.

OpenTSDB Exception:

```
2014-04-28 00:31:42,002 ERROR [New I/O worker #2] ConnectionManager: Unexpected exception from downstream for [id: 0xcd4ea041, /10.250.0.18:
32970 => /172.16.11.11:4242]
org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 4096 bytes.
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485) ~[netty-3.9.0.Final.jar:na]
        at net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:87) ~[tsdb-2.0.0.jar:efb8186]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.9.0.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.9.0.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
```

TSDB version:

```
reposit@localhost:~$ curl 'http://auvmbes003.repositpower.net:4242/api/version/'
{"timestamp":"1398643680","host":"auvmbes003.repositpower.net","repo":"/root/opentsdb/build","full_revision":"efb818608e5525a2f718384c0880685950220761","short_revision":"efb8186","user":"root","repo_status":"MINT","version":"2.0.0"}reposit@localhost:~$
```

TSDB config:

```
reposit@localhost:~$ curl 'http://auvmbes003.repositpower.net:4242/api/config/'
{"tsd.core.auto_create_metrics":"false","tsd.core.meta.enable_realtime_ts":"false","tsd.core.meta.enable_realtime_uid":"false","tsd.core.meta.enable_tsuid_incrementing":"false","tsd.core.meta.enable_tsuid_tracking":"false","tsd.core.plugin_path":"","tsd.core.tree.enable_processing":"false","tsd.http.cachedir":"/tmp/tsd","tsd.http.request.cors_domains":"*","tsd.http.request.enable_chunked":"true","tsd.http.request.max_chunk":"4096","tsd.http.show_stack_trace":"true","tsd.http.staticroot":"/usr/local/share/opentsdb/static/","tsd.network.async_io":"true","tsd.network.bind":"0.0.0.0","tsd.network.keep_alive":"true","tsd.network.port":"4242","tsd.network.reuse_address":"true","tsd.network.tcp_no_delay":"true","tsd.network.worker_threads":"","tsd.rtpublisher.enable":"false","tsd.rtpublisher.plugin":"","tsd.search.enable":"false","tsd.search.plugin":"","tsd.stats.canonical":"false","tsd.storage.enable_compaction":"true","tsd.storage.flush_interval":"1000","tsd.storage.hbase.data_table":"tsdb","tsd.storage.hbase.meta_table":"tsdb-meta","tsd.storage.hbase.tree_table":"tsdb-tree","tsd.storage.hbase.uid_table":"tsdb-uid","tsd.storage.hbase.zk_basedir":"/hbase-unsecure","tsd.storage.hbase.zk_quorum":"auvmbes001.repositpower.net,auvmbes002.repositpower.net,auvmbes003.repositpower.net"}reposit@localhost:~$ 
```

I use python to test this, this is httplib's debug output of my request (just to make sure it's chunked, etc.)

```
send: 'POST /api/put?details HTTP/1.1\r\nHost: auvmbes003.repositpower.net:4242\r\nTransfer-Encoding: chunked\r\nContent-Type: application/json\r\nAccept-Encoding: gzip, deflate, compress\r\nAccept: */*\r\nUser-Agent: python-requests/2.2.1 CPython/2.7.5 Linux/3.13.9-200.fc20.x86_64\r\n\r\n'
send: '400'
send: '\r\n'
send: '[{"timestamp": 1298984700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298944200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298931600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298911800, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298957100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_str'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'uctures.classes.historical.NetworkPrices"}}, {"timestamp": 1298926200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298978400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298937000, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298949300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298940300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298970600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, '
send: '\r\n'
send: '400'
send: '\r\n'
send: '"tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298947200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298907600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298903100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298952600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298924400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298921700, "metric": "zzz_netw'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'ork_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298934900, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298908500, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298977200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298942400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {'
send: '\r\n'
send: '400'
send: '\r\n'
send: '"timestamp": 1298984700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298944200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298931600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298911800, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298957100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_struc'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'tures.classes.historical.NetworkPrices"}}, {"timestamp": 1298926200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298978400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298937000, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298949300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298940300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298970600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "t'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'ags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298947200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298907600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298903100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298952600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298924400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298921700, "metric": "zzz_networ'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'k_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298934900, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298908500, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298977200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298942400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"t'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'imestamp": 1298984700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298944200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298931600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298911800, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298957100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structu'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'res.classes.historical.NetworkPrices"}}, {"timestamp": 1298926200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298978400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298937000, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298949300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298940300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298970600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tag'
send: '\r\n'
send: '400'
send: '\r\n'
send: 's": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298947200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298907600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298903100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298952600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298924400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298921700, "metric": "zzz_network_'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298934900, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298908500, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298977200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298942400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"tim'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'estamp": 1298984700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298944200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298931600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298911800, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298957100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structure'
send: '\r\n'
send: '400'
send: '\r\n'
send: 's.classes.historical.NetworkPrices"}}, {"timestamp": 1298926200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298978400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298937000, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298949300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298940300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298970600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags"'
send: '\r\n'
send: '400'
send: '\r\n'
send: ': {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298947200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298907600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298903100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298952600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298924400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298921700, "metric": "zzz_network_da'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'ily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298934900, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298908500, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298977200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298942400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"times'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'tamp": 1298984700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298944200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298931600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298911800, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298957100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.'
send: '\r\n'
send: '400'
send: '\r\n'
send: 'classes.historical.NetworkPrices"}}, {"timestamp": 1298926200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298978400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298937000, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298949300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298940300, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298970600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": '
send: '\r\n'
send: '400'
send: '\r\n'
send: '{"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298947200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298907600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298903100, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298952600, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298924400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298921700, "metric": "zzz_network_dail'
send: '\r\n'
send: '3f6'
send: '\r\n'
send: 'y", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298909700, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298934900, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298908500, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298977200, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}, {"timestamp": 1298942400, "metric": "zzz_network_daily", "value": 0.0013541666666666667, "tags": {"module_code": "Reposit_EC.data_structures.classes.historical.NetworkPrices"}}]'
send: '\r\n'
send: '0\r\n\r\n'
Traceback (most recent call last):
  File "test_tsdb.py", line 20, in <module>
    headers={"Content-Type": "application/json"}, data=chunk(json.dumps(data)))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(sockerr)
requests.exceptions.ConnectionError: [Errno 104] Connection reset by peer
```

**Comment by bertrandhaut** [comment]
I vote also for a renaming in max_request_size (keeping also the old name for compatibility issue).
It was quite confusing.
