### ISSUE TITLE
/tmp/opentsdb directory erased on a recurring basis, leading to GUI being unavailable

### ISSUE THREAD

**Issue by jletroui** [OpenTSDB/opentsdb#396]
Regularly, GUI on one of the nodes is not working anymore and is producing the following error:
![tsd_and_1__default__bash_](https://cloud.githubusercontent.com/assets/450475/4458118/c226bd0e-489f-11e4-9bc3-c79b33b4f6f3.png)

Looking on the server, the /tmp/opentsdb has indeed disappeared. Recreating it manually is fixing the issue (temporarily).

This is happening approximately 0.1 time per week per user per node. Up to now, we have not identified a pattern to reproduce it solidly.

**Comment by oozie** [comment]
It's `dumpToFiles`. Given that the default location for cachedir is `/tmp/opentsdb`, the right thing to do here is to defend against this by trying to recreate cache dir and log a warning on a failure.
```
Request failed: Internal Server Error
    java.io.FileNotFoundException: /tmp/opentsdb/e024de37_0.dat (No such file or directory)
    at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_65]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[na:1.7.0_65]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:110) ~[na:1.7.0_65]
    at java.io.PrintWriter.<init>(PrintWriter.java:184) ~[na:1.7.0_65]
    at net.opentsdb.graph.Plot.dumpToFiles(Plot.java:199) ~[tsdb-2.1.0RC1.jar:36fba94]
    at net.opentsdb.tsd.GraphHandler.runGnuplot(GraphHandler.java:719) ~[tsdb-2.1.0RC1.jar:36fba94]
    at net.opentsdb.tsd.GraphHandler$RunGnuplot.execute(GraphHandler.java:305) ~[tsdb-2.1.0RC1.jar:36fba94]
    at net.opentsdb.tsd.GraphHandler$RunGnuplot.run(GraphHandler.java:292) ~[tsdb-2.1.0RC1.jar:36fba94]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65] 
`

**Comment by IDerr** [comment]
Hi @jletroui 
if your question has been answered, could you close this issue ?

Thanks a lot :)

**Comment by jletroui** [comment]
Sorry, of course. Thanks for the great support!
