### ISSUE TITLE
Caused by: java.lang.IllegalStateException: id=[0, 0, -51] => name=4756, already mapped to 8905

### ISSUE THREAD

**Issue by xhh0168** [OpenTSDB/opentsdb#416]
Frequently report this error, the error messages is as follows, how to solve? Thank you

2014-11-18 00:55:14,219 ERROR [New I/O worker #2] RpcHandler: [id: 0xdde31487, /61.131.3.6:4694 => /66.175.222.2:10000] Unexpected exception caught while serving [null, java.jvm.memory, 1416272113, 33.65, port=9911, app=SMProxy_CMPP, host=10.0.0.86, appname=短信网关, pid=4756, networkname=电信机房]
java.lang.RuntimeException: Should never be here
        at net.opentsdb.uid.UniqueId.getOrCreateId(UniqueId.java:607) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.Tags.resolveAllInternal(Tags.java:461) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.Tags.resolveOrCreateAll(Tags.java:448) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.IncomingDataPoints.rowKeyTemplate(IncomingDataPoints.java:135) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.TSDB.addPointInternal(TSDB.java:664) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.TSDB.addPoint(TSDB.java:644) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.PutDataPointRpc.importDataPoint(PutDataPointRpc.java:253) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.PutDataPointRpc.execute(PutDataPointRpc.java:62) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.RpcHandler.handleTelnetRpc(RpcHandler.java:206) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:176) ~[tsdb-2.1.0.jar:]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na]
        at net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:90) [tsdb-2.1.0.jar:]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_38]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_38]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_38]
Caused by: java.lang.IllegalStateException: id=[0, 0, -51] => name=4756, already mapped to 8905
        at net.opentsdb.uid.UniqueId.addNameToCache(UniqueId.java:256) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.uid.UniqueId.access$000(UniqueId.java:53) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.uid.UniqueId$1GetIdCB.call(UniqueId.java:289) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.uid.UniqueId$1GetIdCB.call(UniqueId.java:278) ~[tsdb-2.1.0.jar:]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.Deferred.addCallback(Deferred.java:724) ~[suasync-1.4.0.jar:fe17b98]
        at net.opentsdb.uid.UniqueId.getIdAsync(UniqueId.java:293) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.uid.UniqueId.getOrCreateId(UniqueId.java:563) ~[tsdb-2.1.0.jar:]
        ... 45 common frames omitted

---

2014-11-18 02:36:12,022 ERROR [New I/O worker #1] ConnectionManager: Unexpected exception from downstream for [id: 0x6bbc1ae2, /61.131.3.6:44078 => /66.175.222.2:10000]
java.lang.AssertionError: This Deferred was already called! New result=java.lang.IllegalStateException: id=[0, 1, -63] => name=8854, already mapped to 9547, this=Deferred@1351651247(state=DONE, result=java.lang.IllegalStateException: id=[0, 1, -63] => name=8854, already mapped to 9547, callback=<none>, errback=<none>)
at com.stumbleupon.async.Deferred.callback(Deferred.java:982) ~[suasync-1.4.0.jar:fe17b98]
at net.opentsdb.uid.UniqueId$UniqueIdAllocator$1ErrBack.call(UniqueId.java:384) ~[tsdb-2.1.0.jar:]
at net.opentsdb.uid.UniqueId$UniqueIdAllocator$1ErrBack.call(UniqueId.java:382) ~[tsdb-2.1.0.jar:]
at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[suasync-1.4.0.jar:fe17b98]
at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[suasync-1.4.0.jar:fe17b98]
at com.stumbleupon.async.Deferred.addErrback(Deferred.java:756) ~[suasync-1.4.0.jar:fe17b98]
at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:406) ~[tsdb-2.1.0.jar:]
at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[suasync-1.4.0.jar:fe17b98]
at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[suasync-1.4.0.jar:fe17b98]
at com.stumbleupon.async.Deferred.addBoth(Deferred.java:772) ~[suasync-1.4.0.jar:fe17b98]
at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:406) ~[tsdb-2.1.0.jar:]
at net.opentsdb.uid.UniqueId$UniqueIdAllocator.tryAllocate(UniqueId.java:353) ~[tsdb-2.1.0.jar:]
at net.opentsdb.uid.UniqueId.getOrCreateId(UniqueId.java:594) ~[tsdb-2.1.0.jar:]
at net.opentsdb.core.Tags.resolveAllInternal(Tags.java:461) ~[tsdb-2.1.0.jar:]
at net.opentsdb.core.Tags.resolveOrCreateAll(Tags.java:448) ~[tsdb-2.1.0.jar:]
at net.opentsdb.core.IncomingDataPoints.rowKeyTemplate(IncomingDataPoints.java:135) ~[tsdb-2.1.0.jar:]
at net.opentsdb.core.TSDB.addPointInternal(TSDB.java:664) ~[tsdb-2.1.0.jar:]
at net.opentsdb.core.TSDB.addPoint(TSDB.java:644) ~[tsdb-2.1.0.jar:]
at net.opentsdb.tsd.PutDataPointRpc.importDataPoint(PutDataPointRpc.java:253) ~[tsdb-2.1.0.jar:]
at net.opentsdb.tsd.PutDataPointRpc.execute(PutDataPointRpc.java:62) ~[tsdb-2.1.0.jar:]
at net.opentsdb.tsd.RpcHandler.handleTelnetRpc(RpcHandler.java:206) ~[tsdb-2.1.0.jar:]
at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:176) ~[tsdb-2.1.0.jar:]
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na]
at net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:90) [tsdb-2.1.0.jar:]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_38]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_38]
at java.lang.Thread.run(Thread.java:662) [na:1.6.0_38]

**Comment by IDerr** [comment]
Hi @xhh0168 ,
if your question has been answered, could you close this issue ?

Thanks a lot :)

**Comment by FranklinRay** [comment]
I also find this problem. In the code, 
`private void addNameToCache(final byte[] id, final String name) {
    final String key = fromBytes(id);
    String found = id_cache.get(key);
    if (found == null) {
      found = id_cache.putIfAbsent(key, name);
    }
    if (found != null && !found.equals(name)) {
      throw new IllegalStateException("id=" + Arrays.toString(id) + " => name="
          + name + ", already mapped to " + found);
    }
  }`
It looks like didn't support to modify the cache. It is a necessary feature or a bug?
