### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: null using http api

### ISSUE THREAD

**Issue by scicco** [OpenTSDB/opentsdb#445]
Hello,

we are using 

OpenTSDB version [2.0.1] built from revision in a MODIFIED state
Built on Mon Nov 10 03:13:10 GMT+100 2014 by root@centos.localhost:/root/rpmbuild/BUILD/opentsdb-2.0.1

and we're getting this error on log when running the following query:

12:27:56.612 ERROR [HttpQuery.logError] - [id: 0x95b622b0, /127.0.0.1:53566 => /127.0.0.1:14242] Internal Server Error on /q?start=1d-ago&end=2015/02/17-11:15:57&m=avg:qoe.upload.total.kbps{fw=VV2222_CLC_3.1.0.0040}&ascii
java.lang.ArrayIndexOutOfBoundsException: null
12:27:56.613 INFO  [HttpQuery.logInfo] - [id: 0x95b622b0, /127.0.0.1:53566 => /127.0.0.1:14242] HTTP /q?start=1d-ago&end=2015/02/17-11:15:57&m=avg:qoe.upload.total.kbps{fw=VV2222_CLC_3.1.0.0040}&ascii done in 9ms

when i use http query api i see the following lines:

12:40:40.547 INFO  [HttpQuery.logInfo] - [id: 0x93e15f16, /127.0.0.1:32851 :> /127.0.0.1:14242] HTTP /api/query?start=1w-ago&m=avg:24h-avg:qoe.upload.user.kbps%7B
12:40:40.666 ERROR [HttpQuery.logError] - [id: 0xd3ac7a0c, /127.0.0.1:32855 => /127.0.0.1:14242] Internal Server Error on /api/query?start=1w-ago&m=min:24h-min:qo
java.lang.RuntimeException: Shouldn't be here
        at net.opentsdb.tsd.QueryRpc.execute(QueryRpc.java:135) ~[tsdb-2.0.1.jar:]
        at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:255) [tsdb-2.0.1.jar:]
        at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:163) [tsdb-2.0.1.jar:]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
        at net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:87) [tsdb-2.0.1.jar:]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
        at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.DeferredGroup.access$200(DeferredGroup.java:36) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.DeferredGroup$1NotifyOrdered.call(DeferredGroup.java:97) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[suasync-1.4.0.jar:fe17b98]
        at net.opentsdb.core.TsdbQuery$1ScannerCB.call(TsdbQuery.java:419) ~[tsdb-2.0.1.jar:]
        at net.opentsdb.core.TsdbQuery$1ScannerCB.call(TsdbQuery.java:352) ~[tsdb-2.0.1.jar:]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[suasync-1.4.0.jar:fe17b98]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[suasync-1.4.0.jar:fe17b98]
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:506) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1351) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:89) ~[asynchbase-1.6.0.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1082) ~[asynchbase-1.6.0.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:2677) ~[asynchbase-1.6.0.jar:na]
        ... 12 common frames omitted
java.lang.ArrayIndexOutOfBoundsException: null

the same query using cli give us no problem at all:
tsdb scan --import 1w-ago avg qoe.upload.total.kbps fw=VV2222_CLC_3.1.0.0040

we've perfomed an fsck on the same data portion with no problem found:

tsdb fsck 1w-ago avg qoe.upload.total.kbps fw=VV2222_CLC_3.1.0.0040

2015-02-17 12:32:09,375 INFO  [main] Config: Successfully loaded configuration file: /etc/opentsdb/opentsdb.conf
2015-02-17 12:32:09,495 INFO  [main] ZooKeeper: Client environment:zookeeper.version=3.3.6-1366786, built on 07/29/2012 06:22 GMT
2015-02-17 12:32:09,496 INFO  [main] ZooKeeper: Client environment:host.name=adb2.adb.netvision.net.il
2015-02-17 12:32:09,496 INFO  [main] ZooKeeper: Client environment:java.version=1.7.0_71
2015-02-17 12:32:09,496 INFO  [main] ZooKeeper: Client environment:java.vendor=Oracle Corporation
2015-02-17 12:32:09,496 INFO  [main] ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.71.x86_64/jre
2015-02-17 12:32:09,496 INFO  [main] ZooKeeper: Client environment:java.class.path=/usr/share/opentsdb/*.jar:/usr/share/opentsdb:/usr/share/opentsdb/bin:/usr/share/opentsdb/lib/asynchbase-1.6.0.jar:/usr/share/opentsdb/lib/guava-18.0.jar:/usr/share/opentsdb/lib/jackson-annotations-2.4.3.jar:/usr/share/opentsdb/lib/jackson-core-2.4.3.jar:/usr/share/opentsdb/lib/jackson-databind-2.4.3.jar:/usr/share/opentsdb/lib/log4j-over-slf4j-1.7.7.jar:/usr/share/opentsdb/lib/logback-classic-1.0.13.jar:/usr/share/opentsdb/lib/logback-core-1.0.13.jar:/usr/share/opentsdb/lib/netty-3.9.4.Final.jar:/usr/share/opentsdb/lib/protobuf-java-2.5.0.jar:/usr/share/opentsdb/lib/slf4j-api-1.7.7.jar:/usr/share/opentsdb/lib/suasync-1.4.0.jar:/usr/share/opentsdb/lib/tsdb-2.0.1.jar:/usr/share/opentsdb/lib/zookeeper-3.3.6.jar:/usr/share/opentsdb/etc/opentsdb
2015-02-17 12:32:09,496 INFO  [main] ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2015-02-17 12:32:09,497 INFO  [main] ZooKeeper: Client environment:java.io.tmpdir=/tmp
2015-02-17 12:32:09,497 INFO  [main] ZooKeeper: Client environment:java.compiler=<NA>
2015-02-17 12:32:09,497 INFO  [main] ZooKeeper: Client environment:os.name=Linux
2015-02-17 12:32:09,497 INFO  [main] ZooKeeper: Client environment:os.arch=amd64
2015-02-17 12:32:09,497 INFO  [main] ZooKeeper: Client environment:os.version=2.6.32-431.20.5.el6.x86_64
2015-02-17 12:32:09,497 INFO  [main] ZooKeeper: Client environment:user.name=root
2015-02-17 12:32:09,498 INFO  [main] ZooKeeper: Client environment:user.home=/root
2015-02-17 12:32:09,498 INFO  [main] ZooKeeper: Client environment:user.dir=/root
2015-02-17 12:32:09,499 INFO  [main] ZooKeeper: Initiating client connection, connectString=localhost sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@748684b1
2015-02-17 12:32:09,511 INFO  [main] HBaseClient: Need to find the -ROOT- region
2015-02-17 12:32:09,511 INFO  [main-SendThread()] ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181
2015-02-17 12:32:09,517 INFO  [main-SendThread(localhost:2181)] ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-02-17 12:32:09,530 INFO  [main-SendThread(localhost:2181)] ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x149ecdb066d5a7f, negotiated timeout = 5000
2015-02-17 12:32:09,555 INFO  [main-EventThread] HBaseClient: Connecting to .META. region @ XXX.XXX.XXX.XXX:60020
2015-02-17 12:32:09,602 INFO  [main-EventThread] ZooKeeper: Session: 0x149ecdb066d5a7f closed
2015-02-17 12:32:09,603 INFO  [main-EventThread] ClientCnxn: EventThread shut down
2015-02-17 12:32:09,642 INFO  [New I/O worker #1] HBaseClient: Added client for region RegionInfo(table="tsdb-uid", region_name="tsdb-uid,,1399570190507.d4319c9ca6dbf4a1934d8503590173b5.", stop_key=""), which was added to the regions cache.  Now we know that RegionClient@402060195(chan=[id: 0x11194df0, /XXX.XXX.XXX.XXX:56853 => /XXX.XXX.XXX.XXX:60020], #pending_rpcs=0, #batched=0, #rpcs_inflight=1) is hosting 1 region.
2015-02-17 12:32:09,644 INFO  [New I/O worker #1] HBaseClient: Added client for region RegionInfo(table="tsdb", region_name="tsdb,,1413630095973.1a8b66891d39bd129d1af372e73f4980.", stop_key=[0, 0, 9, 84, 64, 21, -80, 0, 0, 2, 0, 14, 50]), which was added to the regions cache.  Now we know that RegionClient@402060195(chan=[id: 0x11194df0, /XXX.XXX.XXX.XXX:56853 => /XXX.XXX.XXX.XXX:60020], #pending_rpcs=0, #batched=0, #rpcs_inflight=1) is hosting 2 regions.
2015-02-17 12:32:09,691 INFO  [main] Fsck: Starting to fsck data covered by TsdbQuery(start_time=1423564329, end_time=1424169129691, metric=[0, 0, 3], tags=[[0, 0, 4, 0, -65, -123]], rate=false, aggregator=avg, group_bys=())
27875 KVs (in 27864 rows) analyzed in 1237ms (~22534 KV/s)
No error found.
2015-02-17 12:32:10,929 INFO  [main] TSDB: Flushing compaction queue
2015-02-17 12:32:10,932 INFO  [main] HBaseClient: Lost connection with the .META. region

Let me know if you need more details.

Thank you in advance

**Comment by oozie** [comment]
Does it manifest a different behavior if you append `&no_annotations=1` to the query string?

**Comment by scicco** [comment]
i've tried with &no_annotations parameter but i still got the same problem.

**Comment by scicco** [comment]
update:

we have upgraded to 2.1.0 RC1 but still have same problems. This problem occurs only when trying to retrieve a large amount of data.

**Comment by scicco** [comment]
i've checked default value of my server doing
java -XX:+PrintFlagsFinal -version | grep ThreadStackSize

1024 is my result

I fixed creating a new file named /usr/share/opentsdb/bin/tsdb.local with the following content:
JVMARGS="-Xss4096k"

and fixing the file /usr/share/opentsdb/tsdb like this oozie/opentsdb@ba4548410eed6c942df7892c3d326c08f9b73009 as you did in your PR #389
