### ISSUE TITLE
PipelineFactory Preventing Orderly JVM Shutdown

### ISSUE THREAD

**Issue by nickman** [OpenTSDB/opentsdb#455]
In 2.1.0RC1, the idle socket timeout handler appears to be preventing an orderly shutdown.
I was running a build of it and when I stopped the server (using diediedie), the JVM stalled after signalling that it was being shutdown. I triggered a thread dump and this grabbed my eye:

```
"Hashed wheel timer #3" prio=10 tid=0x00007f42f4027800 nid=0x66c3 waiting on condition [0x00007f43313cd000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:445)
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:364)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at java.lang.Thread.run(Thread.java:745)
```

Looking at the pipeline factory code, the HashedWheelTimer used to provide a timer to the timeouthandler is spawned using non-daemon threads.

I don't have capacity for a formal patch right now, but the fix is simple:

The code:

```java
private final Timer timer = new HashedWheelTimer();
```

should be replaced with:

```java
  private final ThreadFactory timerThreadFactory = new ThreadFactory() {
    public Thread newThread(final Runnable r) {      
      final Thread t = new Thread(r, "PipelineFactoryTimer");
      t.setDaemon(true);
      return t;
    }
  };
  private final Timer timer = new HashedWheelTimer(timerThreadFactory);
```

This fixed the issue for me.

**Comment by manolama** [comment]
ah good catch
