### ISSUE TITLE
Query - connection refused error

### ISSUE THREAD

**Issue by ebereketoglu** [OpenTSDB/opentsdb#500]
I am trying to visulize the data of the multiple metrics in the same Grafana dashboard. When I try it for 8 or 10 metrics, there is not any error. But when I try with 16 metrics I get the below error.  Hbase is runing in standalone mode. What can cause this problem? Even the query is too big, it should not crash the connection. 

java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_76]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_76]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1143) ~[zookeeper-3.3.6.jar:3.3.6-1366786]
14:49:33.863 INFO  [ClientCnxn.startConnect] - Opening socket connection to server localhost/127.0.0.1:2181
14:49:33.864 WARN  [ClientCnxn.run] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_76]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_76]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1143) ~[zookeeper-3.3.6.jar:3.3.6-1366786]

**Comment by ebereketoglu** [comment]
I noticed that the problem occurs only while querying a specific metric. When I query the 5m downsampled data for 7 days, there is not any problem. But when I query the 30m downsampled data for a month, I get this error. I am not sure the issue is because of the Grafana, OpenTSDB or HBase. But even there is a problem with the query of Grafana, the connection should not be crashed.

**Comment by ebereketoglu** [comment]
I tried the same query with gnuplot and the result was the same. I have about 80 metrics, but only one of them is giving this error.  After I try to query from this metric, all queries are locking up and TSD dashboard is unresponsive until TSD is restarted.

**Comment by ebereketoglu** [comment]
I deleted all the data and imported again and it works.

**Comment by jparicka** [comment]
hmmm
