### ISSUE TITLE
fsck not functioning in release 2.1.0

### ISSUE THREAD

**Issue by christoffbotha** [OpenTSDB/opentsdb#510]
I am running this version of OpenTSDB:
```
OpenTSDB version [2.1.0] built from revision in a MODIFIED state
Built on Thu May 07 07:04:26 GMT+200 2015 by root@centos.localhost:/root/rpmbuild/BUILD/opentsdb-2.1.0
```

I have determined the time window and metric where duplicate data points were submitted. It is confirmed by the following query.
```
[root@34e6d79526ba ~]# tsdb query 24h-ago 12h-ago sum linux.net.bytes
Exception in thread "main" net.opentsdb.core.IllegalDataException: Duplicate timestamp for key=[0, 5, 51, 85, 83, 60, -64, 0, 0, 3, 0, 0, 51, 0, 0, 16, 0, 0, 104, 0, 0, 18, 0, 0, 111], ms_offset=1283000, older=[79, 50, -76, -11], newer=[0, 0, 0, 0, -78, -76, -11, 11]; set tsd.storage.fix_duplicates=true to fix automatically or run Fsck
	at net.opentsdb.core.CompactionQueue$Compaction.mergeDatapoints(CompactionQueue.java:452)
	at net.opentsdb.core.CompactionQueue$Compaction.compact(CompactionQueue.java:337)
	at net.opentsdb.core.CompactionQueue.compact(CompactionQueue.java:563)
```
When I try to run fsck to fix the problem, I get no response in the terminal.
```
[root@34e6d79526ba ~]# tsdb fsck 24h-ago 12h-ago sum linux.net.bytes
[root@34e6d79526ba ~]# 
```

With the ```--fix``` flag added it returns a bit slower than the dry run, as in the listing above, but the duplicates are not fixed.

**Comment by IzakMarais** [comment]
So is fsck not supported anymore for future openTSDB releases, or are there plans to fix this? We used to find it a usefull tool to help track down the cause of duplicate datapoints; it is sad that we cannot use it with the new version of openTSDB.

**Comment by manolama** [comment]
Yeah, fsck is definitely supported and we posted some fixes not long ago that should have helped with this. Try again from the Master or Next branch please.

**Comment by IDerr** [comment]
Without news, I think you can close this @manolama
