### ISSUE TITLE
Unable to build opentsdb with next branch

### ISSUE THREAD

**Issue by gsaray101** [OpenTSDB/opentsdb#522]
I tried this:

git clone https://github.com/OpenTSDB/opentsdb.git --depth=1  -b next

cd opentsdb/
 
git fetch origin master:master --depth=1

git merge -s ours master

when I ran ./build.sh, I get this error:

javac: file not found: src/query/TagVFilter.java
Usage: javac <options> <source files>
use -help for a list of possible options
make[1]: *** [.javac-stamp] Error 2
make[1]: Leaving directory `/app/data.3/opentsdb/build'
make: *** [all] Error 2

Any ideas how I could get master and next branch and merge them and build it ?

**Comment by gsaray101** [comment]
I tried to clone next branch and compiled it, but I get these errors:

2015-06-11 18:29:24,829 INFO  [main] TSDMain: Starting.
2015-06-11 18:29:24,834 INFO  [main] TSDMain: net.opentsdb.tools 2.2.0-SNAPSHOT built at revision 24773ed (MINT)
2015-06-11 18:29:24,834 INFO  [main] TSDMain: Built on 2015/06/11 22:17:15 +0000 by root@ctcprcapplan001:/app/data.3/opentsdb/build
Invalid usage.  Unrecognized option --conf=/etc/opentsdb.conf
2015-06-11 18:29:24,840 INFO  [main] Config: Successfully loaded configuration file: /etc/opentsdb.conf
2015-06-11 18:29:24,947 INFO  [main] Config: Successfully loaded configuration file: /etc/opentsdb.conf
2015-06-11 18:29:25,077 INFO  [main] TSDB: Flushing compaction queue
Exception in thread "main" java.lang.RuntimeException: Initialization failed
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:185)
Caused by: java.lang.NoClassDefFoundError: net/opentsdb/query/filter/TagVFilter
        at net.opentsdb.core.TSDB.initializePlugins(TSDB.java:219)
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:143)
Caused by: java.lang.ClassNotFoundException: net.opentsdb.query.filter.TagVFilter
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more

Can somebody tell me how can I compile this? Are the tree sync and metasyc issues addressed with the next branch?

**Comment by torkelo** [comment]
me too

**Comment by manolama** [comment]
Yeah, that was a goof up on my part, thanks @Misenko for the fix.
