### ISSUE TITLE
In the tag, the character '@' is not allowed in storage

### ISSUE THREAD

**Issue by ansible-lee** [OpenTSDB/opentsdb#554]
Exception information:
java.lang.IllegalArgumentException: Invalid tag value ("SIA@m@standby"): illegal character: @
        at net.opentsdb.core.Tags.validateString(Tags.java:413) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.IncomingDataPoints.checkMetricAndTags(IncomingDataPoints.java:106) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.TSDB.addPointInternal(TSDB.java:671) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.core.TSDB.addPoint(TSDB.java:617) ~[tsdb-2.1.0.jar:]
        at com.easemob.tsdb.thrift.rpc.TSDBWrapper.addPoint(TSDBWrapper.java:23) 

Why？
My tag name is “SIA@m@standby”。Why not allow the character '@' storage？what are the reasons？

**Comment by ansible-lee** [comment]
Because of this function, leading to insert data with the @ character, then, TSD reported errors.
But I do not understand why?
public static void validateString(final String what, final String s) {
    if (s == null) {
      throw new IllegalArgumentException("Invalid " + what + ": null");
    } else if ("".equals(s)) {
      throw new IllegalArgumentException("Invalid " + what + ": empty string");
    }
    final int n = s.length();
    for (int i = 0; i < n; i++) {
      final char c = s.charAt(i);
      if (!(('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') 
          || ('0' <= c && c <= '9') || c == '-' || c == '_' || c == '.' 
          || c == '/' || Character.isLetter(c))) {
        throw new IllegalArgumentException("Invalid " + what
            + " (\"" + s + "\"): illegal character: " + c);
      }
    }
  }

**Comment by manolama** [comment]
It was a choice made early on to block certain characters to allow for the most flexibility in creating a new query language for the system. However some characters, like the @ are used so often (e.g. emails) that we'll probably start allowing those and not use them in any queries. For now, you can just add ``|| c == '@' `` to that function as other folks have done. If you want to open a PR (with some tests) against the Next branch I'll pull it in. Thanks!

**Comment by ansible-lee** [comment]
Thanks, I will pull it after tested.waiting days.

**Comment by IDerr** [comment]
You can close this @manolama

**Comment by IDerr** [comment]
Hi @ansible-lee,
could you please close this issue if the problem has been resolved ?

Thanks a lot :)

**Comment by paulsson** [comment]
@manolama this issue should be closed.
Anyone looking to support additional characters please see the following source:

variable "allowSpecialCharacters"
https://github.com/OpenTSDB/opentsdb/blob/v2.3.0/src/core/Tags.java#L551

methods setAllowSpecialChars and isAllowSpecialChars
Tags#isAllowSpecialChars is used to validate characters for metric names and tag keys and values.
https://github.com/OpenTSDB/opentsdb/blob/v2.3.0/src/core/Tags.java#L816

Specify additional characters in the configuration setting "tsd.core.tag.allow_specialchars"
https://github.com/OpenTSDB/opentsdb/blob/v2.3.0/src/core/TSDB.java#L234
