### ISSUE TITLE
 GC overhead limit exceeded

### ISSUE THREAD

**Issue by lufenghuan** [OpenTSDB/opentsdb#558]
Hi
Running benchmark on OpenTSDB, keep getting  "GC overhead limit exceeded" and hanging after running my inserting program for while (rate around 500,000 point/second). I am using put REST api. It looks similar to https://github.com/OpenTSDB/opentsdb/issues/557. I think my HBase cluster have enough capacity to hand this insertion rate. 

```
17:29:51.861 ERROR [ConnectionManager.exceptionCaught] - Unexpected exception from downstream for [id: 0x0f39e398, /127.0.0.1:33382 => /127.0.0.1:4242]
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.HashMap.createEntry(HashMap.java:901) ~[na:1.7.0_51]
        at java.util.HashMap.addEntry(HashMap.java:888) ~[na:1.7.0_51]
        at java.util.HashMap.put(HashMap.java:509) ~[na:1.7.0_51]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:458) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:311) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:232) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051) ~[jackson-databind-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2153) ~[jackson-databind-2.4.3.jar:2.4.3]
        at net.opentsdb.utils.JSON.parseToObject(JSON.java:163) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.HttpJsonSerializer.parsePutV1(HttpJsonSerializer.java:144) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.PutDataPointRpc.execute(PutDataPointRpc.java:102) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:273) ~[tsdb-2.1.0.jar:]
        at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:180) ~[tsdb-2.1.0.jar:]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
```

**Comment by manolama** [comment]
Hiya, was that 500k for a single TSD? If so, that's really impressive. Either way, what you'll want to watch for are the "tsd.rpc.errors" metric reported from the /api/stats endpoint. Look for an increase in "hbase_errors" just before the GC happens. That could be caused by regions splitting, causing a queue build up in the TSDs while they wait for the new regions to come online.
In 2.2 and AsyncHBase we'll have better configs around this NSRE queue that let you tune it down and also a plugin handler that will let you queue such data to disk and retry later.

**Comment by lufenghuan** [comment]
Thanks for the quick reply. 

It's two TSD instances on two machine. Right, I saw a spike of tsd.rpc.errors{type=hbase_errores} before the TSD slow down.  If that is caused by region split, will a pre-spilt region help solve this problem?

**Comment by manolama** [comment]
Yep, pre-splitting would definitely help as you shouldn't see the NSREs until a region is full or the server falls over.

**Comment by kramerli** [comment]
@lufenghuan 
Hi 能加一下你的联系方式 一起讨论下这个么

**Comment by lufenghuan** [comment]
@kramerli  HI, You can reach me by lufenghuan@gmail.com

**Comment by IDerr** [comment]
Hi @lufenghuan ,
if your question has been answered, could you close this issue ?

Thanks a lot :)
