### ISSUE TITLE
When insert data, Hit  the error java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by kramerli** [OpenTSDB/opentsdb#559]
Hi

I`m using openTSDB RESTful API to insert data. But I hit below ERROR in opentsdb logs.
I checked the Region Server Log since it said exception from downstream. Did not find any error there.

Can you give some advice on what is going ?
Even better on how to analysis this kind information

```
2015-09-05 02:14:35,148 INFO  [New I/O worker #68] CompactionQueue: Flushing all old outstanding rows out of 19490 rows
2015-09-05 02:14:35,184 INFO  [New I/O worker #68] CompactionQueue: Flushing all old outstanding rows out of 15685 rows
2015-09-05 02:14:35,213 INFO  [New I/O worker #68] CompactionQueue: Flushing all old outstanding rows out of 11139 rows
2015-09-05 02:14:35,583 ERROR [New I/O worker #66] RegionClient: Unexpected exception from downstream on [id: 0x65cb49a8, /10.75.44.35:53089 => /10.75.44.36:18020]
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.7.0_85]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.7.0_85]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.7.0_85]
        at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[na:1.7.0_85]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:492) ~[na:1.7.0_85]
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromSelectorLoop(AbstractNioWorker.java:158) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:114) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
2015-09-05 02:14:35,583 INFO  [New I/O worker #66] HBaseClient: Lost connection with the .META. region
2015-09-05 02:14:35,584 ERROR [New I/O worker #66] RegionClient: After decoding the last message on [id: 0x65cb49a8, /10.75.44.35:53089 :> /10.75.44.36:18020], there was still some undecoded bytes in the channel's buffer (which are going to be lost): ReplayingDecoderBuffer(ridx=4, widx=196)="\x00\x00\x03\xF8\xF6\x07\x08\xF8\xB9\x91l\x12\xEE\x07\n1org.apache.hadoop.hbase.NotServingRegionException\x12\xB6\x07org.apache.hadoop.hbase.NotServingRegionException: Region tsdb,\x00\x02|U\xBB\xA9\x90\x00\x00\x01\x00\x0F\x0E\x00\x00\x02\x00\x1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
2015-09-05 02:14:35,585 INFO  [New I/O worker #66] HBaseClient: Invalidated cache for .META. as null seems to be splitting or closing it.
2015-09-05 02:14:35,598 INFO  [New I/O worker #66] HBaseClient: There are now 500 RPCs pending due to NSRE on "tsdb,\x00\x00XU\xBB\x9B\x80\x00\x00\x01\x00\x01\x81\x00\x00\x02\x00\n?,1441367524212.4dab93e7236f51e78afb43769387ec6f."
2015-09-05 02:14:35,602 INFO  [New I/O worker #66] HBaseClient: There are now 1000 RPCs pending due to NSRE on "tsdb,\x00\x00XU\xBB\x9B\x80\x00\x00\x01\x00\x01\x81\x00\x00\x02\x00\n?,1441367524212.4dab93e7236f51e78afb43769387ec6f."
2015-09-05 02:14:35,607 INFO  [New I/O worker #66] HBaseClient: There are now 1500 RPCs pending due to NSRE on "tsdb,\x00\x00XU\xBB\x9B\x80\x00\x00\x01\x00\x01\x81\x00\x00\x02\x00\n?,1441367524212.4dab93e7236f51e78afb43769387ec6f."
2015-09-05 02:14:35,613 INFO  [New I/O worker #66] HBaseClient: There are now 2000 RPCs pending due to NSRE on "tsdb,\x00\x00XU\xBB\x9B\x80\x00\x00\x01\x00\x01\x81\x00\x00\x02\x00\n?,1441367524212.4dab93e7236f51e78afb43769387ec6f."
```

**Comment by manolama** [comment]
This is a problem with the HBase region server disconnecting the client, likely due to a crash. The specific host that failed as at IP ''10.75.44.36:180'' so take a look at it's logs and see if it indeed restarted.
