### ISSUE TITLE
No enum constant net.opentsdb.uid.UniqueId.UniqueIdType.metrics

### ISSUE THREAD

**Issue by kingmorning** [OpenTSDB/opentsdb#628]
[hadoop@hadoop1 build]$ ./tsdb version
net.opentsdb.tools 2.2.0RC2 built at revision e252139 (MINT)
Built on 2015/11/10 02:25:01 +0000 by hobbes@clhbase:/home/hobbes/opentsdb_OFFICIAL/build
[hadoop@hadoop1 build]$ ./tsdb mkmetric mysql.bytes_received mysql.bytes_sent
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant net.opentsdb.uid.UniqueId.UniqueIdType.metrics
        at java.lang.Enum.valueOf(Enum.java:238)
        at net.opentsdb.uid.UniqueId$UniqueIdType.valueOf(UniqueId.java:59)
        at net.opentsdb.tools.UidManager.assign(UidManager.java:364)
        at net.opentsdb.tools.UidManager.runCommand(UidManager.java:162)
        at net.opentsdb.tools.UidManager.main(UidManager.java:127)
[hadoop@hadoop1 build]$

**Comment by manolama** [comment]
Patched in fb255884470597b3b4e8220b4250d75630099cdb so we should be good for the release.

**Comment by xuyang2** [comment]
To bypass:

    ./tsdb uid assign METRIC mysql.bytes_received mysql.bytes_sent
