### ISSUE TITLE
fsck failing to read points

### ISSUE THREAD

**Issue by eswdd** [OpenTSDB/opentsdb#633]
Running 2.1.1

It successfully reads some (and fixes) and then bombs out with this:
```
   2015-11-20 12:32:02,748 ERROR [main] Fsck: Shouldn't be here
   java.lang.ArrayIndexOutOfBoundsException: 2
        at org.hbase.async.Bytes.getInt(Bytes.java:152) ~[asynchbase-1.6.0.jar:na]
        at net.opentsdb.core.RowSeq.extractFloatingPointValue(RowSeq.java:261) ~[tsdb-2.1.1.jar:]
        at net.opentsdb.core.Internal.extractFloatingPointValue(Internal.java:126) ~[tsdb-2.1.1.jar:]
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:646) ~[tsdb-2.1.1.jar:]
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:310) ~[tsdb-2.1.1.jar:]
        at net.opentsdb.tools.Fsck.runQueries(Fsck.java:194) [tsdb-2.1.1.jar:]
        at net.opentsdb.tools.Fsck.main(Fsck.java:1212) [tsdb-2.1.1.jar:]
```

Ideally even if there were a critical error it could let me know the offending data point coordinates so I have a chance of manually fixing and continue regardless. Unfortunately this causes fsck to exit.

**Comment by manolama** [comment]
eww, that's an ugly one. Could you try out this one please? https://github.com/manolama/opentsdb/tree/i633 Should print out the proper row, then paste that row here please. Thanks!

**Comment by eswdd** [comment]
Bad news - i forgot to output to a file and had debug enabled, which overflowed my console. I reran and captured the output and no log line could be found.

Reran with the original version: no error.

I'll try running a full fsck using 2.1.1 just in case there are some others lurking around.

**Comment by eswdd** [comment]
Right, got it, there were a number of them:

```
14:29:38.107 [main] ERROR net.opentsdb.tools.Fsck - Unexpected exception processing DP: Cell([19, 97], [80, -13])
14:29:38.108 [main] ERROR net.opentsdb.tools.Fsck - Unexpected exception processing DP: Cell([23, 33], [81, 18])
14:29:38.121 [main] ERROR net.opentsdb.tools.Fsck - Unexpected exception processing DP: Cell([82, -31], [83, 59])
14:29:38.128 [main] ERROR net.opentsdb.tools.Fsck - Unexpected exception processing DP: Cell([-124, -95], [85, 6])
14:29:38.136 [main] ERROR net.opentsdb.tools.Fsck - Unexpected exception processing DP: Cell([-98, 97], [85, -19])
14:29:38.156 [main] ERROR net.opentsdb.tools.Fsck - Unexpected exception processing DP: Cell([-54, 113], [87, -126])
14:29:38.158 [main] ERROR net.opentsdb.tools.Fsck - Unexpected exception processing DP: Cell([-47, 97], [87, -50])
```

Immediately after each was some extra info about the deduping (which resolved our issue, presumably by removing the broken data point), here's the data from the first:
``` 
14:29:38.107 [main] INFO  net.opentsdb.tools.Fsck - More than one column had a value for the same timestamp: (1446624310000 - Wed Nov 04 08:05:10 GMT 2015)
    row key: (00363A5639BB000000010094600000190011AF00002300004F00002800E1D700005800C28F)
    write time: (1446624310884)  compacted: (false)  qualifier: [19, 97] <--- keep oldest
    write time: (1446629906062 - Wed Nov 04 09:38:26 GMT 2015)  compacted: (true)  qualifier: [0, -117, 1, 43, 1, -53, 2, 107, 3, 11, 3, -85, 4, 75, 4, -21, 5, -117, 6, 43, 6, -53, 7, 107, 8, 27, 8, -69, 9, 91, 9, -5, 10, -101, 11, 59, 11, -37, 12, 123, 13, 27, 13, -69, 14, 91, 14, -5, 15, -101, 16, 59, 16, -37, 17, -117, 18, 43, 18, -53, 19, 97, 20, 11, 20, -85, 21, 75, 21, -21, 22, -117, 23, 33, 23, -53, 24, 107, 25, 11, 25, -85, 26, 75, 26, -21, 27, -101, 28, 59, 28, -37, 29, 123, 30, 27, 30, -69, 31, 91, 32, -101, 33, 59, 33, -37, 34, 123, 35, 27, 36, 91, 36, -5, 38, 59, 38, 75, 38, -21, 39, -117, 40, -53, 41, 107, 42, 11, 42, -85, 43, 75, 43, -21, 44, -117, 45, -53, 46, 107, 47, 27, 47, -69, 48, 91, 49, -101, 50, 59, 50, -37, 51, 123, 52, 27, 52, -69, 53, 91, 53, -5, 54, -101, 55, 59, 55, -37, 56, -117, 57, 43, 57, -53, 58, 107, 59, 11, 59, -85, 60, 75, 60, -21, 61, -117, 62, 43, 62, -53, 63, 107, 64, 11, 64, -85, 65, 75, 65, -21, 66, -101, 67, 59, 67, -37, 68, 123, 69, 27, 69, -69, 70, 91, 70, -5, 71, -101, 72, 59, 72, -37, 73, 123, 74, 27, 74, -69, 75, 91, 76, 11, 76, -85, 77, 75, 77, -21, 78, -117, 79, 43, 79, -53, 80, 107, 81, 11, 81, -85, 82, 75, 82, -31, 83, -117, 84, 43, 84, -53, 85, 107, 86, 27, 86, -69, 87, 91, 87, -5, 89, 59, 93, -101, 94, 59, 94, -37, 95, 123, 102, 107, 113, -53, 114, 107, 115, 11, 115, -85, 116, 75, 116, -21, 117, -117, 118, 43, 118, -53, 119, 107, 120, -85, 121, 91, 121, -5, 122, -101, 123, 59, 123, -37, 124, 123, 125, 27, 126, 91, 126, -5, 127, -101, -128, 59, -128, -37, -126, 27, -126, -69, -125, -5, -124, 11, -124, -95, -123, -21, -121, 43, -121, -53, -120, 107, -119, -85, -118, 75, -118, -21, -117, -117, -116, 43, -116, -37, -115, 123, -114, 27, -114, -69, -113, 91, -113, -5, -112, -101, -111, 59, -111, -37, -110, 123, -109, 27, -109, -69, -108, 91, -108, -5, -107, -101, -106, 59, -106, -21, -105, -117, -104, 43, -104, -53, -103, 107, -102, 11, -102, -85, -101, 75, -101, -21, -100, -117, -99, 43, -99, -53, -98, 97, -97, 11, -97, -85, -96, 91, -96, -5, -95, -101, -94, 59, -94, -37, -93, 123, -92, 27, -92, -69, -91, -5, -90, -101, -89, 59, -89, -37, -88, 123, -87, 27, -87, -69, -86, 107, -85, 11, -85, -85, -84, 75, -84, -21, -83, -117, -82, 43, -82, -53, -81, 107, -80, 11, -80, -85, -79, 75, -79, -21, -78, -117, -77, 43, -77, -53, -76, 123, -75, 27, -75, -69, -74, 91, -74, -5, -73, -101, -72, 59, -72, -37, -71, 123, -70, 27, -70, -69, -69, 91, -69, -5, -68, -101, -67, 59, -67, -21, -66, -117, -65, 43, -65, -53, -64, 107, -63, 11, -63, -85, -62, 75, -62, -21, -61, -117, -60, 43, -60, -53, -59, 107, -58, 11, -58, -85, -57, 91, -57, -5, -56, -101, -55, 59, -55, -37, -54, 113, -53, 27, -53, -69, -52, 91, -52, -5, -51, -101, -50, 59, -50, -37, -49, 123, -48, 27, -48, -53, -47, 97, -46, 11, -46, -85, -43, 43, -43, -53, -42, 107, -41, 11, -41, -85, -40, 75, -40, -5, -39, -101, -38, 59, -38, -37, -37, 123, -36, 27, -36, -69, -35, -5, -34, -101, -33, -37, -32, 123] value: 
```

**Comment by manolama** [comment]
Hmm, were those ``Unexpected exception processing DP:`` from 2.1.1? I couldn't find the log line in the source anywhere... Was there a stack trace associated with those lines? thanks!

**Comment by eswdd** [comment]
No, i patched your fsck change from your i633 branch into our
tsdb-2.1.1.jar to get that. No exception, although when i ran unpatched
before i got the same exception as in the original report.

**Comment by manolama** [comment]
Kay, back on OS. The last paste with the "More than one column had a value..." was missing the value byte array. could you dig that up and paste it please?

**Comment by eswdd** [comment]
hiya,
sorry for the delay, that's all there was in the log, the value byte array was not printed. the next line in that log is:
```
14:29:38.107 [main] INFO  net.opentsdb.tools.Fsck - More than one column had a value for the same timestamp: (1446624320000 - Wed Nov 04 08:05:20 GMT 2015)
    row key: (00363A5639BB000000010094600000190011AF00002300004F00002800E1D700005800C28F)
    write time: (1446624320486)  compacted: (false)  qualifier: [20, 11] <--- keep oldest
    write time: (1446629906062 - Wed Nov 04 09:38:26 GMT 2015)  compacted: (true)  qualifier: [0, -117, 1, 43, 1, -53, 2, 107, 3, 11, 3, -85, 4, 75, 4, -21, 5, -117, 6, 43, 6, -53, 7, 107, 8, 27, 8, -69, 9, 91, 9, -5, 10, -101, 11, 59, 11, -37, 12, 123, 13, 27, 13, -69, 14, 91, 14, -5, 15, -101, 16, 59, 16, -37, 17, -117, 18, 43, 18, -53, 19, 97, 20, 11, 20, -85, 21, 75, 21, -21, 22, -117, 23, 33, 23, -53, 24, 107, 25, 11, 25, -85, 26, 75, 26, -21, 27, -101, 28, 59, 28, -37, 29, 123, 30, 27, 30, -69, 31, 91, 32, -101, 33, 59, 33, -37, 34, 123, 35, 27, 36, 91, 36, -5, 38, 59, 38, 75, 38, -21, 39, -117, 40, -53, 41, 107, 42, 11, 42, -85, 43, 75, 43, -21, 44, -117, 45, -53, 46, 107, 47, 27, 47, -69, 48, 91, 49, -101, 50, 59, 50, -37, 51, 123, 52, 27, 52, -69, 53, 91, 53, -5, 54, -101, 55, 59, 55, -37, 56, -117, 57, 43, 57, -53, 58, 107, 59, 11, 59, -85, 60, 75, 60, -21, 61, -117, 62, 43, 62, -53, 63, 107, 64, 11, 64, -85, 65, 75, 65, -21, 66, -101, 67, 59, 67, -37, 68, 123, 69, 27, 69, -69, 70, 91, 70, -5, 71, -101, 72, 59, 72, -37, 73, 123, 74, 27, 74, -69, 75, 91, 76, 11, 76, -85, 77, 75, 77, -21, 78, -117, 79, 43, 79, -53, 80, 107, 81, 11, 81, -85, 82, 75, 82, -31, 83, -117, 84, 43, 84, -53, 85, 107, 86, 27, 86, -69, 87, 91, 87, -5, 89, 59, 93, -101, 94, 59, 94, -37, 95, 123, 102, 107, 113, -53, 114, 107, 115, 11, 115, -85, 116, 75, 116, -21, 117, -117, 118, 43, 118, -53, 119, 107, 120, -85, 121, 91, 121, -5, 122, -101, 123, 59, 123, -37, 124, 123, 125, 27, 126, 91, 126, -5, 127, -101, -128, 59, -128, -37, -126, 27, -126, -69, -125, -5, -124, 11, -124, -95, -123, -21, -121, 43, -121, -53, -120, 107, -119, -85, -118, 75, -118, -21, -117, -117, -116, 43, -116, -37, -115, 123, -114, 27, -114, -69, -113, 91, -113, -5, -112, -101, -111, 59, -111, -37, -110, 123, -109, 27, -109, -69, -108, 91, -108, -5, -107, -101, -106, 59, -106, -21, -105, -117, -104, 43, -104, -53, -103, 107, -102, 11, -102, -85, -101, 75, -101, -21, -100, -117, -99, 43, -99, -53, -98, 97, -97, 11, -97, -85, -96, 91, -96, -5, -95, -101, -94, 59, -94, -37, -93, 123, -92, 27, -92, -69, -91, -5, -90, -101, -89, 59, -89, -37, -88, 123, -87, 27, -87, -69, -86, 107, -85, 11, -85, -85, -84, 75, -84, -21, -83, -117, -82, 43, -82, -53, -81, 107, -80, 11, -80, -85, -79, 75, -79, -21, -78, -117, -77, 43, -77, -53, -76, 123, -75, 27, -75, -69, -74, 91, -74, -5, -73, -101, -72, 59, -72, -37, -71, 123, -70, 27, -70, -69, -69, 91, -69, -5, -68, -101, -67, 59, -67, -21, -66, -117, -65, 43, -65, -53, -64, 107, -63, 11, -63, -85, -62, 75, -62, -21, -61, -117, -60, 43, -60, -53, -59, 107, -58, 11, -58, -85, -57, 91, -57, -5, -56, -101, -55, 59, -55, -37, -54, 113, -53, 27, -53, -69, -52, 91, -52, -5, -51, -101, -50, 59, -50, -37, -49, 123, -48, 27, -48, -53, -47, 97, -46, 11, -46, -85, -43, 43, -43, -53, -42, 107, -41, 11, -41, -85, -40, 75, -40, -5, -39, -101, -38, 59, -38, -37, -37, 123, -36, 27, -36, -69, -35, -5, -34, -101, -33, -37, -32, 123] value: 20730.369140625
```

Looking at the other unexpected exception messages, they're all followed by a "More than one column message" with a missing value byte array, followed by another with a value.

**Comment by eswdd** [comment]
Hi,

Unfortunately there's no more info in our logs for this, and the issue hasn't happened again. I wonder if it's worth merging the change on this branch to next anyway in case this kind of issue pops up again to prevent fsck just stopping dead?

Simon

**Comment by manolama** [comment]
Yeah, I'll go ahead and add that change to the "next" branch so we can catch it. Thanks!

**Comment by manolama** [comment]
Added in 53dd48645c63ea256f99a15de937c03be8b24ea8. Reopen this if you see it again please :)

**Comment by eswdd** [comment]
Will do, thanks
