### ISSUE TITLE
Opentsdb fsck command throws an error

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#637]
When I run the following command, which is mentioned in the Opentsdb docs (http://opentsdb.net/docs/build/html/user_guide/cli/fsck.html):

```
fsck --full-scan --threads=8 --fix --resolve-duplicates --compact
```
I get the following error:
```
2015-11-24 02:42:49,642 INFO  [AsyncHBase I/O Worker #1] HBaseClient: Added client for region RegionInfo(table="tsdb", region_name="tsdb,\x00\x01eVOQ\x90\x00\x00\x01\x00\x00\x01\x00\x00\x02\x00\x00\x02\x00\x00\x03\x00\x00\x03\x00\x00\x04\x00\x00\x04\x00\x00\x05\x00\x01o,1448160924037.784a4f3906b6cf88b0d6b1f028fa5d77.", stop_key=""), which was added to the regions cache.  Now we know that RegionClient@1494633745(chan=[id: 0xf32e5ba5, /10.241.62.144:47640 => /10.241.63.150:60020], #pending_rpcs=0, #batched=0, #rpcs_inflight=0) is hosting 2 regions.
2015-11-24 02:42:49,692 ERROR [Fsck #1] Fsck: Shouldn't be here
java.lang.RuntimeException: Shouldn't be here
	at net.opentsdb.core.Tags.resolveIds(Tags.java:678) ~[tsdb-2.2.0RC3.jar:]
	at net.opentsdb.tools.Fsck$FsckWorker.fsckKey(Fsck.java:523) ~[tsdb-2.2.0RC3.jar:]
	at net.opentsdb.tools.Fsck$FsckWorker.fsckRow(Fsck.java:334) ~[tsdb-2.2.0RC3.jar:]
	at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:302) ~[tsdb-2.2.0RC3.jar:]
com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
	at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.DeferredGroup.access$200(DeferredGroup.java:36) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.DeferredGroup$1NotifyOrdered.call(DeferredGroup.java:97) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na]
	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:698) ~[asynchbase-1.7.1-20151004.015637-1.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1516) ~[asynchbase-1.7.1-20151004.015637-1.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.1-20151004.015637-1.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1206) ~[asynchbase-1.7.1-20151004.015637-1.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3108) ~[asynchbase-1.7.1-20151004.015637-1.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_51]
Caused by: java.lang.IllegalStateException: name=i-3f6a168d => id=[0, 4, 24], already mapped to [0, 4, 25]
	at net.opentsdb.uid.UniqueId.addIdToCache(UniqueId.java:349) ~[tsdb-2.2.0RC3.jar:]
	at net.opentsdb.uid.UniqueId.access$100(UniqueId.java:55) ~[tsdb-2.2.0RC3.jar:]
	at net.opentsdb.uid.UniqueId$1GetNameCB.call(UniqueId.java:263) ~[tsdb-2.2.0RC3.jar:]
	at net.opentsdb.uid.UniqueId$1GetNameCB.call(UniqueId.java:257) ~[tsdb-2.2.0RC3.jar:]
	... 34 common frames omitted
2015-11-24 02:42:49,693 INFO  [main] Fsck: Thread [Thread[Fsck #1,5,]] Finished
2015-11-24 02:42:53,633 INFO  [Progress] Fsck: Processed 10000 rows, 203189 valid datapoints
```

**Comment by manolama** [comment]
That's expected. Try running the UID fsck utility to fix the issue in 
```
Caused by: java.lang.IllegalStateException: name=i-3f6a168d => id=[0, 4, 24], already mapped to [0, 4, 25]
    at net.opentsdb.uid.UniqueId.addIdToCache(UniqueId.java:349) ~[tsdb-2.2.0RC3.jar:]
    at net.opentsdb.uid.UniqueId.access$100(UniqueId.java:55) ~[tsdb-2.2.0RC3.jar:]
    at net.opentsdb.uid.UniqueId$1GetNameCB.call(UniqueId.java:263) ~[tsdb-2.2.0RC3.jar:]
    at net.opentsdb.uid.UniqueId$1GetNameCB.call(UniqueId.java:257) ~[tsdb-2.2.0RC3.jar:]
    ... 34 common frames omitted
```

http://opentsdb.net/docs/build/html/user_guide/cli/uid.html#fsck
