### ISSUE TITLE
Duplicate datapoints and ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by floyd-may** [OpenTSDB/opentsdb#653]
I'm noticing lots of duplicate datapoints with not much data volume. I wouldn't have noticed it, except I started getting failing queries. I attempted to use fsck to fix the errors with little success. I made the config change recommended in #430, which restored query functionality; however, running a full scan using fsck since then shows ~30k duplicate data point errors, where my attempts using fsck were only showing a max of 400 or so. I'm also noticing this exception stack trace from fsck, which may or may not be related:

```
java.lang.ArrayIndexOutOfBoundsException: 2
        at org.hbase.async.Bytes.getInt(Bytes.java:152) ~[asynchbase-1.6.0.jar:na]
        at net.opentsdb.core.RowSeq.extractIntegerValue(RowSeq.java:238)
        at net.opentsdb.core.Internal.extractIntegerValue(Internal.java:119)
        at net.opentsdb.tools.Fsck$FsckWorker.fsckDataPoints(Fsck.java:646)
        at net.opentsdb.tools.Fsck$FsckWorker.run(Fsck.java:310)
```

I'm on version 2.1.1.

**Comment by manolama** [comment]
Hmm, are TSD compactions enabled on your host? For fun could you turn them off for a bit and see if the duplicates continue? Also please try running fsck with https://github.com/manolama/opentsdb/commits/i633 and paste the output.

**Comment by floyd-may** [comment]
I managed to get the total number of duplicates down to a much less daunting ~300 by grabbing *all* the metric names and passing them to `fsck` one at a time. I'll try turning off compactions and report back. For now, things seem stable, but this caught me by surprise and broke my queries temporarily. Perhaps the default config should have `tsd.storage.fix_duplicates = true`?

I'll also see what i can do to compile `i633` and get some details to you. Thanks for the help.

**Comment by manolama** [comment]
> Perhaps the default config should have ''tsd.storage.fix_duplicates = true''?

Yeah, I'd like to enable it by default in another version or two, for 2.2 I didn't want any surprises. Thanks!
