### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/zookeeper/Watcher

### ISSUE THREAD

**Issue by bobrik** [OpenTSDB/opentsdb#704]
```
Exception in thread "main" java.lang.RuntimeException: Initialization failed
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:196)
Caused by: java.lang.NoClassDefFoundError: org/apache/zookeeper/Watcher
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.hbase.async.HBaseClient.<init>(HBaseClient.java:596)
	at org.hbase.async.HBaseClient.<init>(HBaseClient.java:557)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:150)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:220)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:150)
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.Watcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
```

https://github.com/cloudflare/docker-opentsdb/pull/5

Difference between 2.2.0RC3 and 2.2.0 packages:

```
$ diff -rup <(dpkg -c Downloads/opentsdb-2.2.0RC3_all.deb | awk '{ print $NF }' | sort -n | fgrep .jar) <(dpkg -c Downloads/opentsdb-2.2.0_all.deb | awk '{ print $NF }' | sort -n | fgrep .jar)
--- /dev/fd/63	2016-02-15 17:16:51.000000000 -0800
+++ /dev/fd/62	2016-02-15 17:16:51.000000000 -0800
@@ -1,5 +1,5 @@
 ./usr/share/opentsdb/lib/async-1.4.0.jar
-./usr/share/opentsdb/lib/asynchbase-1.7.1-20151004.015637-1.jar
+./usr/share/opentsdb/lib/asynchbase-1.7.1.jar
 ./usr/share/opentsdb/lib/commons-math3-3.4.1.jar
 ./usr/share/opentsdb/lib/guava-18.0.jar
 ./usr/share/opentsdb/lib/jackson-annotations-2.4.3.jar
@@ -11,5 +11,4 @@
 ./usr/share/opentsdb/lib/netty-3.9.4.Final.jar
 ./usr/share/opentsdb/lib/protobuf-java-2.5.0.jar
 ./usr/share/opentsdb/lib/slf4j-api-1.7.7.jar
-./usr/share/opentsdb/lib/tsdb-2.2.0RC3.jar
-./usr/share/opentsdb/lib/zookeeper-3.3.6.jar
+./usr/share/opentsdb/lib/tsdb-2.2.0.jar
```

Zookeeper jar is missing.

**Comment by ccl0326** [comment]
I have same problem.

**Comment by manolama** [comment]
That's odd, I'll get it fixed up here.

**Comment by manolama** [comment]
OK, found the issue in that I accidentally checked in the ZK jar in the root third_party dir and that prevented it being copied to the build dir. Fixed and updated the debian and tar files in the release. The RPM package was ok. Give it a try and let me know if it's ok for you.

**Comment by bobrik** [comment]
Thanks, that did it!

**Comment by chuy08** [comment]
Still seems to be a problem in the source package.
