### ISSUE TITLE
Sum of distinct time stamp data point values 

### ISSUE THREAD

**Issue by mahendrashri09** [OpenTSDB/opentsdb#734]
Hi,

Please let me know if we can add  all the values of a metric for a given time interval (not at a given timestamp) ? 

For example a query results the following -

apache.hits 1458119588000 **300** {}
apache.hits 1458120081000 **1098** {}
apache.hits 1458120082000 **1500** {}
apache.hits 1458120164000 **300** {}
apache.hits 1458120182000 **300** {}
apache.hits 1458120183000 **350** {}
apache.hits 1458120184000 **450** {}
apache.hits 1458120185000 **600** {}
apache.hits 1458120186000 **750** {}
apache.hits 1458120187000 **900** {}
apache.hits 1458120188000 **1050** {}
apache.hits 1458120189000 **1200** {}
apache.hits 1458120190000 **1350** {}
apache.hits 1458120191000 **950** {}
apache.hits 1458120192000 **500** {}

I want to add all values regardless the timestamp to get a total number of hits in this time interval. 

Thanks

**Comment by johann8384** [comment]
Using the SUM downsampler would do this for you. If you wanted to get all the hits per hour you could use a downsample of 1h-sum

**Comment by johann8384** [comment]
Downsampling is dicussed here: http://opentsdb.net/docs/build/html/user_guide/query/index.html

**Comment by johann8384** [comment]
You may also have better luck sending questions here: https://groups.google.com/forum/#!forum/opentsdb I suspect more people read the list than browse the issue tracker.

**Comment by mahendrashri09** [comment]
Thank you so much Johann.

**Comment by mahendrashri09** [comment]
GUI it works fine. But command line if I am trying, it's showing error. I tried following different ways - 

]# /usr/local/share/opentsdb/bin/tsdb query  2016/02/01-00:00:00 2016/03/18-00:00:00 s**um apache.hits 1h-sum**  --zkbasedir=/hbase
Exception in thread "main" java.util.NoSuchElementException: No such aggregator: 1h-sum
        at net.opentsdb.core.Aggregators.get(Aggregators.java:180)
        at net.opentsdb.tools.CliQuery.parseCommandLineQuery(CliQuery.java:200)
        at net.opentsdb.tools.CliQuery.doQuery(CliQuery.java:111)
        at net.opentsdb.tools.CliQuery.main(CliQuery.java:84)

]# /usr/local/share/opentsdb/bin/tsdb query  2016/02/01-00:00:00 2016/03/18-00:00:00 sum **apache.hits 1h-sum-none**  --zkbasedir=/hbase
Exception in thread "main" java.util.NoSuchElementException: No such aggregator: 1h-sum-none
        at net.opentsdb.core.Aggregators.get(Aggregators.java:180)
        at net.opentsdb.tools.CliQuery.parseCommandLineQuery(CliQuery.java:200)
        at net.opentsdb.tools.CliQuery.doQuery(CliQuery.java:111)
        at net.opentsdb.tools.CliQuery.main(CliQuery.java:84)

]# /usr/local/share/opentsdb/bin/tsdb query  2016/02/01-00:00:00 2016/03/18-00:00:00 **sum:10m-sum-none:apache.hits**  --zkbasedir=/hbase          Exception in thread "main" java.util.NoSuchElementException: No such aggregator: 2016/03/18-00:00:00
        at net.opentsdb.core.Aggregators.get(Aggregators.java:180)
        at net.opentsdb.tools.CliQuery.parseCommandLineQuery(CliQuery.java:200)
        at net.opentsdb.tools.CliQuery.doQuery(CliQuery.java:111)
        at net.opentsdb.tools.CliQuery.main(CliQuery.java:84)


]# /usr/local/share/opentsdb/bin/tsdb query  2016/02/01-00:00:00 2016/03/18-00:00:00 **10m-sum-none apache.hits**  --zkbasedir=/hbase
Exception in thread "main" java.util.NoSuchElementException: No such aggregator: 10m-sum-none
        at net.opentsdb.core.Aggregators.get(Aggregators.java:180)
        at net.opentsdb.tools.CliQuery.parseCommandLineQuery(CliQuery.java:200)
        at net.opentsdb.tools.CliQuery.doQuery(CliQuery.java:111)
        at net.opentsdb.tools.CliQuery.main(CliQuery.java:84)

 ~]# /usr/local/share/opentsdb/bin/tsdb query 2016/02/01-00:00:00 2016/03/18-00:00:00 **sum apache.hits **--zkbasedir=/hbase downsample 300000 sum
Exception in thread "main" java.util.NoSuchElementException: No such aggregator: downsample
        at net.opentsdb.core.Aggregators.get(Aggregators.java:180)
        at net.opentsdb.tools.CliQuery.parseCommandLineQuery(CliQuery.java:200)
        at net.opentsdb.tools.CliQuery.doQuery(CliQuery.java:111)
        at net.opentsdb.tools.CliQuery.main(CliQuery.java:84)


Please assist me with the right query format.


Thanks
