### ISSUE TITLE
Unable to run OpenTSDB with BigTable

### ISSUE THREAD

**Issue by dilipdevaraj-sfdc** [OpenTSDB/opentsdb#765]
Based on documentation for big table backend I cloned project https://github.com/pythian/opentsdb/tree/bigtable , instead of https://github.com/OpenTSDB/opentsdb/tree/next since I could not find  build-bigtable.sh
Let me know if that is fine.

So I then build the TSD and am trying to run it against BigTable in Google Cloud. The TSD fails to startup with following error i in ssl handshake. I have rechecked my configurations. I am suing Java 1.8 and BigTable 1.1 client connector. Please let me know if I am missing anything ?
--------------------------------------
2016-04-09 00:43:19,551 INFO  [main] TSDMain: Starting.
2016-04-09 00:43:19,560 INFO  [main] TSDMain: net.opentsdb.tools 2.2.0 built at revision 7746235 (MINT)
2016-04-09 00:43:19,560 INFO  [main] TSDMain: Built on 2016/04/08 23:29:40 +0000 by ddevaraj@ddevaraj-wsl2:/home/ddevaraj/opentsdb/build
2016-04-09 00:43:19,563 INFO  [main] Config: Successfully loaded configuration file: /home/ddevaraj/opentsdb/opentsdb.conf
2016-04-09 00:43:19,606 INFO  [main] Config: Successfully loaded configuration file: /home/ddevaraj/opentsdb/opentsdb.conf
2016-04-09 00:43:19,903 INFO  [main] HBaseClient: BigTable API: Connecting with config: Configuration: core-default.xml, core-site.xml, hbase-default.xml, hbase-site.xml
2016-04-09 00:43:20,228 WARN  [main] NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-04-09 00:43:20,467 INFO  [main] BigtableSession: Opening connection for projectId coherent-brand-127220, zoneId us-central1-b, clusterId argus-bigtable, on data host bigtable.googleapis.com, table admin host bigtabletableadmin.googleapis.com.
2016-04-09 00:43:20,508 INFO  [BigtableSession-startup-0] BigtableSession: gRPC is using the JDK provider (alpn-boot jar)
2016-04-09 00:43:20,898 INFO  [Credentials-Refresh-0] RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
2016-04-09 00:43:21,235 WARN  [main] PluginLoader: Unable to locate any plugins of the type: net.opentsdb.query.filter.TagVFilter
Exception in thread "Credentials-Refresh-0" java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshaker.localSupportedSignAlgs from class sun.security.ssl.ClientHandshaker
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:281)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.bigtable.repackaged.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.bigtable.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.bigtable.repackaged.com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:225)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:286)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2CredentialsInterceptor.java:256)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$1.run(RefreshingOAuth2CredentialsInterceptor.java:184)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
----------------------------------------------------

**Comment by gansvv** [comment]
You need to use opentsdb v2.3 for BigTable support.

On April 8, 2016, at 5:53 PM, dilipdevaraj-sfdc <notifications@github.com> wrote:

Based on documentation for big table backend I cloned project https://github.com/pythian/opentsdb/tree/bigtable , instead of https://github.com/OpenTSDB/opentsdb/tree/next since I could not find build-bigtable.sh
Let me know if that is fine.

So I then build the TSD and am trying to run it against BigTable in Google Cloud. The TSD fails to startup with following error i in ssl handshake. I have rechecked my configurations. I am suing Java 1.8 and BigTable 1.1 client connector. Please let me know if I am missing anything ?

2016-04-09 00:43:19,551 INFO [main] TSDMain: Starting.
2016-04-09 00:43:19,560 INFO [main] TSDMain: net.opentsdb.tools 2.2.0 built at revision 7746235 (MINT)
2016-04-09 00:43:19,560 INFO [main] TSDMain: Built on 2016/04/08 23:29:40 +0000 by ddevaraj@ddevaraj-wsl2:/home/ddevaraj/opentsdb/build
2016-04-09 00:43:19,563 INFO [main] Config: Successfully loaded configuration file: /home/ddevaraj/opentsdb/opentsdb.conf
2016-04-09 00:43:19,606 INFO [main] Config: Successfully loaded configuration file: /home/ddevaraj/opentsdb/opentsdb.conf
2016-04-09 00:43:19,903 INFO [main] HBaseClient: BigTable API: Connecting with config: Configuration: core-default.xml, core-site.xml, hbase-default.xml, hbase-site.xml
2016-04-09 00:43:20,228 WARN [main] NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-04-09 00:43:20,467 INFO [main] BigtableSession: Opening connection for projectId coherent-brand-127220, zoneId us-central1-b, clusterId argus-bigtable, on data host bigtable.googleapis.com, table admin host bigtabletableadmin.googleapis.com.
2016-04-09 00:43:20,508 INFO [BigtableSession-startup-0] BigtableSession: gRPC is using the JDK provider (alpn-boot jar)
2016-04-09 00:43:20,898 INFO [Credentials-Refresh-0] RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
2016-04-09 00:43:21,235 WARN [main] PluginLoader: Unable to locate any plugins of the type: net.opentsdb.query.filter.TagVFilter
Exception in thread "Credentials-Refresh-0" java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshaker.localSupportedSignAlgs from class sun.security.ssl.ClientHandshaker
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:281)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
at com.google.bigtable.repackaged.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
at com.google.bigtable.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
at com.google.bigtable.repackaged.com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:225)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:286)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2CredentialsInterceptor.java:256)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$1.run(RefreshingOAuth2CredentialsInterceptor.java:184)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

**Comment by dilipdevaraj-sfdc** [comment]
Can you let me know from where I can download OpenTSDB v2.3 for BigTable support ?  I am currently using this version https://github.com/OpenTSDB/opentsdb/tree/next since there is no official v2.3
Also can you point me to the right procedure for building and running OpenTSDB against BigTable. I am currently referring to http://opentsdb.net/docs/build/html/user_guide/backends/bigtable.html#setup

**Comment by johann8384** [comment]
The next branch, which you referenced, is the right place.

**Comment by johann8384** [comment]
I will have to do some research to identify the issue you are having, I
will try to get to a place where I can do that later tonight.

**Comment by manolama** [comment]
hi @dilipdevaraj-sfdc, the error you're seeing looks like an ALPN missmatch version. Try syncing your "next" branch and run the bigtable build again. If it still fails, run a ``java -version`` and let us know which ALPN version was pulled in.

**Comment by dilipdevaraj-sfdc** [comment]
Thanks. I synced the latest next branch and rebuilt with latest Java version of 1.8. It works now.
