### ISSUE TITLE
Problems after upgrading to hbase-1.2 with REGION_REPLICATION=3 on tsdb table

### ISSUE THREAD

**Issue by vitaliyf** [OpenTSDB/opentsdb#772]
We were running OpenTSDB 2.1 on Cloudera's CDH5.5.x (hbase-1.0.x) and enabled REGION_REPLICATION=3 on "tsdb" table a month ago. That seemed to work and lessened impact of region failover during RegionServer restarts.

After upgrade to CDH5.7 (with hbase-1.2) we started seeing strange problems. Incoming data is inserted correctly, but a few minutes after OpenTSDB is restarted it stops serving HTTP responses - requests just hang. This affects both built-in UI, Grafana and check_tsd.py

I've tried a few things to figure out what's happening and haven't been able to pinpoint it. Simply restarting opentsdb process makes reads work again for 5-10 more minutes.

Finally, ended up changing REGION_REPLICATION back to "1" and all problems disappeared.

Does OpenTSDB/AsyncHBase need code changes to better handle reading from timeline-consistent replicas? https://issues.apache.org/jira/browse/HBASE-10070 and http://www.cloudera.com/documentation/enterprise/latest/topics/admin_hbase_read_replicas.html have some documentation on this feature.

**Comment by johann8384** [comment]
Would it be possible for you to try the code from the "next" branch just to make sure it hasn't been worked out already?

I have no specific reason to believe it has, but it is worth checking.

**Comment by vitaliyf** [comment]
I will try, though I don't have a great environment to do this since I can't disrupt our production setup more than it has been disrupted this week already. Also, we've been holding out on upgrading to 2.2 or newer due to #697.

I should have mentioned that I did update asynchbase jar from 1.6.0 to 1.7.1 and that didn't make any difference.

**Comment by johann8384** [comment]
I don't believe #697 is an actual issue.

**Comment by johann8384** [comment]
Adding the bug label for now, it may be an enhancement/feature_request though.

**Comment by vitaliyf** [comment]
Confirmed that this problem disappeared after upgrade to OpenTSDB v2.2.0

We are seeing occasional errors like below, but I haven't dug into it to troubleshoot yet. That's probably off-topic for this ticket though any suggestions are appreciated.

```
	org.hbase.async.RemoteException: Call queue is full on /10.20.30.40:60020, too many items queued ?

	at org.hbase.async.RegionClient.makeException(RegionClient.java:1738) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.RegionClient.decodeException(RegionClient.java:1756) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1468) ~[asynchbase-1.7.1.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.1.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1206) ~[asynchbase-1.7.1.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3108) ~[asynchbase-1.7.1.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
```
