### ISSUE TITLE
NPE in formatErrorV1 when using filters in 2.3.0 RC1

### ISSUE THREAD

**Issue by amalshah** [OpenTSDB/opentsdb#798]
I'm using OpenTSDB 2.3.0 RC1.
With the following query:
{"start":1449531887000,
 "queries": [{"metric":"mymetric","aggregator":"sum","downsample":"5m-avg-null","filters":[{"type":"wildcard","tagk":"mytagname","filter":"*","groupBy":false}]}],
  "msResolution":false,
  "globalAnnotations":true,
  "end":1449877487000
}
I see the following exception, with the request hanging:
18:24:24.676 ERROR [QueryRpc.call] - Exception thrown during exception handling
java.lang.NullPointerException: null
        at net.opentsdb.tsd.HttpSerializer.formatErrorV1(HttpSerializer.java:835) ~[tsdb-2.3.0-RC1.jar:]
        at net.opentsdb.tsd.HttpQuery.badRequest(HttpQuery.java:413) ~[tsdb-2.3.0-RC1.jar:]
        at net.opentsdb.tsd.QueryRpc$1ErrorCB.call(QueryRpc.java:212) [tsdb-2.3.0-RC1.jar:]
        at net.opentsdb.tsd.QueryRpc$1ErrorCB.call(QueryRpc.java:172) [tsdb-2.3.0-RC1.jar:]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1313) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1284) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1313) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1284) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.access$300(Deferred.java:430) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:698) [asynchbase-1.7.1.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1516) [asynchbase-1.7.1.jar:na]

I pointed the new 2.3.0 RC1 install at an existing 2.2.0 HBase repository that was functional. In general puts and non-filtered queries work.

Let me know if I can provide more information.

Thanks.

**Comment by amalshah** [comment]
Sorry, duplicate of #794 2.3.0RC1 Query where all filters have groupBy parameter set to false fail without a response
