### ISSUE TITLE
options.bad_percent in tools/check_tsd

### ISSUE THREAD

**Issue by davidone** [OpenTSDB/opentsdb#800]
Tried to use check_tsd on a FreeBSD 10.3 and I had:
```
root@srv1:/usr/ports/databases/opentsdb/work/opentsdb-2.2.0/tools # ./check_tsd -H 127.0.0.1 -p 4242 -m exec.volume.counter -w 400 -c 50
0
Traceback (most recent call last):                                                                                                      
  File "./check_tsd", line 258, in <module>                                                                                             
    sys.exit(main(sys.argv))
  File "./check_tsd", line 231, in main                                                                                                 
    if options.bad_percent is not None and rv > 0 \
AttributeError: Values instance has no attribute 'bad_percent'                                                                          
```

Removing https://github.com/OpenTSDB/opentsdb/blob/master/tools/check_tsd#L231-L236 fixed the error.

**Comment by johann8384** [comment]
Fixed in #779
