### ISSUE TITLE
Error after processing uid metasyns

### ISSUE THREAD

**Issue by aastahov** [OpenTSDB/opentsdb#806]
Our OpenTSDB instance had this error recently:

> 2016-06-02 16:56:35,453 ERROR [New I/O worker #1] HttpQuery: [id: 0x10c757b3, /127.0.0.1:47944 => /127.0.0.1:4242] Internal Server Error on /api/put?details
> java.lang.IllegalStateException: Should never happen!
>         at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:361) ~[tsdb-2.1.0.jar:248fee6]
>         at net.opentsdb.uid.UniqueId$UniqueIdAllocator.tryAllocate(UniqueId.java:353) ~[tsdb-2.1.0.jar:248fee6]
>         at net.opentsdb.uid.UniqueId$UniqueIdAllocator.createForwardMapping(UniqueId.java:480) ~[tsdb-2.1.0.jar:248fee6]
>         at net.opentsdb.uid.UniqueId$UniqueIdAllocator.call(UniqueId.java:399) ~[tsdb-2.1.0.jar:248fee6]
>         at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
>         at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
>         at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na]
>         at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:506) ~[asynchbase-1.6.0.jar:na]
>         at org.hbase.async.RegionClient.decode(RegionClient.java:1351) ~[asynchbase-1.6.0.jar:na]
>         at org.hbase.async.RegionClient.decode(RegionClient.java:89) ~[asynchbase-1.6.0.jar:na]
>         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]
>         at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1082) ~[asynchbase-1.6.0.jar:na]
>         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]
>         at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:2677) ~[asynchbase-1.6.0.jar:na]
>         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
>         at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
>         at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
> 2016-06-02 16:56:35,453 INFO  [New I/O worker #9] HBaseClient: Lost connection with the -ROOT- region

After the process restart error has gone. Metasync was perfomed with below settings:

> tsd.core.meta.enable_realtime_uid = true
> tsd.core.meta.enable_tsuid_incrementing = true

**Comment by johann8384** [comment]
Do you have any ERROR messages in HBase, HDFS and ZooKeeper? This sounds more like an HBase issue than a metasync issue, at least on the surface.

**Comment by aastahov** [comment]
Can't say about HDFS and ZooKeeper, but there wasn't any ERROR messages in HBASE logfile.
