### ISSUE TITLE
Some queries cause a StackOverflow with a large stack of async.Deferred

### ISSUE THREAD

**Issue by katameru** [OpenTSDB/opentsdb#812]
Thu Jun 16 13:26:58 GMT+200 2016    INFO    OpenTSDB I/O Worker #2  tsd.HttpQuery
[id: 0xda4091e2, /10.10.52.32:33764 => /10.10.34.13:4242] HTTP /logs?json done in 10ms
Thu Jun 16 13:26:57 GMT+200 2016    ERROR   AsyncHBase I/O Worker #12   async.RegionClient
Unexpected exception from downstream on [id: 0x9b8af4de, /10.10.34.13:40230 :> /10.10.34.35:60020]  java.lang.StackOverflowError: null
    at com.stumbleupon.async.Deferred.access$300(Deferred.java:430) ~[async-1.4.0.jar:na]
    at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366) ~[async-1.4.0.jar:na]
    at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
    at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]
    at com.stumbleupon.async.Deferred.access$300(Deferred.java:430) ~[async-1.4.0.jar:na]
... snip ...

pastebin of logs: http://pastebin.com/asvHWetP

In my sample i sent two queries via /api/query and got an error in response. When I send only one query, I get a response with data, but the error still happens and is logged.

Version 2.2.0
Edit: I compiled the branch 'next' and the problem still occurs.

**Comment by sihara** [comment]
I've been seeing exactly same problems many times...

**Comment by johann8384** [comment]
Perhaps this is related to #823

**Comment by katameru** [comment]
We're not using salting, but maybe it's a similar bug in another place in the code?

**Comment by manolama** [comment]
This one should be resolved with AsyncHBase 1.7.2 and TSDB 2.2.1. Give it a try and post a new issue if ya'll see it please.
