### ISSUE TITLE
OpenTSDB restarting after connection reset

### ISSUE THREAD

**Issue by shubhamagarwal003** [OpenTSDB/opentsdb#814]
We have three instances of OpenTSDB behind a load balancer.  Occasionally it  restarts automatically. The logs says a lot of connection reset.

05:10:11.522 ERROR [ConnectionManager.exceptionCaught] - Unexpected exception from downstream for [id: 0x67ebd2c5, ]
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209) ~[na:1.8.0_77]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_77]
        at java.net.SocketInputStream.read(SocketInputStream.java:223) ~[na:1.8.0_77]
        at java.io.FilterInputStream.read(FilterInputStream.java:83) ~[na:1.8.0_77]
        at java.io.PushbackInputStream.read(PushbackInputStream.java:139) ~[na:1.8.0_77]
        at org.jboss.netty.channel.socket.oio.OioWorker.process(OioWorker.java:64) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.oio.AbstractOioWorker.run(AbstractOioWorker.java:73) ~[netty-3.9.4.Final.jar:na]
        at org.jboss.netty.channel.socket.oio.OioWorker.run(OioWorker.java:51) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]

I couldn't understand why there are a lot of connection reset. The same setup is working fine in another datacenter. Can someone help to debug the issue?

**Comment by johann8384** [comment]
It doesn't look like OpenTSDB is the issue, it looks like it got reset from the other side (downstream).

Not sure why it restarts, do you have any logs surrounding this that might be useful? Is the process managed by something that would start it back up again if it died? Perhaps there is a fatal issue and it dies and then is externally restarted.

**Comment by johann8384** [comment]
@shubhamagarwal003 Did you find a resolution to this issue or are you still experiencing it?

**Comment by shubhamagarwal003** [comment]
I was seeing restart due to out of memory. I don't have access to the opentsdb now so wouldn't be able to provide the logs. I'll try contacting the team working on it.

**Comment by manolama** [comment]
Closing for now as this is most likely due to the inflight RPC or NSRE issue. Set ``hbase.nsre.high_watermark`` to a lower value such as ``100`` or ``10``.
