### ISSUE TITLE
Unable to Start Opentsdb Service

### ISSUE THREAD

**Issue by hammad586** [OpenTSDB/opentsdb#826]
Hi All,

I hope i will get some help here regarding setting up opentsdb, I have installed opentsdb on a secured kerberos cluster using this cookbook https://github.com/acaiafa/opentsdb-cookbook, I have done the required settings on opentsdb.conf file including kerberos settings.However whenever I try to start opentsdb service i get the following errors.

10:19:59.756 DEBUG [HBaseClient.handleDisconnect] - Channel [id: 0x301ad776]'s state changed: [id: 0x301ad776] CONNECT :16020
10:19:59.756 WARN  [HBaseClient.call] - Probe Exists(table="hbase:meta", key=[100, 105, 115, 97, 103, 103, 114, 101, 103, 97, 116, 105, 111, 110, 46, 103, 101, 114, 109, 97, 110, 121, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 65, 115, 121, 110, 99, 72, 66, 97, 115, 101, 126, 112, 114, 111, 98, 101, 126, 60, 59, 95, 60, 44, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 65, 115, 121, 110, 99, 72, 66, 97, 115, 101, 126, 112, 114, 111, 98, 101, 126, 60, 59, 95, 60], family=null, qualifiers=null, attempt=0, region=RegionInfo(table="hbase:meta", region_name="hbase:meta,,1", stop_key="")) failed
org.hbase.async.NonRecoverableException: Too many attempts: Exists(table="hbase:meta", key=[100, 105, 115, 97, 103, 103, 114, 101, 103, 97, 116, 105, 111, 110, 46, 103, 101, 114, 109, 97, 110, 121, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 65, 115, 121, 110, 99, 72, 66, 97, 115, 101, 126, 112, 114, 111, 98, 101, 126, 60, 59, 95, 60, 44, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 65, 115, 121, 110, 99, 72, 66, 97, 115, 101, 126, 112, 114, 111, 98, 101, 126, 60, 59, 95, 60], family=null, qualifiers=null, attempt=11, region=RegionInfo(table="hbase:meta", region_name="hbase:meta,,1", stop_key=""))
        at org.hbase.async.HBaseClient.tooManyAttempts(HBaseClient.java:2056) [asynchbase-1.7.1.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1920) [asynchbase-1.7.1.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1944) [asynchbase-1.7.1.jar:na]
        at org.hbase.async.HBaseClient$1RetryRpc.call(HBaseClient.java:1927) [asynchbase-1.7.1.jar:na]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) [async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) [async-1.4.0.jar:na]
        at org.hbase.async.HBaseClient$ZKClient$ZKCallback.processResult(HBaseClient.java:3632) [asynchbase-1.7.1.jar:na]
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:573) [zookeeper-3.4.6.2.3.4.0-3485.jar:3.4.6-3485--1]
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [zookeeper-3.4.6.2.3.4.0-3485.jar:3.4.6-3485--1]
10:19:59.756 DEBUG [HBaseClient.call] - Retrying 3 RPCs on NSREd region "hbase:meta,,1"
10:19:59.757 DEBUG [RegionClient.sendRpc] - RPC queued: HBaseRpc(method=getClosestRowBefore, table="hbase:meta", key="mytable,\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00:AsyncHBase~probe~<;_<,:", region=RegionInfo(table="hbase:meta", region_name="hbase:meta,,1", stop_key=""), attempt=11, timeout=-1, hasTimedout=false)
10:19:59.757 DEBUG [RegionClient.sendRpc] - RPC queued: HBaseRpc(method=getClosestRowBefore, table="hbase:meta", key="mytable-uid,\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00:AsyncHBase~probe~<;_<,:", region=RegionInfo(table="hbase:meta", region_name="hbase:meta,,1", stop_key=""), attempt=11, timeout=-1, hasTimedout=false)
10:19:59.757 INFO  [ClientCnxn.primeConnection] - Socket connection established to :2181, initiating session
10:19:59.757 DEBUG [HBaseClient.disconnectZK] - Ignore any DEBUG exception from ZooKeeper
10:19:59.757 DEBUG [ClientCnxn.primeConnection] - Session establishment request sent on :2181
10:19:59.757 DEBUG [ZooKeeper.close] - Closing session: 0x0
10:19:59.757 DEBUG [ClientCnxn.close] - Closing client for session: 0x0
10:19:59.757 DEBUG [HBaseClient.handleDisconnect] - Channel [id: 0x301ad776, 
10:19:59.757 DEBUG [RegionClient.handleUpstream] - handleUpstream [id: 0x301ad776, 
10:19:59.757 DEBUG [HBaseClient.handleDisconnect] - Channel [id: 0x301ad776, CONNECTED: 
10:19:59.757 DEBUG [RegionClient.handleUpstream] - handleUpstream [id: 0x301ad776, 
10:19:59.757 DEBUG [Login.initUserIfNeeded] - Already logged in
10:19:59.758 INFO  [KerberosClientAuthProvider.newSaslClient] - Connecting to hbase/node@example.com
10:19:59.758 INFO  [KerberosClientAuthProvider.run] - Client will use GSSAPI as SASL mechanism.
10:19:59.758 DEBUG [KerberosClientAuthProvider.run] - Creating sasl client: client=
10:19:59.758 DEBUG [RegionClient.handleUpstream] - handleUpstream [id: 0x301ad776, /10.66.48.100:53332 => /] WRITTEN_AMOUNT: 6
10:19:59.759 DEBUG [RegionClient.handleUpstream] - handleUpstream [id: 0x301ad776, /10.66.48.100:53332 => /10.66.48.102:16020] EXCEPTION: java.io.IOException: Broken pipe
10:19:59.760 ERROR [RegionClient.exceptionCaught] - Unexpected exception from downstream on 
java.io.IOException: Broken pipe

It seems like it reads the meta region and even it tries to read the tables inside hbase and then it gets timeout and in the end an broken pipe issue.

Does anybody faced this problem and does anybody know how to solve this?

**Comment by johann8384** [comment]
I currently have no idea, is this issue still happening or did you find a solution?

**Comment by polingsky** [comment]
I also face problems with kerberos hbase, but my error message is : 

SecureRpcHelper96: Sasl initialization failed with a status of [1]: org.hbase.async.SecureRpcHelper96@4a7b8c4f
2016-09-22 11:08:02,779 ERROR [AsyncHBase I/O Worker #4] RegionClient: Unexpected exception from downstream on [id: 0x036a7ffa, /172.18.0.4:32926 => /172.18.0.8:16020]
java.lang.IllegalArgumentException: Read byte array length that's too large: 1784772193 > 268435455 in buf=ReplayingDecoderBuffer(ridx=12, widx=64)="\x00\x00\x00\x01\x00\x00\x00!javax.security.sasl.SaslException\x00\x00\x00\x13GSS initiate failed"
	at org.hbase.async.HBaseRpc.checkArrayLength(HBaseRpc.java:1021) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.HBaseRpc.readHadoopString(HBaseRpc.java:1088) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.RegionClient.consumeTimedoutNonPBufRPC(RegionClient.java:1640) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:1454) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.2.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223) ~[asynchbase-1.7.2.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121) [asynchbase-1.7.2.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]

my opentsdb version is 2.2 

does anyone find solutions~?

**Comment by IDerr** [comment]
Any news on this @hammad586 : Your opentsdb can't access to hbase:meta table.


I think we close this, since it's not a opentsdb issue but a hbase issue.

@manolama @johann8384

**Comment by youzhagui2006** [comment]
@polingsky  have solve this issue？

**Comment by shitWang** [comment]
same promblem。。。

**Comment by IDerr** [comment]
Hi, Check your regionservers.
Hi @hammad586
if your question has been answered can you close this issue please ?

Thanks

**Comment by HariSekhon** [comment]
I've found an HBase restart followed by an OpenTSDB restart solved it for me.
