### ISSUE TITLE
Error in using explicit tags in v2.3.0RC1

### ISSUE THREAD

**Issue by weikey** [OpenTSDB/opentsdb#837]
Below is error log:

`Caused by: com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
       at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169)
       at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:158)
       at com.stumbleupon.async.DeferredGroup.access$200(DeferredGroup.java:36)
       at com.stumbleupon.async.DeferredGroup$1NotifyOrdered.call(DeferredGroup.java:97)
       at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
       at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
       at com.stumbleupon.async.Deferred.callback(Deferred.java:1005)
       at net.opentsdb.core.TsdbQuery$1ScannerCB.close(TsdbQuery.java:984)
       at net.opentsdb.core.TsdbQuery$1ScannerCB$ErrorCB.call(TsdbQuery.java:718)
       at net.opentsdb.core.TsdbQuery$1ScannerCB$ErrorCB.call(TsdbQuery.java:714)
       at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
       at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
       at com.stumbleupon.async.Deferred.access$300(Deferred.java:430)
       at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366)
       at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
       at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
       at com.stumbleupon.async.Deferred.callback(Deferred.java:1005)
       at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:698)
       at org.hbase.async.RegionClient.decode(RegionClient.java:1516)
       at org.hbase.async.RegionClient.decode(RegionClient.java:88)
       at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
       at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
       at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1206)
       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
       at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
       at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
       at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36)
       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
       at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294)
       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
       at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3108)
       at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
       at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
       at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:724)
Caused by: org.hbase.async.RemoteException: IPC server unable to read call parameters: Error in readFields
       at org.hbase.async.RegionClient.makeException(RegionClient.java:1738)
       at org.hbase.async.RegionClient.deserializeException(RegionClient.java:1717)
       at org.hbase.async.RegionClient.deserialize(RegionClient.java:1581)
       at org.hbase.async.RegionClient.decode(RegionClient.java:1483)
       ... 29 more
`

And I found it only happended  in using FilterList in the QueryUtil, if I change to use ScanFilter directly in scanner.setFilter(), it will be ok.

**Comment by manolama** [comment]
Ahh, good catch. What version of HBase are you running?

**Comment by weikey** [comment]
@manolama  0.94.15-cdh4.6.0

**Comment by weikey** [comment]
Hi, @manolama , can you tell me which version of HBase is ok in your test?

**Comment by manolama** [comment]
@weikey Ah ok, I haven't been using 0.94 in quite some time, we're at 0.98 and 1.0. Let me see if I can track this down.

**Comment by johann8384** [comment]
Got a little over zealous in pushing stuff to 2.3.1, probably should make sure this is working for the 2.3.0RC2.

**Comment by manolama** [comment]
Merged 9e2774c916a26c6049e201df0c64a8f355489566.
Note that you'll still need to set ``tsd.query.enable_fuzzy_filter`` to false in your config since it's 0.94. Thanks!
