### ISSUE TITLE
Endpoint /api/query/exp not responding when groupBy attribute is false 

### ISSUE THREAD

**Issue by aemitos** [OpenTSDB/opentsdb#845]
Hi guys, we are trying to use expressions with the endpoint /api/query/exp.
We are sending this expression below:

```
{
   "time": {
       "start": "2015/01/01",
       "end":"2015/01/04",
       "aggregator":"sum"
   },
   "filters": [
       {
           "tags": [
               {
                   "type": "iliteral_or",
                   "tagk": "key",
                   "filter": "0|1",
                   "groupBy":false
               }
           ],
           "id": "f1"
       },{
           "tags": [
               {
                   "type": "literal_or",
                   "tagk": "key",
                   "filter": "0",
                   "groupBy": false
               }
           ],
           "id": "f2"
       }
   ],
   "metrics": [
       {
           "id": "a",
           "metric": "test_put1",
           "filter": "f1",
           "fillPolicy":{"policy":"nan"}
       },
       {
           "id": "b",
           "metric": "test_put2",
           "filter": "f2",
           "fillPolicy":{"policy":"nan"}
       }
   ],
   "expressions": [
       {
           "id": "c",
           "expr": "a + b"
       }
    ],
    "outputs":[
      {"id":"c", "alias":"Test expression"}
    ]
 }
```
If we change the filter's flag "groupBy" to `true`, the expression works fine but the result per point is `[1420077600000,3500,100]`, like below:
```
{
  "outputs": [
    {
      "id": "c",
      "alias": "Test expression",
      "dps": [
        [
          1420077600000,
          3500,
          100
        ],
        [
          1420164000000,
          3500,
          100
        ],
        [
          1420250400000,
          3500,
          100
        ],
        [
          1420336800000,
          3500,
          100
        ]
      ],
      "dpsMeta": {
        "firstTimestamp": 1420077600000,
        "lastTimestamp": 1420336800000,
        "setCount": 4,
        "series": 2
      },
      "meta": [
        {
          "index": 0,
          "metrics": [
            "timestamp"
          ]
        },
        {
          "index": 1,
          "metrics": [
            "test_put1",
            "test_put2"
          ],
          "commonTags": {
            "key": "0"
          },
          "aggregatedTags": []
        },
        {
          "index": 2,
          "metrics": [
            "test_put1",
            "test_put2"
          ],
          "commonTags": {
            "key": "1"
          },
          "aggregatedTags": []
        }
      ]
    }
  ],
  "query": {
    "name": null,
    "time": {
      "start": "2015/01/01",
      "end": "2015/01/04",
      "timezone": null,
      "downsampler": null,
      "aggregator": "sum",
      "rate": false
    },
    "filters": [
      {
        "id": "f1",
        "tags": [
          {
            "tagk": "key",
            "filter": "0|1",
            "group_by": true,
            "type": "iliteral_or"
          }
        ],
        "explicitTags": false
      },
      {
        "id": "f2",
        "tags": [
          {
            "tagk": "key",
            "filter": "0",
            "group_by": true,
            "type": "literal_or"
          }
        ],
        "explicitTags": false
      }
    ],
    "metrics": [
      {
        "metric": "test_put1",
        "id": "a",
        "filter": "f1",
        "aggregator": null,
        "timeOffset": null,
        "fillPolicy": {
          "policy": "nan",
          "value": "NaN"
        }
      },
      {
        "metric": "test_put2",
        "id": "b",
        "filter": "f2",
        "aggregator": null,
        "timeOffset": null,
        "fillPolicy": {
          "policy": "nan",
          "value": "NaN"
        }
      }
    ],
    "expressions": [
      {
        "id": "c",
        "expr": "a + b",
        "join": {
          "operator": "union",
          "useQueryTags": false,
          "includeAggTags": true
        },
        "fillPolicy": null
      }
    ],
    "outputs": [
      {
        "id": "c",
        "alias": "Test expression"
      }
    ]
  }
}
```
But we want the result per point like `[1420077600000,3600]`, so the sum for the 3 points that will match with the filter, that are 2000,1500 and 100.
You can see the time series in the image attached.

![image](https://cloud.githubusercontent.com/assets/1443757/17624833/adcc98c8-607c-11e6-8281-8aca11f8205e.png)

The problem is that if we set `groupBy` as false in the filters structures, the TSD doesn't respond, like the image below.

![image](https://cloud.githubusercontent.com/assets/1443757/17624776/71e5ba24-607c-11e6-944d-d3e6b3e9a655.png)

Is this a bug or we are doing something wrong?
Thanks in advance
Regards
André

**Comment by katameru** [comment]
See https://github.com/OpenTSDB/opentsdb/issues/794

**Comment by aemitos** [comment]
Hi @katameru 
Just to clarify, we are using version:
```
OpenTSDB version [2.3.0-RC1] built from revision 306603c in a MINT state
Built on Mon May 02 16:02:35 GMT-300 2016 by hobbes@clhbase:/home/hobbes/opentsdb_OFFICIAL/build
```
Last .deb available in the github release session.
The endpoint commented in the issue #794 is `/api/query` not `/api/query/exp`. And it's correct, using `/api/query` the behavior is like described, but why when we use `"groupBy": false` in a filter of an expression the TSD doesn't respond?
Again, thank you in advance and sorry if it's a dumb question :|
Regards
André

**Comment by aemitos** [comment]
Hi again, @katameru 
I made a test with the endpoint `/api/query` and it stays in loading forever too.
The query is listed below:
```
{
    "start": "2015/01/01",
    "end": "2015/04/01",
    "queries" : [
    {
        "aggregator":"sum",
        "metric":"test_put1",
        "rate":false,
        "filters": [
                {
                   "type":"literal_or",
                   "tagk":"key",
                   "filter":"0|1",
                   "groupBy":false
                }
        ]
    }
]
}
```
Here you can see a screenshot:

![image](https://cloud.githubusercontent.com/assets/1443757/17628009/c5a3e1c4-6089-11e6-8bf3-64140db3fe01.png)

Best regards
André

**Comment by aemitos** [comment]
Other tests:

GET in here:
`http://192.168.30.80:4242/api/query?start=2015/01/01&end=2015/01/05&m=sum:test_put1{}{key=0|1}{}`
Returns:
```
[
{
metric: "test_put1",
tags: { },
aggregateTags: [
"key"
],
dps: {
1420077600: 2100,
1420164000: 2100,
1420250400: 2100,
1420336800: 2100,
1420423200: 2100
}
}
]
```
But this fails `http://192.168.30.80:4242/api/query?start=2015/01/01&end=2015/01/05&m=sum:test_put1{}{key=0|1}`

With the same log of the POST:
```
13:10:18.331 WARN  [HttpQuery.logWarn] - [id: 0x01ff9913, /192.168.30.1:56713 => /192.168.30.80:4242] Bad Request on /api/query?start=2015/01/01&end=2015/01/05&m=sum:test_put1{}{key=0|1}: null
13:10:18.332 ERROR [QueryRpc.call] - Exception thrown during exception handling
java.lang.NullPointerException: null
	at net.opentsdb.tsd.HttpSerializer.formatErrorV1(HttpSerializer.java:834) ~[tsdb-2.3.0-RC1.jar:306603c]
	at net.opentsdb.tsd.HttpQuery.badRequest(HttpQuery.java:413) ~[tsdb-2.3.0-RC1.jar:306603c]
	at net.opentsdb.tsd.QueryRpc$1ErrorCB.call(QueryRpc.java:212) [tsdb-2.3.0-RC1.jar:306603c]
	at net.opentsdb.tsd.QueryRpc$1ErrorCB.call(QueryRpc.java:172) [tsdb-2.3.0-RC1.jar:306603c]
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) [async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) [async-1.4.0.jar:na]
	at com.stumbleupon.async.Deferred.addErrback(Deferred.java:756) [async-1.4.0.jar:na]
	at net.opentsdb.tsd.QueryRpc.handleQuery(QueryRpc.java:306) [tsdb-2.3.0-RC1.jar:306603c]
	at net.opentsdb.tsd.QueryRpc.execute(QueryRpc.java:111) [tsdb-2.3.0-RC1.jar:306603c]
	at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [tsdb-2.3.0-RC1.jar:306603c]
	at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [tsdb-2.3.0-RC1.jar:306603c]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
	at net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:128) [tsdb-2.3.0-RC1.jar:306603c]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

And this just runs the query as the first test `http://192.168.30.80:4242/api/query?start=2015/01/01&end=2015/01/05&m=sum:test_put1{key=0|1}{}`, without grouping.
Thanks in advance
Best regards
André

**Comment by katameru** [comment]
Oh, I didn't notice that you were using a different endpoint. But the error message looks the same, I think. In any case the fix is in the `next` branch, so you can either compile it yourself or wait until they release a new RC.

**Comment by aemitos** [comment]
Ok, great @katameru 
we are creating an OpenTSDB HTTP API client in here https://github.com/venidera/otsdb_client
That's why all the tests.
Thank you very much for your time and answers.
Best regards
André

**Comment by aemitos** [comment]
Ok, great @katameru 
we are creating an OpenTSDB HTTP API client in here https://github.com/venidera/otsdb_client
That's why all the tests.
Thank you very much for your time and answers.
Best regards
André
