### ISSUE TITLE
The option auto-metric didn't work

### ISSUE THREAD

**Issue by leell** [OpenTSDB/opentsdb#864]
I start the TSDB with following commond in opentsdb.conf:
`tsd.core.auto_create_metrics = true`
However, when I am trying to add new datapoint, a exception shows No such name for 'metrics'.
I used `import  /usr/local/opentsdb/test/test1` to add datapoint. And the  contents of test1 is:
`testMetric 1473257777 12 testTag=lll`
The exception is as follow.
Exception in thread "main" net.opentsdb.uid.NoSuchUniqueName: No such name for 'metrics': 'testMetric'
	at net.opentsdb.uid.UniqueId$1GetIdCB.call(UniqueId.java:315)
	at net.opentsdb.uid.UniqueId$1GetIdCB.call(UniqueId.java:312)
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)

I also trid to start the TSDB  using the following command.
`./build/tsdb tsd  --auto-metric=true`
But it didn't work either.

Please help me with this.

Many thanks,

Lee

**Comment by johann8384** [comment]
When you pull up /api/config in the browser, what are the values for those properties?

`tsd.core.auto_create_metrics: "true",
tsd.core.auto_create_tagks: "true",
tsd.core.auto_create_tagvs: "true",`

**Comment by leell** [comment]
Yes, these three properties all shows true in the brower.

**Comment by manolama** [comment]
Hm, which distro are you using and which version? I haven't run into this issue yet. You may want to check the file permissions on the log files as well as maybe they were created but the TSD isn't writing.

**Comment by leell** [comment]
The version of my opentsdb is 2.2.0. 
The opentsdb.log and queries.log were automatically create in /var/log/opentsdb. And I have the permission to read and write.
![20160930104834](https://cloud.githubusercontent.com/assets/22073473/18979200/6a2a6384-86fb-11e6-9fbf-02762c05203c.png)

**Comment by leell** [comment]
I installed OpenTSDB 2.3.0 RC1 with rpm instead of tar.gz file. And every problem above has solved.

**Comment by freiman** [comment]
We have same issue with auto-metric option. Metrics, tagv and tagk were not creating when we sent values into OpenTSDB. We use Debian distribution, OpenTSDB is installed by Debian package from github, version is 2.3.0-RC2, hbase is in version 1.2.0+cdh5.9.0+205-1.cdh5.9.0.p0.30~wheezy-cdh5.9.0, hadoop is used for lzo compression. Every option from config api returns true.
Can you help us? Thanks
