### ISSUE TITLE
OpenTSDB Installation issue with Java8 + CDH 5.7+Hbase 1.2

### ISSUE THREAD

**Issue by Explorer89** [OpenTSDB/opentsdb#882]
While starting the OpenTSDB in CDH 5.7 , am getting the below error ,
I was following the  deployment instructions from  http://opentsdb.net/docs/build/html/installation.html

Exception in thread "main" java.lang.RuntimeException: Initialization failed
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:196)
Caused by: java.lang.NoSuchMethodError: org.jboss.netty.util.HashedWheelTimer.<init>(Ljava/util/concurrent/ThreadFactory;Lorg/jboss/netty/util/ThreadNameDeterminer;JLjava/util/concurrent/TimeUnit;I)V
	at org.hbase.async.HBaseClient.newTimer(HBaseClient.java:627)
	at org.hbase.async.HBaseClient.defaultChannelFactory(HBaseClient.java:656)
	at org.hbase.async.HBaseClient.<init>(HBaseClient.java:557)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:150)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:220)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:150)

And service opentsdb start   was also failing ,with message ,
opentsdb: unrecognized service

Am using CDH 5.7 ,HBase 1.2, Java 8 ,OpenTSDB 2.2.0

**Comment by Explorer89** [comment]
Any idea on this issue  ?

**Comment by nickman** [comment]
That looks like an incorrect version of netty.  Not sure how that would
happen, but can you report back your full class path ?

**Comment by Explorer89** [comment]
Hi ,
I also think the same . The issue is there with OpenTSDB version 2.2.0 .
But version 2.1.0 installation was successful .But opentsdb ui is not
coming up .i tried with http://<hostname>:4242 , but in vein . The service
is running at 4242 .

For the issue with netty on opentsdb 2.2.0 , is this a known isuue ? Below
is theclasspath ,
:/u01/connectors/olh/jlib/*:/usr/lib/hadoop/*:/usr/lib/hadoop/client/*:/u01/nosql/kv-ee/lib/kvstore.jar:.

Thanks,
Giri

Thanks & Regards,
Giri
+919995857088

**Comment by nickman** [comment]
I've not seen the issue before, but based on the stack trace, that looks
most likely.

Can you provide the full class path ? Want to know which netty jar is
resident.

Is it possible that the netty jar from the prior installation of OpenTSDB
is still hanging around ?

**Comment by Explorer89** [comment]
Hi ,

Please find the classpath
ls /usr/local/share/opentsdb/lib
async-1.4.0.jar          guava-18.0.jar
jackson-databind-2.4.3.jar  logback-core-1.0.13.jar  slf4j-api-1.7.7.jar
asynchbase-1.7.1.jar     jackson-annotations-2.4.3.jar
 log4j-over-slf4j-1.7.7.jar  netty-3.9.4.Final.jar    tsdb-2.2.0.jar
commons-math3-3.4.1.jar  jackson-core-2.4.3.jar
logback-classic-1.0.13.jar  protobuf-java-2.5.0.jar  zookeeper-3.4.5.jar

The issue is clearly with opentsdb-2.2.0 . I have tried opentsdb-2.1.0  and
it is running on 4242 .
netstat -nlp | grep 4242
tcp        0      0 ::ffff:127.0.0.1:4242       :::*
 LISTEN      23507/java

But http://localhost:4242 giving no response. So two issues am facing with
two versions of opentsdb during installation itself .

Thanks


Thanks & Regards,
Giri
+919995857088

**Comment by manolama** [comment]
Hi @Explorer89 can you take a look at the log file from OpenTSDB? If the UI isn't coming up but it's listening on 4242 then it may not have loaded the static files properly. Also try loading http://127.0.0.1:4242/api/stats to see if it comes up.

**Comment by Explorer89** [comment]
Hi Chris,

Am not finding any logs .Nothing is printed on the console after ,

tsdb tsd
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in
[jar:file:/usr/lib/zookeeper/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in
[jar:file:/usr/local/share/opentsdb/lib/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an
explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger
(net.opentsdb.tools.TSDMain).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
more info.

  http://127.0.0.1:4242/api/stats gave no response .



Thanks & Regards,
Giri
+919995857088

**Comment by manolama** [comment]
That's odd too in that it found log4j. Did you install 2.2 from a package and if so, which version?

**Comment by Explorer89** [comment]
Hi Chris,

No. 2.2.0 is giving netty error which i stated in the first email.

Am using opentsdb-2.1.0.tar.gz downloaded from github.

Thanks

Thanks & Regards,
Giri
+919995857088

**Comment by manolama** [comment]
Hmm, I just tried the CDH 5.8 VM from Cloudera with 2.1.0 from the Github releases and it worked (though Gnuplot couldn't find a font it needed).

But the fact that 2.2 was giving you class path errors says something is odd about your host config in that it's picking up the wrong classes. Did you run a ``sh build.sh`` and then ``sh build.sh install`` and tried running TSDB that way?

**Comment by Explorer89** [comment]
Hi Chris ,

Both issues still exist .



Thanks & Regards,
Giri
+919995857088

**Comment by Explorer89** [comment]
Hi Chris,

Any ideas ??

Thanks & Regards,
Giri
+919995857088

**Comment by Explorer89** [comment]
Tried again https://github.com/OpenTSDB/opentsdb/wiki/Installation-on-Cloudera-Virtual-Machine

Still the same issue ,



Exception in thread "main" java.lang.RuntimeException: Initialization failed
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:196)
Caused by: java.lang.NoSuchMethodError: org.jboss.netty.util.HashedWheelTimer.<init>(Ljava/util/concurrent/ThreadFactory;Lorg/jboss/netty/util/ThreadNameDeterminer;JLjava/util/concurrent/TimeUnit;I)V
	at org.hbase.async.HBaseClient.newTimer(HBaseClient.java:627)
	at org.hbase.async.HBaseClient.defaultChannelFactory(HBaseClient.java:656)
	at org.hbase.async.HBaseClient.<init>(HBaseClient.java:557)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:150)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:220)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:150)

PFb the path ,
echo $PATH
/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/lib64/R/bin:/u01/Middleware/jdeveloper/jdev/bin:/usr/java/latest/bin:/u01/app/oracle/product/12.1.0.2/dbhome_1/bin:/home/oracle/scripts:/opt/bin:/u01/sqlcl/bin:/u01/connectors/ohsh/bin:/root/bin
[root@bigdatalite Downloads]# echo $CLASSPATH
:/u01/connectors/olh/jlib/*:/usr/lib/hadoop/*:/usr/lib/hadoop/client/*:/u01/nosql/kv-ee/lib/kvstore.jar:.

ls third_party/netty/
include.mk  netty-3.9.1.Final.jar.md5  netty-3.9.4.Final.jar.md5

**Comment by karanalang** [comment]
Hello - 
Were you able to fix this issue ?
i'm getting the same error on starting OpenTSDB 2.2.1 on HDP 2.4

here are the details -> 

Command ->
/root/opentsdb/build/tsdb import /root/opentsdb/data/opentsd.input --zkbasedir=/hbase-unsecure --zkquorum=localhost:2181 --auto-metric

Error ->
SLF4J: Class path contains multiple SLF4J bindings. SLF4J: Found binding in [jar:file:/usr/hdp/2.4.0.0-169/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class] SLF4J: Found binding in [jar:file:/root/opentsdb/third_party/logback/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation. SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory] log4j:WARN No appenders could be found for logger (net.opentsdb.utils.Config). log4j:WARN Please initialize the log4j system properly. log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Exception in thread "main" java.lang.NoSuchMethodError: org.jboss.netty.util.HashedWheelTimer.<init>(Ljava/util/concurrent/ThreadFactory;Lorg/jboss/netty/util/ThreadNameDeterminer;JLjava/util/concurrent/TimeUnit;I)V at org.hbase.async.HBaseClient.newTimer(HBaseClient.java:627) at org.hbase.async.HBaseClient.defaultChannelFactory(HBaseClient.java:656) at org.hbase.async.HBaseClient.<init>(HBaseClient.java:557) at net.opentsdb.core.TSDB.<init>(TSDB.java:150) at net.opentsdb.core.TSDB.<init>(TSDB.java:220) at net.opentsdb.tools.TextImporter.main(TextImporter.java:68)

Pls note -> when i run OpenTSB v 2.0.1 - it seems to go through fine.

The netty version in both installs in identical.
Pls see below :

ON v 2.2.1
----------------
[root@sandbox netty]# pwd
/root/opentsdb-2.2.1/third_party/netty
[root@sandbox netty]# ls -lrt
total 1288
-rw-rw-r-- 1 1000 1000      33 2016-05-02 19:02 netty-3.9.4.Final.jar.md5
-rw-rw-r-- 1 1000 1000    1908 2016-05-02 19:02 include.mk
-rw-rw-r-- 1 1000 1000 1310154 2016-10-08 18:55 netty-3.9.4.Final.jar


ON v2.0.1
-------------
[root@sandbox netty]# pwd
/root/opentsdb-2.0.1/third_party/netty
[root@sandbox netty]# ls -lrt
total 1288
-rw-r--r-- 1 root root      33 2014-10-14 06:02 netty-3.9.4.Final.jar.md5
-rw-r--r-- 1 root root    1908 2014-10-14 06:02 include.mk
-rw-r--r-- 1 root root 1310154 2014-11-09 23:32 netty-3.9.4.Final.jar

**Comment by Explorer89** [comment]
Hi Karan,

I could fix it  by removing some jar conflicts . In my case , the classpath
 had  older versions of netty.jar,slf4j-log4j.jar and  guava.jar  in
/usr/lib/hadoop/client /usr/lib/zookeeper/lib ,/usr/lib/hadoop/client
respectively .

Glad to know that this is not a random case . I had to crawl through all
classpath files to fix it .

Thanks


Thanks & Regards,
Giri
+919995857088

**Comment by IDerr** [comment]
I think you can close this @manolama

**Comment by IDerr** [comment]
Hi @Explorer89 
if your question has been answered can you close this issue please ?

Thanks
