### ISSUE TITLE
Open TSDB and Cassendra

### ISSUE THREAD

**Issue by pavanshetty05** [OpenTSDB/opentsdb#894]
Hi Team 
     Presently we are integrating opentsdb_temp-2.3.0RC1 and apache-cassandra-2.0.2 .We created table tsdb and tsdbuid as per the guideline  mentioned in below link.  We are getting below exception . It look like there is some configuration missed in the documentation . 
http://opentsdb.net/docs/build/html/user_guide/backends/cassandra.html 
2016-11-21 05:49:28,321 ERROR [OpenTSDB I/O Worker #2] HttpQuery: [id: 0x4050af94, /0:0:0:0:0:0:0:1:54213 => /0:0:0:0:0:0:0:1:4242] Internal Server Error on /api/put
java.lang.RuntimeException: Should never be here 
	at net.opentsdb.uid.UniqueId.getOrCreateId(UniqueId.java:742) ~[tsdb-2.3.0-RC1.jar:]
	at net.opentsdb.core.IncomingDataPoints.rowKeyTemplate(IncomingDataPoints.java:139) ~[tsdb-2.3.0-RC1.jar:]
	at net.opentsdb.core.TSDB.addPointInternal(TSDB.java:963) ~[tsdb-2.3.0-RC1.jar:]
	at net.opentsdb.core.TSDB.addPoint(TSDB.java:873) ~[tsdb-2.3.0-RC1.jar:]
	at net.opentsdb.tsd.PutDataPointRpc.execute(PutDataPointRpc.java:207) ~[tsdb-2.3.0-RC1.jar:]
	at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [tsdb-2.3.0-RC1.jar:]
	at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [tsdb-2.3.0-RC1.jar:]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.9.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]

**Comment by manolama** [comment]
HI @pavanshetty05, Hmm, that's an odd one in that it's not printing out a useful error message. 

Can you check the TSD logs and see if there are other error messages in there with some more detail? Thanks!
