### ISSUE TITLE
Fail to resolve the IP but I have no permisson to modify hosts file

### ISSUE THREAD

**Issue by zhengshimin** [OpenTSDB/opentsdb#941]
Hi team,
    When I used OpenTSDB, I met a problem that OpenTSDB gets HBase's hostnames from zookeepers and then resolves these to ips. But there is no permission to modify hosts file in the OpenTSDB client. So when I run tsdb,  I get the following problem:

_09:14:00.688 [main-EventThread] ERROR org.hbase.async.HBaseClient - Failed to resolve the IP of `slave159' in 199416139ns
09:14:00.689 [main-EventThread] INFO  org.hbase.async.HBaseClient - Connecting to .META. region @ null:16020
09:14:00.722 [main-EventThread] DEBUG org.hbase.async.HBaseClient - Channel [id: 0xf82b0db6]'s state changed: [id: 0xf82b0db6] OPEN
09:14:00.724 [main-EventThread] DEBUG org.hbase.async.RegionClient - handleUpstream [id: 0xf82b0db6] OPEN
09:14:00.730 [main-EventThread] ERROR org.apache.zookeeper.ClientCnxn - Caught unexpected throwable
java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149) ~[na:1.8.0_92]
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216) ~[na:1.8.0_92]
	at org.hbase.async.HBaseClient.newClient(HBaseClient.java:3055) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.HBaseClient.access$3200(HBaseClient.java:190) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.HBaseClient$ZKClient$ZKCallback.handleMetaZnode(HBaseClient.java:3778) ~[asynchbase-1.7.2.jar:na]
	at org.hbase.async.HBaseClient$ZKClient$ZKCallback.processResult(HBaseClient.java:3634) ~[asynchbase-1.7.2.jar:na]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:561) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) [zookeeper-3.4.6.jar:3.4.6-1569965]
_

I tried to look up asyncHBase code but I couldn't find how to configure the HBase ips. Are there some ways to solve the problem? I have the HBase ips  and could OpenTSDB connect to HBase master directly? Or have some methods to configure?

**Comment by manolama** [comment]
Hi, the names of region servers are stored in HBase's meta table as FQDNs. There may be a configuration in HBase that could force the server to store them as IPs so you may want to look at the documentation to see if that's possible. Otherwise I don't know of a good way to fix that other than, as you said, hack the AsyncHBase code to perform some kind of lookup given your name to ip file.

**Comment by IDerr** [comment]
I think it has been answered.

You can close this one @manolama

**Comment by IDerr** [comment]
@zhengshimin Could close this issue if you don't have others questions ?

Thanks :)
