### ISSUE TITLE
Unexpected exception caught by UniqueId

### ISSUE THREAD

**Issue by c61811** [OpenTSDB/opentsdb#956]
Today, Results show that is exceptional, when I used suggest to search for an api url . eg: http://localhost:4242/api/suggest?type=metrics&q=apps&max=1000. 
the message is following:

> Unexpected exception caught by UniqueId(jdh_doctor:jdh_tsdb_uid, metrics, 3).suggest(apps)

the trace is following:

> trace: "java.lang.RuntimeException: Unexpected exception caught by UniqueId(jdh_doctor:jdh_tsdb_uid, metrics, 3).suggest(apps) at net.opentsdb.uid.UniqueId.suggest(UniqueId.java:776) ~[tsdb-2.2.0RC1.jar:] at net.opentsdb.core.TSDB.suggestMetrics(TSDB.java:996) ~[tsdb-2.2.0RC1.jar:] at net.opentsdb.tsd.SuggestRpc.execute(SuggestRpc.java:80) ~[tsdb-2.2.0RC1.jar:] at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [tsdb-2.2.0RC1.jar:] at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [tsdb-2.2.0RC1.jar:] at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.9.4.Final.jar:na] at 

Excuse me, How is this error happen. Thanks!

**Comment by c61811** [comment]
otherwise, the same to connection of hbase table, and the same to request parameters. that sameone of request is ok, but other one of request is error.

**Comment by c61811** [comment]
![image](https://cloud.githubusercontent.com/assets/1625296/24228405/f125bdf2-0fae-11e7-9439-9bf6ddf5c083.png)
we are find that reason, tsd.uid.cache-hit number is minus. but why is  this number minus. 

through search system meteics. found the cache is not enough. the following:
![image](https://cloud.githubusercontent.com/assets/1625296/24228621/6d659864-0fb0-11e7-8e78-e3d80cadb6b8.png)

**Comment by manolama** [comment]
It looks almost like the HTTP connection was closed or had an issue before the response. Can you reproduce it with later versions of TSD? (Also I think there was a fix after RC1 for the negative counts.

**Comment by c61811** [comment]
Has been solved, is int the result of plastic overflow!
