### ISSUE TITLE
ConnectionManager: Unexpected exception from downstream for [id: 0x498b14cf, /127.0.0.1:51050 => /127.0.0.1:4242]

### ISSUE THREAD

**Issue by stopter** [OpenTSDB/opentsdb#993]
hello
I use cjson and c++socket  to achieve http
then I use http api to write my quote data to open tsdb
most data was wirted successfully,but some data hava a error Bad Request on /api/put: Unable to parse the given JSON in opentsdb log,then opentsdb have an error:
"ConnectionManager: Unexpected exception from downstream for [id: 0x498b14cf, /127.0.0.1:51050 => /127.0.0.1:4242]
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[na:1.8.0_131]"

it is incredible,because it is from cjson,

**Comment by stopter** [comment]
resolved,because write some big timestemp that > int64
